#!/usr/bin/env python3
"""
Random Dungeon content generator (items, loot, enemies, icons, translations).

Source of truth (edit these, then re-run this script):
  tools/ek_data/items.csv        one row per item (names, level, damage, bonuses, tint...)
  tools/ek_data/enemies.csv      one row per enemy variant (template, sprite, tint, strength)
  tools/ek_data/loot_bands.csv   drop chances per enemy grade  <-- "chance de loot"
  PALETTE below                  the color filters (tints) used by items and enemies

Everything this script writes is marked GENERATED at the top -- don't hand-edit
those files, edit the CSVs instead:
  items/items.txt, items/categories/rd_items.txt, items/sets.txt
  engine/icons.txt, images/icons/icons_rd.png
  animations/avatar/<body>/rd_*.txt      (tinted equipment layers)
  animations/enemies/rd/*.txt            (tinted enemy sprites)
  enemies/rd_*.txt, loot/rd_*.txt
  languages/data.pt_BR.po, languages/data.pt.po  (Portuguese names)
  ../ek_icons/images/icons/icons_rd.png  (optional mod with the original EK icons, see README)

Usage:  python3 tools/gen_content.py            (uses cached EK icons, downloads missing ones)
        python3 tools/gen_content.py --offline  (never touch the network)
"""
import csv, os, re, sys, urllib.request
from PIL import Image

TOOLS = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(TOOLS)
MODS = os.path.dirname(MOD)
DATA = os.path.join(TOOLS, 'ek_data')
EK_CACHE = os.path.join(DATA, 'ek_icons_cache')      # gitignored (not our art)
EK_MOD = os.path.join(MODS, 'ek_icons')              # gitignored (not our art)
BASE_MODS = ['empyrean_campaign', 'fantasycore']     # lookup order for base files
BODIES = ['male', 'female', 'female_dark']
ICON_FIRST_ID = 4096
ICON = 64
HEADER = '# GENERATED by tools/gen_content.py from tools/ek_data/*.csv -- edit those, not this file.\n'

# Color filters ("skins"). Multiplicative, like the engine's color_mod: 255 = unchanged,
# lower = darker in that channel. Optional 4th value = alpha (255 opaque).
PALETTE = {
    # metals / materials
    'iron':       (175, 170, 165),
    'silver':     (225, 235, 255),
    'bluesteel':  (150, 180, 255),
    'adamantite': (140, 215, 190),
    'hardened':   (185, 150, 115),
    'forest':     (150, 205, 140),
    'blessed':    (170, 190, 255),
    'ice':        (185, 225, 255),
    'gold':       (255, 215, 120),
    'crimson':    (225, 115, 105),
    'ashen':      (105, 100, 100),
    'shadow':     (95, 90, 110),
    'fire':       (255, 140, 90),
    # creatures
    'rust':       (205, 160, 130),
    'royal':      (255, 205, 90),
    'blood':      (255, 90, 80),
    'orc':        (190, 225, 160),
    'steel':      (170, 180, 205),
    'frost':      (140, 175, 255),
    'arcane':     (195, 165, 255),
    'dusk':       (170, 140, 200),
    'bone':       (240, 230, 200),
    'ghoul':      (170, 200, 150),
    'mummy':      (235, 215, 165),
    'ancient':    (200, 170, 120),
    'ghost':      (190, 255, 205, 140),
    'spectral':   (170, 190, 255, 150),
    'wraith':     (255, 110, 110, 170),
    'deathknight': (110, 105, 140, 200),
    'sand':       (230, 200, 140),
    'venom':      (150, 230, 110),
    'infernal':   (210, 75, 60),
}
# automatic filter for elemental weapons that have no tint of their own
ELEM_TINT = {'fire': 'fire', 'ice': 'ice', 'lightning': 'gold', 'dark': 'venom'}
# XP per kill = 2 * strength * XP_BASE, times the il table (x2 per enemy level).
# The campaign's own numbers (XP_BASE=1) need ~128 same-level kills per hero
# level; 5 makes it ~26. The infinite run adds engine/horde.txt xp_multiplier.
XP_BASE = 5
QUALITY = {'common': 'normal', 'uncommon': 'high', 'rare': 'epic', 'unique': 'unique'}


def rel(*p):
    return os.path.join(MOD, *p)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf8') as f:
        f.write(text)


def locate(relpath):
    """Find a data file the way the engine would (our mod first, then base mods)."""
    for m in [os.path.basename(MOD)] + BASE_MODS:
        p = os.path.join(MODS, m, relpath)
        if os.path.exists(p):
            return p
    return None


def read_kv(relpath):
    """key=value pairs of a base file, following INCLUDEs (last value wins)."""
    out = {}
    p = locate(relpath)
    if not p:
        return out
    # fantasycore holds the full definition; empyrean may APPEND to it
    paths = [os.path.join(MODS, m, relpath) for m in reversed(BASE_MODS)]
    for p in paths:
        if not os.path.exists(p):
            continue
        for line in open(p, encoding='utf8'):
            line = line.strip()
            if line.startswith('INCLUDE '):
                out.update(read_kv(line.split(None, 1)[1]))
            elif '=' in line and not line.startswith('#'):
                k, v = line.split('=', 1)
                out[k] = v
    return out


def tint_rgb(name):
    c = PALETTE[name]
    return c[:3], (c[3] if len(c) > 3 else 255)


def color_mod_lines(name):
    rgb, a = tint_rgb(name)
    s = 'color_mod=%d,%d,%d\n' % rgb
    if a != 255:
        s += 'alpha_mod=%d\n' % a
    return s


def bonuses(s):
    out = []
    for part in (s or '').split(';'):
        if part.strip():
            k, v = part.split(':')
            out.append((k.strip(), v.strip()))
    return out


# ------------------------------------------------------------------ icons
_sheet = None


def flare_icon(idx):
    global _sheet
    if _sheet is None:
        _sheet = Image.open(os.path.join(MODS, 'fantasycore/images/icons/icons.png')).convert('RGBA')
    cols = _sheet.width // ICON
    x, y = (idx % cols) * ICON, (idx // cols) * ICON
    return _sheet.crop((x, y, x + ICON, y + ICON))


def tinted(img, name):
    if not name:
        return img
    rgb, _ = tint_rgb(name)
    r, g, b, a = img.split()
    r = r.point(lambda v: v * rgb[0] // 255)
    g = g.point(lambda v: v * rgb[1] // 255)
    b = b.point(lambda v: v * rgb[2] // 255)
    return Image.merge('RGBA', (r, g, b, a))


def ek_icon(url, offline):
    if not url:
        return None
    fn = os.path.join(EK_CACHE, url.rsplit('/', 1)[1])
    if not os.path.exists(fn):
        if offline:
            return None
        os.makedirs(EK_CACHE, exist_ok=True)
        req = urllib.request.Request('https://www.exiledkingdoms.com' + url, headers={'User-Agent': 'Mozilla/5.0'})
        try:
            data = urllib.request.urlopen(req, timeout=30).read()
        except Exception as e:
            print('  ! could not download %s: %s' % (url, e))
            return None
        open(fn, 'wb').write(data)
    im = Image.open(fn).convert('RGBA')
    if im.size != (ICON, ICON):
        # EK icons are 60 or 64 px: pad (don't blur) smaller ones, shrink bigger ones
        if im.width <= ICON and im.height <= ICON:
            canvas = Image.new('RGBA', (ICON, ICON), (0, 0, 0, 0))
            canvas.alpha_composite(im, ((ICON - im.width) // 2, (ICON - im.height) // 2))
            im = canvas
        else:
            im = im.resize((ICON, ICON), Image.LANCZOS)
    return im


# ------------------------------------------------------------------ items
def gen_items(offline):
    items = list(csv.DictReader(open(os.path.join(DATA, 'items.csv'), encoding='utf8')))
    cols = 8
    rows = (len(items) + cols - 1) // cols
    sheet = Image.new('RGBA', (cols * ICON, rows * ICON), (0, 0, 0, 0))
    ek_sheet = sheet.copy()
    out = [HEADER]
    avatar_tints = set()
    missing_ek = 0

    for n, it in enumerate(items):
        base = read_kv(it['base'])
        if not it['tint']:
            elems = [k[4:-4] for k, _ in bonuses(it['bonuses']) if k.startswith('dmg_') and k.endswith('_min')]
            if elems and elems[0] in ELEM_TINT:
                it = dict(it, tint=ELEM_TINT[elems[0]])
        icon_id = ICON_FIRST_ID + n
        pos = ((n % cols) * ICON, (n // cols) * ICON)
        flare = tinted(flare_icon(int(base.get('icon', 0))), it['tint'])
        sheet.alpha_composite(flare, pos)
        ek = ek_icon(it['ek_icon'], offline)
        if ek is None:
            missing_ek += 1
        if ek is not None and it.get('flavor') == 'extrapolated':
            ek = tinted(ek, it['tint'])  # borrowed icon (e.g. Bluesteel) recolored for the new material
        ek_sheet.alpha_composite(ek if ek is not None else flare, pos)

        out.append('\n[item]\nid=%s\nname=%s\n' % (it['id'], it['name']))
        if it.get('flavor') and it['flavor'] != 'extrapolated':
            out.append('flavor=%s\n' % it['flavor'])
        out.append('INCLUDE %s\n' % it['base'])
        out.append('level=%s\nquality=%s\nicon=%d\nprice=%s\n' % (it['level'], QUALITY[it['band']], icon_id, it['price']))
        out.append('requires_level=%s\n' % it['level'])
        if it['dmg_type']:
            out.append('dmg=%s,%s,%s\n' % (it['dmg_type'], it['dmg_min'], it['dmg_max']))
        if it['abs_min'] != '':
            out.append('abs=%s,%s\n' % (it['abs_min'], it['abs_max']))
        if it['two_handed'] == '1':
            out.append('disable_slots=off\n')
        # extra equip flags for the skills (tools/gen_skills.py): two-handed
        # weapons, staves and wands can be required by passive skills
        kind = it['base'].split('/')[-1][:-4]
        extra = (['two_handed'] if it['two_handed'] == '1' else []) + \
                (['staff'] if kind in ('staff', 'greatstaff') else []) + (['wand'] if kind in ('wand', 'rod') else [])
        if extra:
            flags = [f for f in base.get('equip_flags', '').split(',') if f]
            out.append('equip_flags=%s\n' % ','.join(flags + [f for f in extra if f not in flags]))
        for k, v in bonuses(it['bonuses']):
            out.append('bonus=%s,%s\n' % (k, v))
        if it.get('classes'):
            out.append('requires_class=%s\n' % it['classes'].replace(';', ','))
        for k, v in bonuses(it.get('slayer', '')):
            out.append('slayer=%s,%s\n' % (k, v))
        if it['tint'] and base.get('gfx'):
            gfx = 'rd_%s_%s' % (base['gfx'], it['tint'])
            out.append('gfx=%s\n' % gfx)
            avatar_tints.add((base['gfx'], it['tint']))
        if it['band'] == 'unique':
            out.append('loot_drops_max=1\n')

    write(rel('items/categories/rd_items.txt'), ''.join(out))
    os.makedirs(rel('images/icons'), exist_ok=True)
    sheet.save(rel('images/icons/icons_rd.png'))

    # optional EK-icon mod: same file path, so enabling the mod just swaps the art
    os.makedirs(os.path.join(EK_MOD, 'images/icons'), exist_ok=True)
    ek_sheet.save(os.path.join(EK_MOD, 'images/icons/icons_rd.png'))
    write(os.path.join(EK_MOD, 'settings.txt'),
          'description=Swaps Random Dungeon item icons for the original Exiled Kingdoms wiki icons. '
          'PERSONAL USE ONLY: this art belongs to Exiled Kingdoms, do not redistribute. Generated by '
          'random_dungeon/tools/gen_content.py.\nrequires=random_dungeon\ngame=flare-game\nversion=0.1\n'
          'engine_version_min=1.13.01\n')

    # tinted equipment layers on the hero (same sprite, color filter on top)
    for gfx, tint in sorted(avatar_tints):
        for body in BODIES:
            src = 'animations/avatar/%s/%s.txt' % (body, gfx)
            if locate(src):
                write(rel('animations/avatar/%s/rd_%s_%s.txt' % (body, gfx, tint)),
                      HEADER + color_mod_lines(tint) + '\nINCLUDE %s\n' % src)

    # items.txt: the engine loads ONE items.txt (highest mod wins), so repeat the campaign's list
    camp = open(os.path.join(MODS, 'empyrean_campaign/items/items.txt'), encoding='utf8').read()
    write(rel('items/items.txt'), HEADER + '# Copy of empyrean_campaign/items/items.txt + our items at the end.\n\n'
          + camp.rstrip() + '\n\n# Random Dungeon items (ids 5000+)\n'
          'INCLUDE items/categories/rd_items.txt\n')

    # icons.txt: same deal, one file wins
    write(rel('engine/icons.txt'), HEADER +
          'icon_set=0,images/icons/icons.png\nicon_set=256,images/icons/icons_empyrean.png\n'
          'icon_set=512,images/icons/icons_crafting.png\nicon_set=1024,images/icons/icons_overlay.png\n'
          'icon_set=%d,images/icons/icons_rd.png\n' % ICON_FIRST_ID +
          'icon_set=6144,images/icons/icons_skills.png\n')   # tools/gen_skills.py

    gen_sets(items)
    print('items: %d (icons: %d from EK, %d fallback to tinted Flare art), %d tinted equipment layers'
          % (len(items), len(items) - missing_ek, missing_ek, len(avatar_tints)))
    return items


# EK-style armor sets: all pieces with the same EK group name. bonus per pieces worn.
SET_BONUSES = {
    'Leather': ('rd_leather', [(3, 'avoidance', 5), (5, 'hp', 20)]),
    'Chainmail': ('rd_chain', [(3, 'absorb_min', 1), (5, 'hp', 40)]),
    'Platemail': ('rd_plate', [(3, 'absorb_max', 2), (5, 'hp', 60)]),
    'Legion': ('rd_legion', [(2, 'poise', 10), (4, 'physical', 2), (5, 'hp', 80)]),
    "Assassin's": ('rd_assassin', [(2, 'crit', 3), (4, 'offense', 2), (5, 'avoidance', 15)]),
    'Conjurer': ('rd_conjurer', [(3, 'mp', 30), (5, 'mental', 2)]),
    'Ashen': ('rd_ashen', [(2, 'fire_resist', 10), (4, 'hp', 100)]),
    'Blessed Platemail': ('rd_blessed_plate', [(3, 'dark_resist', 15), (5, 'hp_regen', 10)]),
}


def gen_sets(items):
    camp = open(os.path.join(MODS, 'empyrean_campaign/items/sets.txt'), encoding='utf8').read()
    ids = [int(x) for x in re.findall(r'^id=(\d+)', camp, re.M)] or [0]
    next_id = max(ids) + 1
    out = [HEADER, '# Copy of empyrean_campaign/items/sets.txt + Random Dungeon sets at the end.\n\n', camp.rstrip(), '\n']
    for group, (_, bl) in SET_BONUSES.items():
        members = [it['id'] for it in items if it['base'].startswith('items/base/armor/')
                   and (it['name'].startswith(group + ' ') or (group == 'Platemail' and it['name'] == 'Knight Helm'))
                   and not (group == 'Platemail' and it['name'].startswith('Blessed'))]
        if len(members) < 2:
            continue
        out.append('\n[set]\nid=%d\nname=%s Set\nitems=%s\ncolor=255,215,120\n' % (next_id, group, ','.join(members)))
        for count, stat, val in bl:
            out.append('bonus=%d,%s,%d\n' % (count, stat, val))
        next_id += 1
    write(rel('items/sets.txt'), ''.join(out))


# ------------------------------------------------------------------ loot
def gen_loot(items):
    """
    How Flare picks loot (LootManager::checkLoot): each "drop attempt" rolls ONE
    number 0-100; every entry whose chance >= roll is eligible, and the eligible
    entry with the SMALLEST chance wins (ties: random pick). So chances behave
    like nested rarity bands:
        P(unique) = unique, P(rare) = rare - unique, ... P(nothing) = 100 - gold
    Items outside the player's level window are skipped, so the roll falls to
    the next band. Enemies get `loot_count` attempts per death.
    """
    bands = list(csv.DictReader(open(os.path.join(DATA, 'loot_bands.csv'), encoding='utf8')))
    for b in bands:
        out = [HEADER, '# grade=%s  (see tools/ek_data/loot_bands.csv)\n' % b['grade']]
        out.append('\n[loot]\nid=currency\nchance=%s\nquantity=%s\nquantity_per_level=%s\n'
                   % (b['gold'], b['gold_qty'].replace('-', ','), b['gold_qty_per_level'].replace('-', ',')))
        for pid in ('2', '3'):  # health / mana potion
            out.append('\n[loot]\nid=%s\nchance=%s\nquantity=1\n' % (pid, b['potion']))
        for it in items:
            lvl = int(it['level'])
            lo = max(1, lvl - int(b['level_below']))
            hi = lvl + int(b['level_above'])
            out.append('\n[loot]\nid=%s\nchance=%s\nquantity=1\nrequires_level=%d,%d\n'
                       % (it['id'], b[it['band']], lo, hi))
        write(rel('loot/rd_drop_%s.txt' % b['grade']), ''.join(out))
    print('loot tables: %s' % ', '.join('rd_drop_%s' % b['grade'] for b in bands))
    return {b['grade']: b for b in bands}


# ------------------------------------------------------------------ enemies
CUSTOM_TEMPLATES = {
    # ---- folclore (sprites de tools/gen_serpents.py)
    'serpent': """INCLUDE enemies/base/rd_serpent.txt
stat=hp,22
speed=5.5
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,5
stat=dmg_melee_min,5
stat=dmg_melee_max,10
cooldown=1200ms
stat_per_level=hp,12
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,15
stat_per_level=dmg_melee_max,15
""",
    'serpent_big': """INCLUDE enemies/base/rd_serpent.txt
stat=hp,90
speed=3.6
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,14
stat=dmg_melee_max,22
cooldown=1600ms
stat_per_level=hp,40
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,18
stat_per_level=dmg_melee_max,18
stat=absorb_min,3
stat=absorb_max,6
melee_range=1.5
""",
    # Minhocão: lento, golpe enorme que alcança longe
    'serpent_burrow': """INCLUDE enemies/base/rd_serpent.txt
stat=hp,260
speed=3.0
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,25
stat=dmg_melee_max,40
cooldown=2000ms
stat_per_level=hp,110
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,25
stat_per_level=dmg_melee_max,25
stat=absorb_min,6
stat=absorb_max,12
melee_range=3.0
threat_range=12.0
""",
    # Boitatá: cospe fogo (173 = bola de fogo do wyvern)
    'serpent_fire': """INCLUDE enemies/base/rd_serpent.txt
stat=hp,220
speed=4.5
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,18
stat=dmg_melee_max,28
cooldown=1600ms
stat_per_level=hp,100
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,22
stat_per_level=dmg_melee_max,22
power=ranged,173,45
stat=dmg_ment_min,30
stat=dmg_ment_max,40
stat_per_level=dmg_ment_min,20
stat_per_level=dmg_ment_max,20
chance_pursue=5
melee_range=2.0
threat_range=12.0
""",
    # Cobra Grande: chefe final, muito vida e alcance
    'serpent_giant': """INCLUDE enemies/base/rd_serpent.txt
stat=hp,380
speed=3.4
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,30
stat=dmg_melee_max,45
cooldown=2000ms
stat_per_level=hp,150
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,28
stat_per_level=dmg_melee_max,28
stat=absorb_min,8
stat=absorb_max,15
melee_range=3.2
threat_range=12.0
""",
    # Mula sem Cabeça: rápida, coice pesado e labaredas
    'mula': """INCLUDE enemies/base/rd_mula.txt
stat=hp,240
speed=6.5
turn_delay=200ms
power=melee,164,10
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,22
stat=dmg_melee_max,34
cooldown=1500ms
stat_per_level=hp,105
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,24
stat_per_level=dmg_melee_max,24
power=ranged,173,20
stat=dmg_ment_min,25
stat=dmg_ment_max,35
stat_per_level=dmg_ment_min,20
stat_per_level=dmg_ment_max,20
stat=absorb_min,4
stat=absorb_max,10
""",
    'minotaur': """INCLUDE enemies/base/minotaur.txt
stat=hp,80
speed=4
turn_delay=300ms
power=melee,164,5
power=ranged,192,3
stat=accuracy,80
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,20
stat=dmg_melee_max,30
stat=dmg_ranged_min,15
stat=dmg_ranged_max,25
stat=absorb_min,4
stat=absorb_max,8
cooldown=1800ms
stat_per_level=hp,35
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,15
stat_per_level=dmg_melee_max,15
stat_per_level=dmg_ranged_min,15
stat_per_level=dmg_ranged_max,15
stat_per_level=absorb_min,1
stat_per_level=absorb_max,1
""",
    # Oracle: ranged caster + party buff. No summons (193): summoned creatures
    # aren't network-synced yet (see README, "Limitacao conhecida").
    'minotaur_caster': """INCLUDE enemies/base/minotaur.txt
stat=hp,70
speed=3.4
turn_delay=300ms
power=melee,164,3
power=ranged,192,10
power=ranged,195,2
power=on_join_combat,197,100
stat=accuracy,85
stat=avoidance,10
stat=poise,30
stat=dmg_melee_min,15
stat=dmg_melee_max,20
stat=dmg_ranged_min,20
stat=dmg_ranged_max,30
stat=dmg_ment_min,20
stat=dmg_ment_max,30
stat=absorb_min,4
stat=absorb_max,8
cooldown=2000ms
chance_pursue=2
chance_flee=20
flee_duration=3s
flee_cooldown=1s
flee_range=6
stat_per_level=hp,30
stat_per_level=accuracy,5
stat_per_level=avoidance,5
stat_per_level=poise,3
stat_per_level=dmg_melee_min,15
stat_per_level=dmg_melee_max,15
stat_per_level=dmg_ranged_min,15
stat_per_level=dmg_ranged_max,15
stat_per_level=dmg_ment_min,15
stat_per_level=dmg_ment_max,15
""",
}
DROP_KEYS = ('name', 'level', 'categories', 'rarity', 'xp', 'xp_scaling', 'loot', 'loot_count', 'animations')
TIERS = [(3, 'rd_t1'), (6, 'rd_t2'), (9, 'rd_t3'), (12, 'rd_t4'), (15, 'rd_t5'), (99, 'rd_t6')]


def template_lines(name):
    if name in CUSTOM_TEMPLATES:
        return CUSTOM_TEMPLATES[name].splitlines()
    return open(os.path.join(MODS, 'empyrean_campaign/enemies/%s.txt' % name), encoding='utf8').read().splitlines()


def scale_line(line, hp_mult, dmg_mult):
    m = re.match(r'(stat|stat_per_level)=(hp|dmg_\w+),(\d+)$', line.strip())
    if not m:
        return line
    mult = hp_mult if m.group(2) == 'hp' else dmg_mult
    return '%s=%s,%d' % (m.group(1), m.group(2), max(1, int(round(int(m.group(3)) * mult))))


FAMILY_TYPE = {'Caveiras': 'undead', 'Dead': 'undead', 'Visagens': 'undead', 'Devils': 'demon',
               'Sacis': 'greenskin', 'Quibungos': 'greenskin', 'Caiporas': 'greenskin',
               'Tanajuras': 'beast', 'Spiders': 'beast', 'Caimans': 'beast', 'Lobisomens': 'beast', 'Snakes': 'beast'}
# damage-type names shown in item tooltips ("+25% damage vs Undead")
EXTRA_PT_SLAYER = [('+%d%% damage vs %s', '+%d%% de dano contra %s'), ('Undead', 'Mortos-vivos'), ('Demon', 'Demônios'),
                   ('Greenskin', 'Peles-verdes'), ('Beast', 'Feras')]
REGIONS = list(csv.DictReader(open(os.path.join(TOOLS, 'world/regions.csv'), encoding='utf8')))
REGION_BY_ID = {r['id']: r for r in REGIONS}
ZONES = list(csv.DictReader(open(os.path.join(TOOLS, 'world/zones.csv'), encoding='utf8')))


def gen_enemies(loot_grades):
    enemies = list(csv.DictReader(open(os.path.join(DATA, 'enemies.csv'), encoding='utf8')))
    in_il_common = 0
    for e in enemies:
        hp_mult, dmg_mult = float(e['hp_mult']), float(e['dmg_mult'])
        lvl = int(e['ek_level'])
        grade = e['grade']
        tier = next(t for cap, t in TIERS if lvl <= cap)
        family = 'rd_' + re.sub(r'\W+', '_', e['family'].lower()).strip('_')
        cats = [e['id'], tier, family, 'rd_all']
        # creature type, for item slayer bonuses (silver vs undead...). 'undead' is
        # also the campaign's own category for its skeletons and zombies.
        if FAMILY_TYPE.get(e['family']):
            cats.append(FAMILY_TYPE[e['family']])
        # open-world regions this enemy belongs to (tools/world/regions.csv): the
        # region's dungeons spawn from rd_reg_<region> / rd_regelite_<region>
        for reg in REGIONS:
            if e['id'] in reg['enemies'].split(';'):
                cats.append(('rd_regelite_' if grade == 'elite' else 'rd_reg_') + reg['id'])
        # per-zone dungeon category: region enemies within the zone's level band
        # (same rule as gen_world.zone_enemies, EK_BAND there)
        for zn in ZONES:
            if zn['dungeon'] and grade == 'normal' and e['id'] in REGION_BY_ID[zn['region']]['enemies'].split(';') \
                    and int(zn['level_min']) - 3 <= lvl <= int(zn['level_max']) + 2:
                cats.append('rd_dg_' + zn['id'])
        if grade == 'boss':
            cats.append('rd_boss')
        else:
            cats += ['rd_' + grade, 'il_common']   # il_common: also shows up in the procedural dungeon
            in_il_common += 1
        strength = (hp_mult + dmg_mult) / 2
        rarity = 'rare' if grade == 'boss' else ('uncommon' if grade == 'elite' or strength >= 1.35 else 'common')

        body = []
        for line in template_lines(e['template']):
            key = line.split('=', 1)[0].strip()
            if key in DROP_KEYS or key.startswith('#') or not line.strip():
                continue
            if key.endswith('_resist'):
                continue
            body.append(scale_line(line, hp_mult, dmg_mult))

        mod, anim = e['animation'].split(':')
        anim_path = 'animations/enemies/%s.txt' % anim
        if e['tint']:
            tinted_path = 'animations/enemies/rd/%s.txt' % e['id']
            write(rel(tinted_path), HEADER + color_mod_lines(e['tint']) + '\nINCLUDE %s\n' % anim_path)
            anim_path = tinted_path

        b = loot_grades.get(grade, loot_grades['normal'])
        out = [HEADER, '# %s (level %d, family %s)\n' % (e['name'], lvl, e['family'])]
        out.append('\n'.join(body) + '\n\n')
        out.append('name=%s\nlevel=1\ncategories=%s\nrarity=%s\n' % (e['name'], ','.join(cats), rarity))
        out.append('xp=%d\nxp_scaling=enemies/xp_scaling/il.txt\n' % max(1, round(2 * strength * XP_BASE)))
        out.append('animations=%s\n' % anim_path)
        for part in (e['resists'] or '').split(';'):
            if part:
                k, v = part.split(':')
                out.append('stat=%s,%s\n' % (k, v))
        # holy damage (tools/gen_skills.py): undead and demons are weak to it
        if FAMILY_TYPE.get(e['family']) in ('undead', 'demon'):
            out.append('stat=holy_resist,-50\n')
        if grade == 'boss' or any(r['boss'] == e['id'] for r in REGIONS):
            # world bosses stay dead until the hero visits a town (see gen_world.py)
            out.append('defeat_status=rd_boss_down_%s\n' % e['id'])
        out.append('loot=loot/rd_drop_%s.txt\nloot_count=%s,%s\n' % (grade if grade in loot_grades else 'normal',
                                                                     b['drops_min'], b['drops_max']))
        write(rel('enemies/%s.txt' % e['id']), ''.join(out))
    print('enemies: %d (%d also added to il_common for the procedural dungeon)' % (len(enemies), in_il_common))
    return enemies


# ------------------------------------------------------------------ translations
# strings that aren't in the CSVs (engine/classes.txt, powers/*.txt)
EXTRA_PT = [
    ('Warrior', 'Guerreiro'), ('Rogue', 'Ladino'), ('Cleric', 'Clérigo'), ('Mage', 'Mago'),
    ('Warriors rely on physical strength, heavy armor and big weapons. Primary attribute: Physical',
     'Guerreiros confiam na força física, armaduras pesadas e armas grandes. Atributo principal: Físico'),
    ('Rogues strike fast and silent with daggers, and shoot from afar with bows. Primary attribute: Offense',
     'Ladinos golpeiam rápido e em silêncio com adagas, e atiram de longe com arcos. Atributo principal: Ataque'),
    ('Clerics fight with mace and shield and heal themselves with holy magic. Primary attributes: Mental and Physical',
     'Clérigos lutam com maça e escudo e se curam com magia sagrada. Atributos principais: Mental e Físico'),
    ('Mages cast powerful spells from a distance. Primary attribute: Mental',
     'Magos lançam feitiços poderosos à distância. Atributo principal: Mental'),
    ('Holy Strike', 'Golpe Sagrado'), ('A blessed blow with your weapon.', 'Um golpe abençoado com sua arma.'),
    ('Heal', 'Cura'), ('Restore 20% of maximum HP.', 'Restaura 20% do HP máximo.'),
    ('Dev Kit', 'Ferramentas'), ('Monsters', 'Monstros'), ('Items', 'Itens'), ('Class', 'Classe'), ('Hero', 'Herói'),
    ('Spawn 1', 'Spawnar 1'), ('Spawn 5', 'Spawnar 5'), ('Training Dummy', 'Boneco de Treino'), ('Kill All', 'Matar Todos'),
    ('Reset Meter', 'Zerar Medidor'), ('Take 1', 'Pegar 1'), ('Take 10', 'Pegar 10'), ('+1000 Gold', '+1000 Ouro'),
    ('+10 Potions', '+10 Poções'), ('Switch Class', 'Trocar Classe'), ('+1 Level', '+1 Nível'), ('+5 Levels', '+5 Níveis'),
    ('Full Heal', 'Curar Tudo'), ('Spawn level', 'Nível do spawn'), ('Dummies', 'Bonecos'), ('Total damage', 'Dano total'),
    ('DPS (last 5s)', 'DPS (últimos 5s)'), ('Biggest hit', 'Maior golpe'), ('Current class', 'Classe atual'),
    ('Infinite points', 'Pontos infinitos'), ('God mode', 'Modo deus'),
    ('Wave', 'Onda'), ('kills', 'abates'), ('New record!', 'Novo recorde!'), ('Best', 'Recorde'), ('Run over', 'Fim da horda'),
    ('Only the host can lead the party to another area.', 'Só o anfitrião pode levar o grupo para outra área.'),
    ('Following the host to another area.', 'Seguindo o anfitrião para outra área.'),
    ('Open World', 'Mundo Aberto'), ('Infinite Run', 'Horda Infinita'), ('Test Room', 'Treinamento'),
    ('Skin', 'Pele'), ('Hair', 'Cabelo'), ('Clothes', 'Roupa'), ('Original', 'Original'),
    ('Play', 'Jogar'),
    ('You fell! Stay close to an ally to be revived.', 'Você caiu! Fique perto de um aliado para ser revivido.'),
    ('Reviving...', 'Revivendo...'),
    ('Sanctuary', 'Santuário'), ('Souls: %d', 'Almas: %d'), ('Buy (%d)', 'Comprar (%d)'), ('Close', 'Fechar'),
    ('+%d souls (%d)', '+%d almas (%d)'), ('Second chance! You rise again.', 'Segunda chance! Você se levanta de novo.'),
    ('Vigor', 'Vigor'), ('+4% max health', '+4% de vida máxima'),
    ('Might', 'Poder'), ('+3% damage', '+3% de dano'),
    ('Swiftness', 'Ligeireza'), ('+2% move and attack speed', '+2% de velocidade e ataque'),
    ('Precision', 'Precisão'), ('+1% critical chance', '+1% de chance de crítico'),
    ('Guard', 'Guarda'), ('+1 absorb', '+1 de absorção'),
    ('Fortune', 'Fortuna'), ('+10% gold, +5% item find', '+10% de ouro, +5% de itens'),
    ('Wisdom', 'Sabedoria'), ('+8% experience', '+8% de experiência'),
    ('Second Chance', 'Segunda Chance'), ('Rise again once per run', 'Levanta de novo 1x por horda'),
    ('Wave %d', 'Onda %d'), ('Swarm!', 'Enxame!'), ('Ambush!', 'Emboscada!'), ('Elite hunters!', 'Caçadores de elite!'),
    ('Boss!', 'Chefe!'), ('Caveiras', 'Caveiras'), ('Dead', 'Defuntos'), ('Visagens', 'Visagens'), ('Sacis', 'Sacis'),
    ('Quibungos', 'Quibungos'), ('Lobisomens', 'Lobisomens'), ('Devils', 'Capetas'), ('Spiders', 'Aranhas'), ('Tanajuras', 'Tanajuras'),
    ('Caiporas', 'Caiporas'), ('Snakes', 'Cobras'), ('Caimans', 'Jacarés'), ('An ally', 'Um aliado'), ('%s: %s on you', '%s: %s em você'), ('An ally brought you back!', 'Um aliado trouxe você de volta!'),
    ('Credits', 'Créditos'),
    ('Level up! Choose an upgrade', 'Subiu de nível! Escolha uma melhoria'), ('Choose', 'Escolher'), ('Rank %d / %d', 'Nível %d / %d'),
    ('Sharp Blade', 'Lâmina Afiada'), ('+10% damage', '+10% de dano'),
    ('Stone Heart', 'Coração de Pedra'), ('+12% maximum HP', '+12% de vida máxima'),
    ('Swift Boots', 'Botas Ligeiras'), ('+8% movement speed', '+8% de velocidade'),
    ('Frenzy', 'Frenesi'), ('+10% attack speed', '+10% de velocidade de ataque'),
    ("Executioner's Eye", 'Olho do Carrasco'), ('+4% critical chance', '+4% de chance de crítico'),
    ('Iron Skin', 'Pele de Ferro'), ('+2 absorb', '+2 de absorção'),
    ('Bloodthirst', 'Sede de Sangue'), ('+2% life steal', '+2% de roubo de vida'),
    ('Scholar', 'Estudioso'), ('+15% XP gained', '+15% de XP ganho'),
    ('The host closed the game. You are now playing alone.', 'O anfitrião fechou o jogo. Agora você está jogando sozinho.'),
    ('Connection to the host was lost. You are now playing alone.', 'A conexão com o anfitrião caiu. Agora você está jogando sozinho.'),
    ('Play with friends', 'Jogar com amigos'), ('Close to friends', 'Fechar para amigos'), ('Solo game', 'Partida solo'),
    ("In a friend's game", 'Na partida de um amigo'), ('Room code: %s', 'Código da sala: %s'), ('Room: %s', 'Sala: %s'),
    ('Online room unavailable (LAN only)', 'Sala online indisponível (só rede local)'), ('Opening room...', 'Abrindo sala...'),
    ('Open on LAN', 'Aberta na rede local'), ('Your game is solo again.', 'Sua partida voltou a ser solo.'),
    ('Could not open the game to friends.', 'Não foi possível abrir a partida para amigos.'),
    ('Room open! Friends join with the code %s', 'Sala aberta! Seus amigos entram com o código %s'),
    ('LAN: %s', 'Rede local: %s'),
    ('Open on the local network: friends use Search, or type %s', 'Aberta na rede local: os amigos usam Buscar na rede, ou digitam %s'),
    ('Dagger Strike', 'Golpe de Adaga'), ('A quick stab with your dagger.', 'Uma estocada rápida com sua adaga.'),
]


def po_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def gen_po(items, enemies):
    pairs = [(it['name'], it['name_pt']) for it in items if it['name_pt']]
    pairs += [(e['name'], e['name_pt']) for e in enemies if e['name_pt']]
    pairs += [('%s Set' % g, 'Conjunto %s' % g) for g in SET_BONUSES]
    pairs += EXTRA_PT + EXTRA_PT_SLAYER
    import gen_skills
    pairs += gen_skills.translations()
    seen, body = set(), []
    for en, pt in pairs:
        if en in seen:
            continue
        seen.add(en)
        body.append('msgid "%s"\nmsgstr "%s"\n' % (po_escape(en), po_escape(pt)))
    head = ('# GENERATED by tools/gen_content.py -- edit name_pt in tools/ek_data/*.csv\n'
            'msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n"Language: %s\\n"\n\n')
    for lang in ('pt_BR', 'pt'):
        write(rel('languages/data.%s.po' % lang), head % lang + '\n'.join(body))
    print('translations: %d names (pt_BR, pt)' % len(seen))


def main():
    offline = '--offline' in sys.argv
    items = gen_items(offline)
    grades = gen_loot(items)
    enemies = gen_enemies(grades)
    gen_po(items, enemies)


if __name__ == '__main__':
    main()
