#!/usr/bin/env python3
"""
Random Dungeon skills: the Exiled Kingdoms skill system with our own names.

  python3 tools/gen_skills.py

Reads tools/ek_data/skills.csv (names, tab, classes, ranks, point cost per
rank, requirements) and the mechanics table below (SPEC: what every rank
does), and writes:

  powers/skills.txt              one power per skill rank (ids 6000+)
  powers/effects.txt             APPENDed effects (Duelist stacks)
  engine/damage_types.txt        APPENDed poison and holy damage
  powers/trees/rd_<class>.txt    the skills sheet of each class: tabs
                                 Class / General / Advanced (EK layout)
  enemies/rd_summon_*.txt        allies the summoning skills call
  images/icons/icons_skills.png  skill icons (tinted Flare icons, 6144+)

Translations (names and every rank's description) are returned by
translations() and written by gen_content.py into languages/data.pt*.po.

EK -> Random Dungeon scale: flat damage x2, mana x3, armor ~ absorb / 2,
healing x4, traits -> primary stats (see ek_data/make_skills_csv.py).
Things that don't exist in a run (towns, rumours, traps to disarm, days)
became co-op friendly equivalents (see the notes in SPEC).
"""
import csv, os, sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(TOOLS)
MODS = os.path.dirname(MOD)
HEADER = '# GENERATED by tools/gen_skills.py from tools/ek_data/skills.csv -- edit those, not this file.\n'

ID_BASE = 6000          # power id = ID_BASE + index * 5 + rank
ICON_BASE = 6144        # icons_skills.png icon_set offset
BASIC_ATTACKS = (1, 7, 42, 5000, 5001, 116, 122)   # engine/classes.txt actionbars
CLASSES = ['warrior', 'rogue', 'cleric', 'mage']
TABS = [('class', 'Class'), ('general', 'General'), ('advanced', 'Advanced')]


def rel(*p):
    return os.path.join(MOD, *p)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf8') as f:
        f.write(text)


def load_skills():
    rows = list(csv.DictReader(open(os.path.join(TOOLS, 'ek_data', 'skills.csv'), encoding='utf8')))
    for i, r in enumerate(rows):
        r['index'] = i
        r['ranks'] = int(r['ranks'])
        r['costs'] = [int(c) for c in r['cost'].split('/')]
    return rows


def pid(skill, rank):
    return ID_BASE + skill['index'] * 5 + rank


# ------------------------------------------------------------------ building blocks
# Every SPEC entry is fn(r) -> Rank, r = 0-based rank.

class Rank:
    def __init__(self, lines, en, pt):
        self.lines, self.en, self.pt = lines, en, pt


PAIRS = {'absorb': ('absorb_min', 'absorb_max')}


def expand(stat):
    if stat in PAIRS:
        return PAIRS[stat]
    if stat.startswith('dmg_') and not stat.endswith(('_min', '_max')):
        return (stat + '_min', stat + '_max')
    return (stat,)


def effects(pairs, dur='0', key='post_effect'):
    out = []
    for stat, mag in pairs:
        for s in expand(stat):
            out.append('%s=%s,%s,%s' % (key, s, mag, dur))
    return out


def passive(pairs, en, pt, extra=()):
    return Rank(['type=fixed', 'passive=true'] + effects(pairs) + list(extra), en, pt)


def triggered(trigger, pairs, dur, en, pt, cooldown=None, extra=()):
    lines = ['type=fixed', 'passive=true', 'passive_trigger=%s' % trigger, 'buff=true']
    lines += effects(pairs, dur)
    if cooldown:
        lines.append('cooldown=%s' % cooldown)
    return Rank(lines + list(extra), en, pt)


def buff(pairs, dur, en, pt, cooldown=None, mp=0, sound='soundfx/powers/shield.ogg', extra=()):
    lines = ['type=fixed', 'new_state=cast', 'buff=true', 'soundfx=%s' % sound]
    lines += effects(pairs, dur)
    if cooldown:
        lines.append('cooldown=%s' % cooldown)
    if mp:
        lines.append('requires_mp=%d' % mp)
    return Rank(lines + list(extra), en, pt)


def strike(mult, en, pt, cooldown=None, mp=0, radius=1.0, multitarget=False, post=(), charge=None,
           anim=None, source=False, state='swing', sound='soundfx/melee_attack.ogg', base='melee', flags=()):
    lines = ['type=fixed', 'new_state=%s' % state, 'face=true', 'use_hazard=true', 'base_damage=%s' % base,
             'lifespan=%s' % ('300ms' if charge else '120ms'), 'radius=%s' % radius,
             'starting_pos=%s' % ('source' if source else 'melee'), 'aim_assist=true',
             'modifier_damage=multiply,%d,0' % mult, 'soundfx=%s' % sound, 'can_trigger_passives=true']
    if multitarget:
        lines.append('multitarget=true')
    if charge:
        lines += ['charge_speed=%s' % charge, 'relative_pos=true', 'state_duration=300ms']
    if anim:
        lines += ['animation=%s' % anim, 'directional=false' if source else 'directional=true']
    if cooldown:
        lines.append('cooldown=%s' % cooldown)
    if mp:
        lines.append('requires_mp=%d' % mp)
    if flags:
        lines.append('requires_flags=%s' % ','.join(flags))
    lines += ['post_effect=%s' % p for p in post]
    return Rank(lines, en, pt)


def spell(element, dmin, dmax, en, pt, cooldown, mp, kind='missile', anim=None, radius=1.0, post=(),
          sound='soundfx/powers/fireball.ogg', multitarget=False, speed=16):
    lines = ['new_state=cast', 'face=true', 'use_hazard=true', 'aim_assist=true', 'base_damage=ment',
             'modifier_damage=absolute,%d,%d' % (dmin, dmax), 'radius=%s' % radius, 'soundfx=%s' % sound,
             'cooldown=%s' % cooldown, 'requires_mp=%d' % mp]
    if element:
        lines.append('trait_elemental=%s' % element)
    if kind == 'missile':
        lines += ['type=missile', 'directional=true', 'lifespan=900ms', 'speed=%s' % speed,
                  'animation=%s' % (anim or 'animations/powers/fireball.txt')]
    elif kind == 'target':      # lands where you aim (storms, clouds)
        lines += ['type=fixed', 'starting_pos=target', 'target_range=7', 'lifespan=600ms', 'multitarget=true',
                  'animation=%s' % (anim or 'animations/powers/freeze.txt')]
    elif kind == 'nova':        # around the caster
        lines += ['type=fixed', 'starting_pos=source', 'lifespan=300ms', 'multitarget=true',
                  'animation=%s' % (anim or 'animations/powers/blast.txt')]
    if multitarget and kind == 'missile':
        lines.append('multitarget=true')
    lines += ['post_effect=%s' % p for p in post]
    return Rank(lines, en, pt)


def summon(category, level_mult, en, pt, cooldown, mp, count=1):
    return Rank(['type=spawn', 'new_state=cast', 'soundfx=soundfx/powers/teleport.ogg', 'spawn_type=%s' % category,
                 'spawn_level=hero_level,%s,1' % level_mult, 'starting_pos=source', 'target_neighbor=1',
                 'use_hazard=true', 'no_attack=true', 'count=%d' % count, 'spawn_limit=fixed,%d' % count,
                 'cooldown=%s' % cooldown, 'requires_mp=%d' % mp], en, pt)


def pick(r, *vals):
    return vals[min(r, len(vals) - 1)]


def pct(v):
    return '%d%%' % (100 + v)


WARDS = {  # skill id: resist, EK values, EN element, PT element
    'grave_ward': ('dark_resist', (12, 24, 36), 'shadow', 'sombra'),
    'ember_ward': ('fire_resist', (12, 24, 36), 'fire', 'fogo'),
    'frost_ward': ('ice_resist', (12, 24, 36), 'ice', 'gelo'),
    'storm_ward': ('lightning_resist', (12, 24, 36), 'lightning', 'raio'),
    'venom_ward': ('poison_resist', (12, 24, 36), 'poison', 'veneno'),
    'soul_ward': ('holy_resist', (10, 20, 30), 'holy', 'sagrado'),
}

# ------------------------------------------------------------------ the skills
# icon: (Flare icon index from images/icons/icons.png, tint)
ICON = {}
SPEC = {}


def skill(sid, icon, tint=None):
    def deco(fn):
        SPEC[sid] = fn
        ICON[sid] = (icon, tint)
        return fn
    return deco


# ---- Warrior
@skill('shield_slam', 4)
def _(r):
    stun, push = (1, 2, 3)[r], (10, 15, 20)[r]
    return strike(100, 'Slam into the enemy: knocks it back and stuns it for %ds.' % stun,
                  'Golpeia o inimigo: empurra e atordoa por %ds.' % stun, cooldown='%ds' % (16, 14, 12)[r],
                  post=('paralyze,0,%ds' % stun, 'force,%d,100ms' % push), state='block',
                  sound='soundfx/powers/block.ogg')


@skill('bull_rush', 13)
def _(r):
    b = (60, 90, 125, 160)[r]
    return strike(100 + b, 'Charge forward and hit for +%d%% damage, briefly stunning.' % b,
                  'Avança e golpeia com +%d%% de dano, atordoando por um instante.' % b,
                  cooldown='%ds' % (12, 11, 10, 9)[r], charge=14, post=('paralyze,0,600ms',),
                  sound='soundfx/powers/shock.ogg')


@skill('wide_swing', 1)
def _(r):
    n, p = r + 1, (50, 60, 75)[r]
    # EK: your attacks also hit extra enemies. Here: every attack skill you
    # use sweeps the enemies around the target for a share of the damage.
    return Rank(['type=fixed', 'passive=true', 'passive_trigger=on_active_power', 'use_hazard=true',
                 'base_damage=melee', 'multitarget=true', 'starting_pos=melee', 'radius=%s' % (1.5, 1.8, 2.1)[r],
                 'lifespan=120ms', 'modifier_damage=multiply,%d,0' % p, 'cooldown=400ms'],
                'Your attacks also sweep up to %d nearby enemies for %d%% damage.' % (n, p),
                'Seus ataques também atingem até %d inimigos próximos com %d%% do dano.' % (n, p))


@skill('berserk_blood', 25)
def _(r):
    b = (30, 50, 65)[r]
    return triggered('on_halfdeath', [('dmg_melee', pct(b)), ('dmg_ranged', pct(b))], '8s',
                     'Below half health, deal +%d%% damage for 8s.' % b,
                     'Com menos da metade da vida, causa +%d%% de dano por 8s.' % b, cooldown='20s')


@skill('iron_will', 31)
def _(r):
    a, d = (3, 5, 7)[r], (6, 8, 10)[r]
    return buff([('absorb', a), ('poise', 20)], '%ds' % d, 'Gain +%d absorb and resist staggering for %ds.' % (a, d),
                'Ganha +%d de absorção e resiste a atordoamentos por %ds.' % (a, d), cooldown='35s',
                sound='soundfx/powers/warcry.ogg')


@skill('bulwark', 4, (255, 210, 120))
def _(r):
    a = r + 1
    return passive([('absorb', a), ('avoidance', 3 * (r + 1))],
                   'With a shield: +%d absorb and +%d avoidance.' % (a, 3 * (r + 1)),
                   'Com escudo: +%d de absorção e +%d de esquiva.' % (a, 3 * (r + 1)),
                   extra=['requires_flags=shield'])


@skill('heavy_arms', 44)
def _(r):
    b, s = (15, 30, 50)[r], (5, 5, 10)[r]
    return passive([('dmg_melee', pct(b)), ('poise', s)],
                   'With a two-handed weapon: +%d%% melee damage.' % b,
                   'Com arma de duas mãos: +%d%% de dano corpo a corpo.' % b, extra=['requires_flags=two_handed'])


@skill('blade_storm', 32)
def _(r):
    b, st = (50, 75, 100, 120)[r], (0, 3, 5, 7)[r]
    post = ('paralyze,0,1s,%d' % st,) if st else ()
    en = 'Spin and hit everyone around you for +%d%% damage' % b + (' (%d%% stun chance).' % st if st else '.')
    pt = 'Gira e atinge todos ao redor com +%d%% de dano' % b + (' (%d%% de chance de atordoar).' % st if st else '.')
    return strike(100 + b, en, pt, cooldown='%ds' % (12, 11, 10, 9)[r], radius=2.2, multitarget=True, source=True,
                  anim='animations/powers/quake.txt', post=post, sound='soundfx/powers/quake.ogg')


# ---- Rogue
@skill('keen_arrows', 3)
def _(r):
    d = (2, 4, 6)[r]
    return passive([('dmg_ranged', d), ('accuracy', 3 * (r + 1))], 'Arrows deal +%d damage and hit more often.' % d,
                   'Flechas causam +%d de dano e acertam mais.' % d)


@skill('slip_away', 36)
def _(r):
    e = (50, 70, 90)[r]
    return buff([('avoidance', e)], '5s', 'Dodge most attacks: +%d avoidance for 5s.' % e,
                'Esquiva da maioria dos ataques: +%d de esquiva por 5s.' % e, cooldown='%ds' % (30, 25, 20)[r],
                sound='soundfx/powers/teleport.ogg')


@skill('heel_strike', 31, (200, 160, 120))
def _(r):
    s = (3, 4, 5)[r]
    return strike(60, 'Kick the enemy away and slow it for %ds.' % s, 'Chuta o inimigo para longe e o deixa lento por %ds.' % s,
                  cooldown='%ds' % (9, 8, 7)[r], post=('force,%d,100ms' % (10, 15, 20)[r], 'slow,50,%ds' % s))


@skill('backstab', 5)
def _(r):
    c = (6, 10, 15)[r]
    return passive([('crit', c)], 'Strike weak spots: +%d%% critical chance.' % c,
                   'Ataca pontos fracos: +%d%% de chance de crítico.' % c)


@skill('dash', 9)
def _(r):
    d = (4, 5, 6)[r]
    return buff([('speed', 160)], '%ds' % d, 'Sprint at +60%% speed for %ds.' % d, 'Corre com +60%% de velocidade por %ds.' % d,
                cooldown='%ds' % (30, 25, 20)[r], sound='soundfx/powers/heal.ogg')


@skill('gut_strike', 33)
def _(r):
    b = (100, 150, 200, 250)[r]
    return strike(100 + b, 'A precise stab for +%d%% damage.' % b, 'Uma estocada precisa com +%d%% de dano.' % b,
                  cooldown='%ds' % (14, 12, 10, 9)[r], post=('bleeding,%d,4s' % (3, 5, 7, 9)[r],))


@skill('fade', 29)
def _(r):
    d = (8, 10, 12)[r]
    return buff([('stealth', (50, 65, 80)[r]), ('speed', 115)], '%ds' % d,
                'Vanish into the shadows for %ds: enemies notice you much later.' % d,
                'Some nas sombras por %ds: os inimigos demoram muito mais a notar você.' % d, cooldown='25s',
                sound='soundfx/powers/teleport.ogg')


@skill('snare_craft', 43)
def _(r):
    d = (15, 20, 30)[r]
    return Rank(['type=fixed', 'new_state=cast', 'face=true', 'directional=true', 'starting_pos=melee',
                 'animation=animations/powers/bear_trap.txt', 'use_hazard=true', 'base_damage=melee',
                 'modifier_damage=multiply,%d,0' % (80, 110, 150)[r], 'lifespan=%ds' % d, 'radius=1.0',
                 'post_effect=slow,0,%ds' % (2, 3, 4)[r], 'cooldown=15s', 'floor=true'],
                'Set a trap that lasts %ds, hurts and holds the first enemy in place.' % d,
                'Arma uma armadilha que dura %ds, fere e prende o primeiro inimigo.' % d)


# ---- Cleric
@skill('zealots_might', 45)
def _(r):
    d, t = (6, 10, 16)[r], (12, 14, 16)[r]
    return buff([('dmg_melee', d), ('dmg_fire', 8)], '%ds' % t, '+%d damage and +8 fire damage for %ds.' % (d, t),
                '+%d de dano e +8 de dano de fogo por %ds.' % (d, t), cooldown='20s', mp=(2, 4, 7)[r] * 3,
                sound='soundfx/powers/warcry.ogg')


@skill('templar', 15)
def _(r):
    h = (2, 4, 6)[r]
    return passive([('dmg_holy', h)], 'Your attacks burn with +%d holy damage (undead take more).' % h,
                   'Seus ataques queimam com +%d de dano sagrado (mortos-vivos sofrem mais).' % h)


@skill('mend_flesh', 11)
def _(r):
    h = (30, 75, 125)[r] * 4
    return Rank(['type=fixed', 'new_state=cast', 'buff=true', 'soundfx=soundfx/powers/heal.ogg',
                 'base_damage=ment', 'modifier_damage=absolute,%d,%d' % (h, h), 'post_effect=hp_heal,0,0',
                 'post_effect=heal_animation,0,0', 'cooldown=%ds' % (10, 8, 5)[r], 'requires_mp=%d' % ((6, 12, 18)[r] * 3),
                 'share_radius=6'],
                'Heal %d HP, you and allies nearby.' % h, 'Cura %d de vida em você e nos aliados próximos.' % h)


@skill('hallowed_aegis', 4, (255, 255, 230))
def _(r):
    a, d = (2, 3, 4, 5)[r], (25, 40, 60, 80)[r]
    return buff([('absorb', a), ('dark_resist', d)], '12s', '+%d absorb and +%d%% shadow resistance for 12s.' % (a, d),
                '+%d de absorção e +%d%% de resistência a sombra por 12s.' % (a, d), cooldown='15s',
                mp=(5, 5, 6, 6)[r] * 3)


@skill('last_rite', 10)
def _(r):
    h = (15, 25, 40)[r]
    return triggered('on_halfdeath', [('hp_restore', h)], '1s',
                     'When your health falls below half, recover %d%% of it (once per minute).' % h,
                     'Quando a vida cai abaixo da metade, recupera %d%% dela (uma vez por minuto).' % h, cooldown='60s')


@skill('warding_faith', 21)
def _(r):
    a = (1, 2, 3)[r]
    return passive([('absorb', a), ('dark_resist', 5 * (r + 1))], '+%d absorb, +%d%% shadow resistance.' % (a, 5 * (r + 1)),
                   '+%d de absorção, +%d%% de resistência a sombra.' % (a, 5 * (r + 1)))


@skill('cleansing_flame', 37, (255, 240, 170))
def _(r):
    d = (12, 24, 48)[r] * 2
    return spell('holy', d, d + d // 3, 'Holy flames hit for %d-%d holy damage (undead take more).' % (d, d + d // 3),
                 'Chamas sagradas causam %d-%d de dano sagrado (mortos-vivos sofrem mais).' % (d, d + d // 3),
                 cooldown='%ds' % (8, 6, 3)[r], mp=(3, 6, 9)[r] * 3, kind='target', radius=1.2,
                 anim='animations/powers/runes_orange.txt', sound='soundfx/powers/burn.ogg')


@skill('seers_sight', 6)
def _(r):
    f = (15, 30)[r]
    # EK: detects hidden items. Here: more and better loot for you.
    return passive([('item_find', f)], '+%d%% item find.' % f, '+%d%% de chance de encontrar itens.' % f)


# ---- Mage
@skill('ember_orb', 18)
def _(r):
    lo, hi = [(9, 18), (15, 30), (28, 56), (42, 84)][r]
    return spell('fire', lo * 2, hi * 2, 'Hurl a ball of fire: %d-%d fire damage.' % (lo * 2, hi * 2),
                 'Arremessa uma bola de fogo: %d-%d de dano de fogo.' % (lo * 2, hi * 2), cooldown='5s',
                 mp=(4, 8, 16, 32)[r] * 3)


@skill('frost_squall', 24)
def _(r):
    lo, hi = [(8, 16), (12, 24), (18, 36), (32, 64)][r]
    return spell('ice', lo * 2, hi * 2, 'An icy squall where you aim: %d-%d ice damage and slow.' % (lo * 2, hi * 2),
                 'Uma rajada gélida onde você mira: %d-%d de dano de gelo e lentidão.' % (lo * 2, hi * 2),
                 cooldown='3s', mp=(4, 7, 12, 24)[r] * 3, kind='target', radius=1.6, post=('slow_ice,50,2s',),
                 sound='soundfx/powers/freeze.ogg')


@skill('call_wisp', 20)
def _(r):
    return summon('rd_summon_wisp', (0.6, 1.0)[r], 'Call a fiery wisp to fight at your side.',
                  'Invoca uma fagulha de fogo para lutar ao seu lado.', cooldown='30s', mp=(12, 20)[r] * 3)


@skill('storm_lance', 7)
def _(r):
    lo, hi = [(10, 15), (15, 20), (20, 28), (36, 44)][r]
    st = (20, 25, 30, 40)[r]
    return spell('lightning', lo * 2, hi * 2, 'A bolt of lightning: %d-%d lightning damage, %d%% stun chance.' % (lo * 2, hi * 2, st),
                 'Um raio: %d-%d de dano elétrico, %d%% de chance de atordoar.' % (lo * 2, hi * 2, st), cooldown='5s',
                 mp=(5, 9, 18, 24)[r] * 3, anim='animations/powers/lightning.txt', post=('paralyze,0,1s,%d' % st,),
                 sound='soundfx/powers/shock.ogg', speed=24)


@skill('arcane_mantle', 21, (150, 190, 255))
def _(r):
    a, res = (3, 5, 7, 10)[r], (0, 15, 20, 30)[r]
    pairs = [('absorb', a)] + ([(x, res) for x in ('fire_resist', 'ice_resist', 'lightning_resist')] if res else [])
    en = '+%d absorb' % a + (' and +%d%% fire, ice and lightning resistance' % res if res else '') + ' for 20s.'
    pt = '+%d de absorção' % a + (' e +%d%% de resistência a fogo, gelo e raio' % res if res else '') + ' por 20s.'
    return buff(pairs, '20s', en, pt, cooldown='5s', mp=(3, 5, 9, 16)[r] * 3)


@skill('deep_well', 42)
def _(r):
    m = (20, 40, 60)[r]
    return passive([('mp', m), ('mp_regen', 5 * (r + 1))], '+%d max mana, faster mana regeneration.' % m,
                   '+%d de mana máxima, regeneração de mana mais rápida.' % m)


@skill('staff_adept', 2)
def _(r):
    d = (4, 8, 12, 16)[r]
    return passive([('dmg_ment', d)], 'With a staff: +%d magic damage.' % d, 'Com cajado: +%d de dano mágico.' % d,
                   extra=['requires_flags=staff'])


@skill('wand_adept', 2, (210, 150, 255))
def _(r):
    d = (2, 6, 10, 16)[r]
    return passive([('dmg_ment', d), ('accuracy', 5)], 'With a wand: +%d magic damage.' % d,
                   'Com varinha: +%d de dano mágico.' % d, extra=['requires_flags=wand'])


# ---- General (every class)
@skill('beast_friend', 14)
def _(r):
    return summon('rd_summon_beast', (0.8, 1.0, 1.2)[r], 'Call a wild beast to fight for you.',
                  'Chama uma fera selvagem para lutar por você.', cooldown='%ds' % (180, 120, 90)[r], mp=0)


@skill('delver', 30)
def _(r):
    f = (10, 18, 25)[r]
    return passive([('item_find', f)], '+%d%% item find.' % f, '+%d%% de chance de encontrar itens.' % f)


@skill('second_wind', 10, (150, 255, 150))
def _(r):
    h = (3, 6)[r]
    return passive([('hp_regen', h * 10)], 'You recover health faster (+%d0 health regeneration).' % h,
                   'Recupera a vida mais rápido (+%d0 de regeneração de vida).' % h)


@skill('silver_tongue', 17)
def _(r):
    g = (10, 20, 30)[r]
    return passive([('currency_find', g)], '+%d%% gold found.' % g, '+%d%% de ouro encontrado.' % g)


# ---- Advanced
@skill('runed_edge', 34)
def _(r):
    m = (25, 50, 100, 150)[r]
    return passive([('dmg_fire', pct(m)), ('dmg_ice', pct(m)), ('dmg_lightning', pct(m))],
                   'Your fire, ice and lightning damage from gear is increased by %d%%.' % m,
                   'Seu dano de fogo, gelo e raio vindo de equipamentos aumenta %d%%.' % m)


@skill('spell_thrift', 42, (170, 170, 255))
def _(r):
    g = (10, 20, 30)[r]
    return passive([('mp_regen', g)], 'Mana flows back faster (+%d mana regeneration).' % g,
                   'A mana volta mais rápido (+%d de regeneração de mana).' % g)


@skill('killing_flow', 5, (255, 120, 120))
def _(r):
    a = (25, 40, 60)[r]
    return triggered('on_kill', [('haste_attack', 100 + a)], '3s', 'After a kill, attack %d%% faster for 3s.' % a,
                     'Depois de matar, ataca %d%% mais rápido por 3s.' % a)


@skill('war_hymn', 45, (255, 220, 120))
def _(r):
    a, d, res = (2, 3, 4)[r], (4, 6, 10)[r], (0, 10, 25)[r]
    pairs = [('absorb', a), ('dmg_melee', d), ('dmg_ment', d)]
    pairs += [(x, res) for x in ('fire_resist', 'ice_resist', 'lightning_resist', 'dark_resist')] if res else []
    en = 'You and allies nearby: +%d absorb, +%d damage' % (a, d) + (', +%d%% to all resistances' % res if res else '') + ' for 12s.'
    pt = 'Você e aliados próximos: +%d de absorção, +%d de dano' % (a, d) + (', +%d%% em todas as resistências' % res if res else '') + ' por 12s.'
    return buff(pairs, '12s', en, pt, cooldown='12s', mp=(6, 9, 12)[r] * 3, sound='soundfx/powers/warcry.ogg',
                extra=['share_radius=6'])


@skill('blood_frenzy', 25, (255, 90, 90))
def _(r):
    s, a, d = (8, 12, 16)[r], (2, 3, 4)[r], (6, 8, 9)[r]
    return buff([('physical', s), ('absorb', a), ('immune', 100)], '%ds' % d,
                '+%d physical, +%d absorb and immunity to crowd control for %ds.' % (s, a, d),
                '+%d de físico, +%d de absorção e imunidade a controle por %ds.' % (s, a, d), cooldown='30s',
                sound='soundfx/powers/warcry.ogg')


@skill('thrill_of_the_kill', 38)
def _(r):
    d, a = (6, 8, 12)[r], (1, 2, 3)[r]
    return triggered('on_kill', [('dmg_melee', d), ('dmg_ranged', d), ('absorb', a)], '6s',
                     'After a kill: +%d damage and +%d absorb for 6s.' % (d, a),
                     'Depois de matar: +%d de dano e +%d de absorção por 6s.' % (d, a))


@skill('hardened_body', 31, (255, 200, 170))
def _(r):
    h = (5, 10, 15)[r]
    return passive([('hp', pct(h))], '+%d%% maximum health.' % h, '+%d%% de vida máxima.' % h)


@skill('immolate', 18, (255, 110, 60))
def _(r):
    lo, hi = [(15, 30), (20, 40), (28, 56)][r]
    a, res = (2, 3, 5)[r], (20, 40, 60)[r]
    return spell('fire', lo * 2, hi * 2, '%d-%d fire damage; the target loses %d absorb and %d%% resistances for 8s.' % (lo * 2, hi * 2, a, res),
                 '%d-%d de dano de fogo; o alvo perde %d de absorção e %d%% de resistências por 8s.' % (lo * 2, hi * 2, a, res),
                 cooldown='15s', mp=(25, 35, 45)[r] * 3,
                 post=('absorb_min,-%d,8s' % a, 'absorb_max,-%d,8s' % a, 'fire_resist,-%d,8s' % res, 'ice_resist,-%d,8s' % res,
                       'lightning_resist,-%d,8s' % res))


@skill('plague_mist', 27)
def _(r):
    lo, hi = [(10, 20), (14, 28), (18, 36)][r]
    res = (30, 50, 80)[r]
    return spell('poison', lo * 2, hi * 2, 'A toxic cloud: %d-%d poison damage, slows and lowers shadow resistance by %d%%.' % (lo * 2, hi * 2, res),
                 'Uma nuvem tóxica: %d-%d de dano de veneno, deixa lento e reduz a resistência a sombra em %d%%.' % (lo * 2, hi * 2, res),
                 cooldown='12s', mp=(20, 25, 30)[r] * 3, kind='target', radius=2.0, anim='animations/powers/dark_mist.txt',
                 post=('slow,50,4s', 'dark_resist,-%d,8s' % res, 'poison,%d,4s' % (lo // 2 + 2)))


def ward(sid):
    stat, vals, en_el, pt_el = WARDS[sid]

    def fn(r):
        v = vals[r]
        return passive([(stat, v)], '+%d%% %s resistance.' % (v, en_el), '+%d%% de resistência a %s.' % (v, pt_el))
    return fn


for _sid, _tint in (('grave_ward', (150, 120, 190)), ('ember_ward', (255, 120, 80)), ('frost_ward', (130, 190, 255)),
                    ('storm_ward', (255, 240, 120)), ('venom_ward', (140, 230, 110)), ('soul_ward', (255, 255, 235))):
    SPEC[_sid] = ward(_sid)
    ICON[_sid] = (4, _tint)


@skill('unmake', 26)
def _(r):
    d = (50, 75, 100)[r] * 2
    return spell('', d, d + d // 4, 'A ray of pure force: %d-%d damage.' % (d, d + d // 4),
                 'Um raio de força pura: %d-%d de dano.' % (d, d + d // 4), cooldown='20s', mp=(25, 50, 70)[r] * 3,
                 anim='animations/powers/plasmaball.txt', sound='soundfx/powers/shock.ogg', speed=20)


@skill('duelist', 1, (255, 215, 120))
def _(r):
    step, cap = (1, 2, 2)[r], (4, 6, 10)[r]
    n = cap // step
    return Rank(['type=fixed', 'passive=true', 'passive_trigger=on_active_power', 'buff=true',
                 'post_effect=rd_duel_%d,%d,4s' % (r, step * 2)],
                'Each attack adds +%d damage for 4s, stacking up to +%d.' % (step * 2, cap * 2),
                'Cada ataque soma +%d de dano por 4s, acumulando até +%d.' % (step * 2, cap * 2))


@skill('stone_caller', 20, (190, 150, 110))
def _(r):
    return summon('rd_summon_golem', (0.8, 1.0, 1.25)[r], 'Call a stone guardian that soaks up blows.',
                  'Invoca um guardião de pedra que aguenta os golpes.', cooldown='30s', mp=(40, 60, 80)[r] * 3 // 2)


@skill('blast_snares', 18, (255, 170, 60))
def _(r):
    lo, hi = [(12, 24), (18, 36), (24, 48)][r]
    return Rank(['type=fixed', 'new_state=cast', 'face=true', 'directional=true', 'starting_pos=melee',
                 'animation=animations/powers/bear_trap.txt', 'use_hazard=true', 'base_damage=ment',
                 'modifier_damage=absolute,%d,%d' % (lo * 2, hi * 2), 'trait_elemental=fire', 'lifespan=20s',
                 'radius=1.6', 'multitarget=true', 'cooldown=12s', 'floor=true'],
                'Set an explosive trap: %d-%d fire damage to everyone near it.' % (lo * 2, hi * 2),
                'Arma uma armadilha explosiva: %d-%d de dano de fogo em todos por perto.' % (lo * 2, hi * 2))


@skill('flame_caller', 37)
def _(r):
    return summon('rd_summon_fire', (0.7, 0.9, 1.1)[r], 'Call a fire elemental.', 'Invoca um elemental de fogo.',
                  cooldown='10s', mp=(25, 35, 45)[r] * 3 // 2)


@skill('pyre_of_faith', 37, (255, 220, 110))
def _(r):
    h, d = (5, 8, 10)[r], (8, 15, 21)[r] * 2
    return Rank(['type=fixed', 'new_state=cast', 'starting_pos=source', 'use_hazard=true', 'multitarget=true',
                 'base_damage=ment', 'modifier_damage=absolute,%d,%d' % (d * 3, d * 3), 'trait_elemental=holy',
                 'radius=2.5', 'lifespan=400ms', 'animation=animations/powers/runes_orange.txt',
                 'soundfx=soundfx/powers/burn.ogg', 'post_effect_src=hpot,%d,5s' % (h * 4),
                 'cooldown=30s', 'requires_mp=%d' % ((15, 25, 35)[r] * 3), 'share_radius=5'],
                'A holy pyre: %d holy damage around you; you and allies nearby heal %d HP per second for 5s.' % (d * 3, h * 4),
                'Uma pira sagrada: %d de dano sagrado ao redor; você e aliados próximos curam %d de vida por segundo por 5s.' % (d * 3, h * 4))


@skill('blade_dance', 35)
def _(r):
    a = (25, 50, 75)[r]
    return buff([('haste_attack', 100 + a)], '6s', 'Attack %d%% faster for 6s.' % a, 'Ataca %d%% mais rápido por 6s.' % a,
                cooldown='20s', sound='soundfx/powers/warcry.ogg')


@skill('pilgrims_step', 19)
def _(r):
    # EK: recall to a town. Here: blink to where you aim (co-op: join a friend)
    return Rank(['type=fixed', 'new_state=cast', 'buff_teleport=true', 'target_range=%d' % (6, 9)[r],
                 'soundfx=soundfx/powers/teleport.ogg', 'animation=animations/powers/sparkle.txt',
                 'cooldown=%ds' % (20, 12)[r], 'requires_mp=%d' % 20],
                'Step through space to where you aim (up to %d tiles).' % (6, 9)[r],
                'Atravessa o espaço até onde você mira (até %d metros).' % (6, 9)[r])


@skill('spirit_hound', 46)
def _(r):
    return summon('rd_summon_hound', (0.7, 0.9, 1.1)[r], 'Call a spirit hound to guard you.',
                  'Invoca um cão espiritual para protegê-lo.', cooldown='%ds' % (120, 90, 60)[r], mp=(15, 20, 35)[r] * 3)


@skill('crushing_blows', 31, (255, 110, 110))
def _(r):
    d = (2, 6, 10)[r]
    return passive([('dmg_melee', d)], '+%d melee damage on every hit.' % d, '+%d de dano corpo a corpo em cada golpe.' % d)


@skill('frost_caller', 40)
def _(r):
    return summon('rd_summon_frost', (0.7, 0.9, 1.1)[r], 'Call an ice elemental.', 'Invoca um elemental de gelo.',
                  cooldown='20s', mp=(25, 35, 45)[r] * 3 // 2)


@skill('veteran_stance', 4, (190, 190, 190))
def _(r):
    p = (35, 50)[r]
    return passive([('poise', p), ('absorb', r + 1)], 'Shrug off blows: +%d poise and +%d absorb.' % (p, r + 1),
                   'Aguenta golpes: +%d de firmeza e +%d de absorção.' % (p, r + 1))


@skill('blood_casting', 38, (200, 120, 255))
def _(r):
    s = (2, 3, 4)[r]
    return passive([('hp_steal', s)], 'Drink your enemies\' blood: %d%% of damage heals you.' % s,
                   'Bebe o sangue dos inimigos: %d%% do dano causado cura você.' % s)


@skill('arc_repulse', 15)
def _(r):
    d = (12, 25, 40)[r] * 2
    st = (0, 10, 30)[r]
    post = ['force,%d,150ms' % (10, 15, 20)[r]] + (['paralyze,0,1s,%d' % st] if st else [])
    return spell('lightning', d, d, 'Push everyone around you away with %d lightning damage%s.' % (d, ' (%d%% stun)' % st if st else ''),
                 'Empurra todos ao redor com %d de dano elétrico%s.' % (d, ' (%d%% de atordoar)' % st if st else ''),
                 cooldown='10s', mp=(8, 12, 16)[r] * 3, kind='nova', radius=2.2, post=tuple(post),
                 sound='soundfx/powers/shock.ogg')


@skill('brutal_criticals', 39)
def _(r):
    c = (3, 6, 10)[r]
    return passive([('crit', c)], '+%d%% critical chance; criticals hit very hard.' % c,
                   '+%d%% de chance de crítico; críticos batem muito forte.' % c)


@skill('venomcraft', 27, (140, 230, 110))
def _(r):
    d, res = (2, 4, 6)[r], (10, 20, 30)[r]
    return passive([('dmg_poison', d), ('poison_resist', res)], '+%d poison damage, +%d%% poison resistance.' % (d, res),
                   '+%d de dano de veneno, +%d%% de resistência a veneno.' % (d, res))


@skill('deadeye', 16)
def _(r):
    c = (3, 6, 9)[r]
    return passive([('crit', c), ('accuracy', 5)], '+%d%% critical chance.' % c, '+%d%% de chance de crítico.' % c)


@skill('keen_strikes', 16, (255, 140, 140))
def _(r):
    c = (3, 6, 9)[r]
    return passive([('crit', c), ('accuracy', 5)], '+%d%% critical chance.' % c, '+%d%% de chance de crítico.' % c)


@skill('quickdraw', 23)
def _(r):
    a = (40, 70, 100)[r]
    return buff([('haste_attack', 100 + a)], '6s', 'Attack %d%% faster for 6s.' % a, 'Ataca %d%% mais rápido por 6s.' % a,
                cooldown='20s', sound='soundfx/powers/warcry.ogg')


@skill('soul_harvest', 12, (140, 180, 255))
def _(r):
    m = (3, 6)[r]
    return triggered('on_kill', [('mp_restore', m)], '1s', 'Each kill restores %d%% of your mana.' % m,
                     'Cada abate restaura %d%% da sua mana.' % m)


@skill('smoke_veil', 26, (170, 170, 170))
def _(r):
    st = (0, 35, 50)[r]
    post = ['paralyze,0,%ds,%d' % ((0, 3, 5)[r], st)] if st else []
    return Rank(['type=fixed', 'new_state=cast', 'starting_pos=source', 'use_hazard=true', 'multitarget=true',
                 'no_attack=%s' % ('false' if st else 'true'), 'radius=2.5', 'lifespan=300ms',
                 'animation=animations/powers/dark_mist.txt', 'soundfx=soundfx/powers/teleport.ogg',
                 'post_effect_src=stealth,80,8s', 'cooldown=25s'] + ['post_effect=%s' % p for p in post],
                'Throw a smoke bomb and vanish' + (' (%d%% chance to stun those nearby).' % st if st else '.'),
                'Joga uma bomba de fumaça e some' + (' (%d%% de chance de atordoar quem estiver perto).' % st if st else '.'))


@skill('binder', 43, (200, 150, 255))
def _(r):
    m = (4, 8, 12)[r]
    return passive([('mental', m)], '+%d mental: your summons come out stronger.' % m,
                   '+%d de mental: suas invocações ficam mais fortes.' % m)


@skill('banish_dead', 45, (255, 255, 255))
def _(r):
    return Rank(['type=fixed', 'new_state=cast', 'starting_pos=source', 'use_hazard=true', 'multitarget=true',
                 'no_attack=true', 'radius=%d' % (2, 4, 6)[r], 'lifespan=300ms', 'animation=animations/powers/runes.txt',
                 'soundfx=soundfx/powers/heal.ogg', 'post_effect=paralyze,0,%ds' % (2, 3, 4)[r],
                 'cooldown=20s', 'requires_mp=%d' % ((4, 5, 6)[r] * 3)],
                'A holy word paralyzes every enemy within %d tiles for %ds.' % ((2, 4, 6)[r], (2, 3, 4)[r]),
                'Uma palavra sagrada paralisa os inimigos a até %d metros por %ds.' % ((2, 4, 6)[r], (2, 3, 4)[r]))


@skill('leeching_edge', 38, (150, 80, 110))
def _(r):
    s, d = (2, 3, 4)[r], (2, 4, 6)[r]
    return passive([('hp_steal', s), ('dmg_dark', d)], '+%d shadow damage and %d%% of damage heals you.' % (d, s),
                   '+%d de dano de sombra e %d%% do dano cura você.' % (d, s))


# ------------------------------------------------------------------ summons
SUMMONS = {  # category: (name, name_pt, gfx template, hp, hp/lvl, dmg, dmg/lvl, absorb, speed, element)
    'rd_summon_wisp': ('Your Fiery Wisp', 'Sua Fagulha', 'enemies/base/skeleton_mage.txt', 50, 12, 8, 3, 0, 5, 'fire'),
    'rd_summon_beast': ('Your Wild Beast', 'Sua Fera', 'enemies/base/antlion.txt', 90, 20, 10, 4, 2, 5, ''),
    'rd_summon_golem': ('Your Stone Guardian', 'Seu Guardião de Pedra', 'enemies/base/antlion_small.txt', 160, 35, 8, 3, 6, 3.5, ''),
    'rd_summon_fire': ('Your Fire Elemental', 'Seu Elemental de Fogo', 'enemies/base/wyvern_fire.txt', 90, 18, 12, 5, 2, 5, 'fire'),
    'rd_summon_frost': ('Your Ice Elemental', 'Seu Elemental de Gelo', 'enemies/base/wyvern_ice.txt', 100, 20, 10, 4, 3, 5, 'ice'),
    'rd_summon_hound': ('Your Spirit Hound', 'Seu Cão Espiritual', 'enemies/base/antlion_ice.txt', 80, 16, 10, 4, 2, 6.5, ''),
}


def gen_summons():
    for cat, (name, _pt, gfx, hp, hpl, dmg, dmgl, ab, speed, el) in SUMMONS.items():
        lines = [HEADER, 'INCLUDE %s\n' % gfx, 'name=%s' % name, 'level=1', 'categories=%s' % cat,
                 'stat=hp,%d' % hp, 'speed=%s' % speed, 'turn_delay=300ms', 'chance_pursue=30',
                 'power=melee,164,60', 'stat=accuracy,95', 'stat=avoidance,15', 'stat=poise,30',
                 'stat=dmg_melee_min,%d' % dmg, 'stat=dmg_melee_max,%d' % (dmg * 3 // 2), 'cooldown=1s',
                 'stat=absorb_min,%d' % ab, 'stat=absorb_max,%d' % (ab + 2),
                 'stat_per_level=hp,%d' % hpl, 'stat_per_level=accuracy,4', 'stat_per_level=avoidance,3',
                 'stat_per_level=dmg_melee_min,%d' % dmgl, 'stat_per_level=dmg_melee_max,%d' % (dmgl * 3 // 2),
                 'stat_per_level=absorb_min,1', 'stat_per_level=absorb_max,1',
                 'stat_per_primary=mental,hp,%d' % max(2, hpl // 4), 'stat_per_primary=mental,dmg_melee_max,1']
        if el:
            lines += ['stat=dmg_%s_min,%d' % (el, dmg // 2), 'stat=dmg_%s_max,%d' % (el, dmg),
                      'stat=%s_resist,50' % el]
        write(rel('enemies', '%s.txt' % cat), '\n'.join(lines) + '\n')


# ------------------------------------------------------------------ output
def build(skills):
    """Rank objects for every skill; checks SPEC covers skills.csv"""
    missing = [s['id'] for s in skills if s['id'] not in SPEC]
    if missing:
        sys.exit('gen_skills: no SPEC for %s' % ', '.join(missing))
    out = {}
    for s in skills:
        out[s['id']] = [SPEC[s['id']](r) for r in range(s['ranks'])]
    return out


def gen_powers(skills, ranks):
    body = [HEADER, '# %d skills, ids %d-%d (skill index * 5 + rank)\n' % (len(skills), ID_BASE, ID_BASE + len(skills) * 5)]
    for s in skills:
        body.append('\n# ---- %s (%s, %s; EK: %s)' % (s['name'], s['tab'], s['classes'], s['ek_name']))
        for r, rk in enumerate(ranks[s['id']]):
            body.append('[power]\nid=%d\nname=%s\ndescription=%s\nicon=%d' % (pid(s, r), s['name'], rk.en, ICON_BASE + s['index']))
            body += rk.lines
            body.append('')
    # the classes' basic attacks trigger "on_active_power" passives
    # (Wide Swing, Duelist); a second [power] section only adds this key
    body.append('\n# basic attacks: Swing, Blood Strike, Shoot, Dagger Strike, Holy Strike, Channel, Mage basic')
    for basic in BASIC_ATTACKS:
        body.append('[power]\nid=%d\ncan_trigger_passives=true\n' % basic)
    write(rel('powers', 'skills.txt'), '\n'.join(body))


def gen_damage_types():
    write(rel('engine', 'damage_types.txt'), 'APPEND\n' + HEADER + '''
[damage_type]
id=poison
name=Poison Damage
name_short=Poison
description=Adds poison damage to non-elemental attacks.
min=dmg_poison_min
max=dmg_poison_max
elemental=true

[damage_type]
id=holy
name=Holy Damage
name_short=Holy
description=Adds holy damage to non-elemental attacks. Undead are weak to it.
min=dmg_holy_min
max=dmg_holy_max
elemental=true
''')


def gen_effects():
    lines = ['APPEND', HEADER]
    # Duelist: stacking damage
    for r, cap in enumerate((4, 6, 10)):
        step = (1, 2, 2)[r]
        lines += ['[effect]', 'id=rd_duel_%d' % r, 'name=Duelist', 'type=dmg_melee_max', 'icon=%d' % (ICON_BASE + 0),
                  'can_stack=true', 'max_stacks=%d' % (cap // step), 'group_stack=true', '']
    write(rel('powers', 'effects.txt'), '\n'.join(lines))


GRID_X, GRID_Y, COLS, DX, DY = 96, 122, 5, 96, 84   # matches darkfantasy_gui gen_theme panel_powers()


def gen_trees(skills):
    by_id = {s['id']: s for s in skills}
    for cls in CLASSES:
        lines = [HEADER, '# %s skills sheet (menus/powers.txt detail_area = EK layout)\n' % cls.capitalize()]
        for _k, title in TABS:
            lines += ['[tab]', 'title=%s' % title, '']
        for t, (tab, _title) in enumerate(TABS):
            mine = [s for s in skills if s['tab'] == tab and (cls in s['classes'].split(',') or s['classes'] == 'all')]
            for n, s in enumerate(mine):
                x, y = GRID_X + (n % COLS) * DX, GRID_Y + (n // COLS) * DY
                lines += ['[power]', 'id=%d' % pid(s, 0), 'tab=%d' % t, 'position=%d,%d' % (x, y),
                          'requires_point=%d' % s['costs'][0]]
                if s['requires_level']:
                    lines.append('requires_level=%s' % s['requires_level'])
                for req in filter(None, s['requires'].split(';')):
                    parts = req.split(':')
                    if parts[0] == 'skill':
                        other = by_id[parts[1]]
                        if cls in other['classes'].split(',') or other['classes'] == 'all':
                            lines.append('requires_power=%d' % pid(other, int(parts[2]) - 1))
                    else:
                        lines.append('requires_primary=%s,%s' % (parts[0], parts[1]))
                if s['ranks'] > 1:
                    lines.append('upgrades=%s' % ','.join(str(pid(s, r)) for r in range(1, s['ranks'])))
                lines.append('')
                for r in range(1, s['ranks']):
                    lines += ['[upgrade]', 'id=%d' % pid(s, r), 'requires_point=%d' % s['costs'][r], '']
        write(rel('powers', 'trees', 'rd_%s.txt' % cls), '\n'.join(lines))


def gen_icons(skills):
    from PIL import Image
    src = Image.open(os.path.join(MODS, 'fantasycore', 'images', 'icons', 'icons.png')).convert('RGBA')
    S = 64
    cols = 8
    sheet = Image.new('RGBA', (cols * S, ((len(skills) + cols - 1) // cols) * S), (0, 0, 0, 0))
    for s in skills:
        idx, tint = ICON[s['id']]
        ic = src.crop(((idx % 8) * S, (idx // 8) * S, (idx % 8) * S + S, (idx // 8) * S + S))
        if tint:
            r, g, b, a = ic.split()
            r = r.point(lambda v, k=tint[0]: v * k // 255)
            g = g.point(lambda v, k=tint[1]: v * k // 255)
            b = b.point(lambda v, k=tint[2]: v * k // 255)
            ic = Image.merge('RGBA', (r, g, b, a))
        i = s['index']
        sheet.alpha_composite(ic, ((i % cols) * S, (i // cols) * S))
    out = rel('images', 'icons', 'icons_skills.png')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    sheet.save(out)


def translations():
    """(en, pt) pairs for gen_content.py's .po files"""
    skills = load_skills()
    ranks = build(skills)
    pairs = [('Class', 'Classe'), ('Skills', 'Habilidades'), ('General', 'Gerais'), ('Advanced', 'Avançadas'),
             ('Learn', 'Aprender'), ('First level:', 'Primeiro nível:'), ('Maximum rank', 'Nível máximo'),
             ('Requires %d Skill Points', 'Requer %d pontos de habilidade'), ('Duelist', 'Duelista'),
             ('Poison Damage', 'Dano de Veneno'), ('Poison', 'Veneno'), ('Holy Damage', 'Dano Sagrado'), ('Holy', 'Sagrado'),
             ('Adds poison damage to non-elemental attacks.', 'Adiciona dano de veneno aos ataques não elementais.'),
             ('Adds holy damage to non-elemental attacks. Undead are weak to it.',
              'Adiciona dano sagrado aos ataques não elementais. Mortos-vivos são fracos a ele.')]
    for s in skills:
        pairs.append((s['name'], s['name_pt']))
        for rk in ranks[s['id']]:
            pairs.append((rk.en, rk.pt))
    for cat, v in SUMMONS.items():
        pairs.append((v[0], v[1]))
    return pairs


def main():
    skills = load_skills()
    ranks = build(skills)
    gen_powers(skills, ranks)
    gen_damage_types()
    gen_effects()
    gen_trees(skills)
    gen_summons()
    gen_icons(skills)
    print('skills: %d (%d ranks) -> powers/skills.txt, trees, %d summons, icons_skills.png' % (
        len(skills), sum(len(v) for v in ranks.values()), len(SUMMONS)))


if __name__ == '__main__':
    main()
