#!/usr/bin/env python3
"""
Procedural serpent sprites: Jararaca, Sucuri, Boitatá, Minhocão, Cobra Grande.

Nenhum pacote de arte do projeto tem cobra, então elas são desenhadas aqui:
o corpo é um tubo de esferas num z-buffer (vista isométrica 2:1), com sombra,
contorno e tons quantizados pra combinar com o filtro pixelado do jogo.

Escreve (tudo GENERATED, rode de novo depois de mexer em SPECIES):
  images/enemies/rd_<nome>_<n>.png     folhas de sprite (até 2048x2048 cada)
  animations/enemies/rd_<nome>.txt     animações (8 direções, formato do Flare)

Uso:  python3 tools/gen_serpents.py [nome ...]      (precisa de numpy e Pillow)
      python3 tools/gen_serpents.py --preview        (só gera previews/serpents_*.png)
"""
import math, os, random, sys
import numpy as np
from PIL import Image, ImageFilter

TOOLS = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(TOOLS)
HEADER = '# GENERATED by tools/gen_serpents.py -- edit SPECIES there, not this file.\n'
SHEET = 2048

# vista: ground (gx para a direita da tela, gy para baixo da tela), z para cima
C30, S30 = math.cos(math.radians(30)), math.sin(math.radians(30))
VIEW = np.array([0.0, C30, S30])                 # em direção à câmera (ground coords)
LIGHT = np.array([-0.45, -0.62, 0.64])           # na tela: x direita, y baixo, z para a câmera
LIGHT /= np.linalg.norm(LIGHT)

# animações: nome -> (frames, duração ms, tipo, active_frame)
ANIMS = [
    ('stance', 4, 533, 'back_forth', None),
    ('run', 8, 533, 'looped', None),
    ('swing', 4, 400, 'play_once', 2),
    ('cast', 4, 500, 'play_once', 2),
    ('shoot', 4, 500, 'play_once', 2),
    ('block', 2, 200, 'play_once', None),
    ('hit', 2, 133, 'back_forth', None),
    ('die', 6, 800, 'play_once', None),
    ('critdie', 8, 1066, 'play_once', None),
    ('spawn', 6, 800, 'play_once', None),
]

ANIMS_PROP = [('stance', 8, 900, 'looped', None)]

SPECIES = {
    # cobra comum das hordas
    'jararaca': dict(mode='snake', L=78, r=4.6, r_tail=1.2, head=1.3,
                     base=(128, 98, 58), dark=(62, 44, 28), belly=(196, 176, 120), eyes=(250, 215, 70),
                     pattern='diamond', period=13, canvas=(150, 110)),
    # sucuri (elite): grossa, verde-oliva com manchas
    'sucuri': dict(mode='snake', L=150, r=8.5, r_tail=2.2, head=1.15,
                   base=(92, 110, 48), dark=(28, 32, 18), belly=(190, 180, 105), eyes=(235, 190, 60),
                   pattern='spots', period=20, canvas=(270, 190), durations={'swing': 500}),
    # Boitatá (chefe): serpente de fogo, olhos enormes
    'boitata': dict(mode='snake', L=210, r=11, r_tail=2.5, head=1.25,
                    base=(255, 120, 25), dark=(170, 35, 10), belly=(255, 225, 110), eyes=(215, 245, 255),
                    pattern='fire', period=16, canvas=(360, 260), eye_size=0.34, glow=(255, 120, 30),
                    durations={'swing': 550, 'cast': 700, 'shoot': 700}),
    # Cobra Grande / Boiúna (chefe final): preta, brilho molhado, olhos amarelos
    'cobra_grande': dict(mode='snake', L=320, r=16, r_tail=3.5, head=1.2,
                         base=(38, 46, 40), dark=(16, 20, 18), belly=(92, 100, 70), eyes=(255, 214, 40),
                         pattern='bands', period=26, canvas=(520, 380), sheen=True, eye_size=0.22,
                         durations={'swing': 700, 'cast': 800, 'shoot': 800}),
    # Minhocão (chefe): minhoca gigante que nada pela terra
    'minhocao': dict(mode='burrow', L=260, r=19, r_tail=15, head=1.12,
                     base=(118, 90, 66), dark=(66, 48, 36), belly=(150, 118, 88), eyes=None,
                     pattern='rings', period=15, canvas=(460, 330), sheen=True,
                     materials={4: dict(pattern='none', base=(225, 210, 175), dark=(150, 130, 100), belly=(235, 225, 195))},
                     durations={'swing': 750, 'cast': 800, 'shoot': 800, 'die': 1100, 'critdie': 1300, 'spawn': 1000}),
    # Mula sem Cabeça (chefe): no lugar da cabeça, uma labareda; ferraduras de prata
    'mula': dict(mode='quad', L=100, r=14, r_tail=3, head=1.0,
                 base=(64, 45, 34), dark=(40, 28, 22), belly=(96, 74, 58), eyes=None,
                 pattern='none', period=10, canvas=(320, 290), edge=1.6, glow=(255, 120, 30),
                 materials={1: dict(pattern='fire', base=(255, 135, 30), dark=(200, 45, 10), belly=(255, 238, 140)),
                            2: dict(pattern='none', base=(190, 190, 200), dark=(120, 120, 130), belly=(205, 205, 215), sheen=True),
                            3: dict(pattern='none', base=(32, 24, 20), dark=(20, 15, 12), belly=(44, 34, 28))},
                 durations={'run': 450, 'swing': 650, 'cast': 700, 'shoot': 700}),
    # Saci-Pererê (chefe): uma perna, gorro vermelho, cachimbo, redemoinho
    'saci': dict(mode='biped', kind='saci', L=100, r=10, r_tail=3, head=1.0,
                 base=(78, 50, 36), dark=(52, 33, 24), belly=(96, 64, 46), eyes=None,
                 pattern='none', period=10, canvas=(260, 300), edge=1.4,
                 materials={1: dict(pattern='none', base=(205, 32, 30), dark=(140, 20, 20), belly=(215, 60, 50)),
                            2: dict(pattern='none', base=(196, 188, 160), dark=(140, 130, 110), belly=(170, 160, 135)),
                            3: dict(pattern='none', base=(118, 76, 42), dark=(80, 50, 28), belly=(130, 90, 55)),
                            4: dict(pattern='flat', base=(255, 236, 150), dark=(255, 236, 150), belly=(255, 236, 150)),
                            5: dict(pattern='flat', base=(205, 205, 200), dark=(205, 205, 200), belly=(205, 205, 200)),
                            6: dict(pattern='none', base=(176, 146, 104), dark=(130, 104, 72), belly=(190, 162, 120))},
                 durations={'swing': 500, 'cast': 700, 'shoot': 700}),
    # Curupira (chefe): guardião da mata, cabelo de fogo e pés virados para trás
    'curupira': dict(mode='biped', kind='curupira', L=100, r=10, r_tail=3, head=1.0,
                     base=(104, 96, 62), dark=(70, 64, 40), belly=(120, 110, 74), eyes=None,
                     pattern='none', period=10, canvas=(260, 330), edge=1.4, glow=(255, 120, 30),
                     materials={1: dict(pattern='fire', base=(255, 120, 25), dark=(200, 40, 10), belly=(255, 225, 110)),
                                2: dict(pattern='none', base=(66, 128, 44), dark=(34, 76, 26), belly=(88, 150, 58)),
                                3: dict(pattern='none', base=(104, 72, 44), dark=(70, 48, 30), belly=(120, 86, 54)),
                                4: dict(pattern='flat', base=(170, 255, 120), dark=(170, 255, 120), belly=(170, 255, 120))},
                     durations={'swing': 550, 'cast': 700, 'shoot': 700}),
    # Lobisomem (hordas + chefe da Lua Cheia): lobo em pé, corcunda, calça rasgada
    'lobisomem': dict(mode='beast', kind='lobisomem', L=100, r=10, r_tail=3, head=1.0, hunch=22, hip=3.3, arm=3.0,
                      base=(86, 78, 70), dark=(66, 58, 52), belly=(120, 110, 96), eyes=None,
                      pattern='fur', period=10, canvas=(300, 330), edge=1.4,
                      materials={1: dict(pattern='none', base=(128, 116, 100), dark=(90, 80, 70), belly=(150, 138, 120)),
                                 2: dict(pattern='none', base=(226, 218, 196), dark=(170, 160, 140), belly=(236, 230, 212)),
                                 3: dict(pattern='none', base=(70, 62, 84), dark=(44, 38, 54), belly=(84, 76, 100)),
                                 4: dict(pattern='flat', base=(255, 206, 60), dark=(255, 206, 60), belly=(255, 206, 60)),
                                 5: dict(pattern='none', base=(60, 16, 20), dark=(30, 8, 10), belly=(70, 20, 24))},
                      durations={'swing': 450, 'cast': 700, 'shoot': 700}),
    # Mapinguari (chefe): gigante peludo da Amazônia, um olho só, boca na barriga, pés virados
    'mapinguari': dict(mode='beast', kind='mapinguari', L=100, r=10, r_tail=3, head=1.0, hunch=10, hip=3.2, arm=3.2, bulk=1.35,
                       base=(110, 62, 40), dark=(84, 46, 30), belly=(130, 80, 54), eyes=None,
                       pattern='fur', period=10, canvas=(340, 360), edge=1.4,
                       materials={1: dict(pattern='none', base=(90, 30, 30), dark=(60, 18, 18), belly=(110, 40, 40)),
                                  2: dict(pattern='none', base=(228, 216, 180), dark=(170, 156, 124), belly=(236, 228, 200)),
                                  4: dict(pattern='flat', base=(250, 240, 120), dark=(250, 240, 120), belly=(250, 240, 120)),
                                  5: dict(pattern='none', base=(40, 6, 10), dark=(24, 4, 6), belly=(50, 10, 14))},
                       durations={'swing': 650, 'cast': 800, 'shoot': 800}),
    # Cuca (chefe): bruxa com cabeça de jacaré e cabelo loiro, vestido roxo, feitiço verde
    'cuca': dict(mode='beast', kind='cuca', L=100, r=10, r_tail=3, head=1.0, hunch=14, hip=3.2, arm=2.8,
                 base=(78, 108, 56), dark=(44, 66, 32), belly=(150, 160, 96), eyes=None,
                 pattern='spots', period=9, canvas=(320, 360), edge=1.4, glow=(120, 255, 110),
                 materials={1: dict(pattern='none', base=(236, 196, 84), dark=(180, 140, 50), belly=(250, 220, 120)),
                            2: dict(pattern='none', base=(236, 230, 206), dark=(180, 170, 150), belly=(245, 240, 220)),
                            3: dict(pattern='none', base=(92, 46, 104), dark=(56, 26, 64), belly=(116, 64, 130)),
                            4: dict(pattern='flat', base=(255, 214, 40), dark=(255, 214, 40), belly=(255, 214, 40)),
                            5: dict(pattern='none', base=(70, 14, 20), dark=(40, 8, 12), belly=(80, 20, 26)),
                            6: dict(pattern='fire', base=(170, 255, 120), dark=(30, 150, 40), belly=(230, 255, 200))},
                 durations={'swing': 550, 'cast': 800, 'shoot': 800}),
    # Bicho-Papão (chefe): sombra alta de capuz, olhos acesos, sorriso de dentes, mãos compridas
    'papao': dict(mode='beast', kind='papao', L=100, r=10, r_tail=3, head=1.0, hunch=16, hip=4.1, arm=3.9, bulk=0.85,
                  base=(150, 140, 150), dark=(100, 92, 100), belly=(170, 160, 170), eyes=None,
                  pattern='none', period=10, canvas=(320, 380), edge=1.4, glow=(170, 90, 255),
                  materials={2: dict(pattern='none', base=(230, 224, 210), dark=(170, 160, 150), belly=(240, 236, 226)),
                             3: dict(pattern='none', base=(34, 30, 40), dark=(22, 20, 26), belly=(46, 42, 54)),
                             4: dict(pattern='flat', base=(255, 250, 200), dark=(255, 250, 200), belly=(255, 250, 200)),
                             5: dict(pattern='flat', base=(6, 4, 8), dark=(6, 4, 8), belly=(6, 4, 8)),
                             6: dict(pattern='fire', base=(200, 140, 255), dark=(90, 30, 170), belly=(240, 220, 255))},
                  durations={'swing': 550, 'cast': 800, 'shoot': 800}),
    # objetos do acampamento (mode 'prop': só a animação stance, em loop)
    'camp_fogueira': dict(mode='prop', kind='campfire', L=40, r=10, r_tail=1, head=1.0, base=(0, 0, 0), dark=(0, 0, 0),
                          belly=(0, 0, 0), eyes=None, pattern='none', period=10, canvas=(140, 150), edge=1.2, glow=(255, 130, 40),
                          materials={1: dict(pattern='none', base=(128, 122, 112), dark=(84, 80, 74), belly=(140, 134, 124)), 2: dict(pattern='none', base=(104, 70, 42), dark=(70, 46, 28), belly=(120, 84, 52)), 3: dict(pattern='fire', base=(255, 130, 30), dark=(200, 45, 10), belly=(255, 235, 130))}),
    'camp_portal': dict(mode='prop', kind='portal', L=40, r=12, r_tail=1, head=1.0, base=(0, 0, 0), dark=(0, 0, 0),
                        belly=(0, 0, 0), eyes=None, pattern='none', period=10, canvas=(200, 260), edge=1.2, glow=(255, 110, 30),
                        materials={1: dict(pattern='none', base=(128, 122, 112), dark=(84, 80, 74), belly=(140, 134, 124)), 3: dict(pattern='fire', base=(255, 130, 30), dark=(200, 45, 10), belly=(255, 235, 130))}),
    'camp_altar': dict(mode='prop', kind='altar', L=40, r=10, r_tail=1, head=1.0, base=(0, 0, 0), dark=(0, 0, 0),
                       belly=(0, 0, 0), eyes=None, pattern='none', period=10, canvas=(170, 230), edge=1.2, glow=(90, 170, 255),
                       materials={1: dict(pattern='none', base=(128, 122, 112), dark=(84, 80, 74), belly=(140, 134, 124)), 2: dict(pattern='none', base=(236, 228, 206), dark=(180, 170, 150), belly=(240, 234, 216)),
                                  3: dict(pattern='fire', base=(255, 130, 30), dark=(200, 45, 10), belly=(255, 235, 130)), 4: dict(pattern='fire', base=(90, 190, 255), dark=(30, 60, 200), belly=(220, 245, 255))}),
}

# tamanho na tela: os chefes precisam ser bem maiores que o herói
SCALE = {'lobisomem': 1.3, 'mapinguari': 1.6, 'cuca': 1.6, 'papao': 1.6, 'sucuri': 1.2, 'boitata': 1.5, 'cobra_grande': 1.5, 'minhocao': 1.6, 'mula': 1.6, 'saci': 1.5, 'curupira': 1.55,
         'camp_fogueira': 1.7, 'camp_portal': 1.7, 'camp_altar': 2.0}
for _n, _k in SCALE.items():
    _sp = SPECIES[_n]
    for _key in ('L', 'r', 'r_tail', 'period'):
        _sp[_key] = _sp[_key] * _k
    _sp['canvas'] = (int(_sp['canvas'][0] * _k), int(_sp['canvas'][1] * _k))


# ------------------------------------------------------------------ geometry
def dir_vec(d):
    """Flare direction (0..7) -> unit vector in ground coords."""
    th = math.radians((d - 5) * 45)
    c, s = math.cos(th), math.sin(th)
    return np.array([(c - s) / math.sqrt(2), (c + s) / math.sqrt(2)])


def smooth(x):
    x = min(1.0, max(0.0, x))
    return x * x * (3 - 2 * x)


def radius_at(sp, s):
    """Tube radius along the body (s = 0 at the head)."""
    L, r = sp['L'], sp['r']
    u = s / L
    if u < 0.07:
        return r * sp['head']
    if u < 0.13:  # pescoço
        return r * (sp['head'] + (0.82 - sp['head']) * smooth((u - 0.07) / 0.06))
    if u < 0.3:
        return r * (0.82 + 0.18 * smooth((u - 0.13) / 0.17))
    if u < 0.55:
        return r
    return r + (sp['r_tail'] - r) * smooth((u - 0.55) / 0.45)


def snake_spine(sp, head_a, amp, lam, phase, env_len, raise_h, raise_len, lie=0.0):
    """Arc-length spine behind the head: returns [(s, a, b, z)] in local coords
    (a = forward, b = to the side). The heading wiggles as a travelling sine."""
    L = sp['L']
    pts = []
    a, b = head_a, 0.0
    s = 0.0
    while s <= L:
        r = radius_at(sp, s)
        env = smooth(s / env_len) if env_len > 0 else 1.0
        psi = amp * env * math.sin(2 * math.pi * s / lam - phase)
        z = r * 0.85 * (1 - lie * 0.25) + raise_h * smooth(1 - s / raise_len) if raise_len > 0 else r * 0.85
        pts.append((s, a, b, z))
        ds = max(0.8, r * 0.3)
        # while raised, the neck consumes less ground length
        horiz = 1.0 if raise_len <= 0 or s > raise_len else 0.55 + 0.45 * (s / raise_len)
        a -= ds * math.cos(psi) * horiz
        b += ds * math.sin(psi) * horiz
        s += ds
    return pts


def bezier(p0, p1, p2, p3, n=200):
    t = np.linspace(0, 1, n)[:, None]
    return ((1 - t) ** 3) * p0 + 3 * ((1 - t) ** 2) * t * p1 + 3 * (1 - t) * t * t * p2 + (t ** 3) * p3


def resample(curve, sp, s0=0.0):
    """Points along a 3D polyline (head first) spaced by the local radius."""
    seg = np.linalg.norm(np.diff(curve, axis=0), axis=1)
    cum = np.concatenate([[0], np.cumsum(seg)])
    out, s = [], 0.0
    while s <= cum[-1]:
        i = min(np.searchsorted(cum, s, side='right') - 1, len(seg) - 1)
        f = (s - cum[i]) / seg[i] if seg[i] > 0 else 0
        p = curve[i] + (curve[i + 1] - curve[i]) * f
        out.append((s0 + s, p[0], p[1], p[2]))
        s += max(0.8, radius_at(sp, s0 + s) * 0.3)
    return out, s0 + cum[-1]


# ------------------------------------------------------------------ poses
def snake_pose(sp, anim, f, n):
    """-> dict(pts, mouth, flash, dark, clip_z, eyes)"""
    L, r = sp['L'], sp['r']
    t = f / n
    pose = dict(mouth=0.0, flash=0.0, dark=0.0, clip=None, eyes=True, dust=0.0)
    base = dict(head_a=0.3 * L, amp=0.95, lam=0.55 * L, phase=0.0, env_len=0.12 * L,
                raise_h=r * 2.0, raise_len=0.2 * L)
    if anim in ('stance', 'block'):
        base['phase'] = 0.5 * t * 2
        base['raise_h'] = r * (2.0 + 0.25 * math.sin(2 * math.pi * t))
    elif anim == 'run':
        base.update(amp=0.75, phase=2 * math.pi * t, raise_h=r * 1.0, env_len=0.18 * L, head_a=0.34 * L)
    elif anim == 'swing':
        k = [(0.2, 2.8, 1.15, 0.2), (0.16, 3.2, 1.2, 0.5), (0.58, 0.4, 0.55, 1.0), (0.42, 1.2, 0.8, 0.6)][f]
        base.update(head_a=k[0] * L, raise_h=r * k[1], amp=k[2])
        pose['mouth'] = k[3]
        if f == 2:
            base['env_len'] = 0.4 * L
    elif anim in ('cast', 'shoot'):
        rise = [3.0, 3.8, 4.2, 3.8][f]
        base.update(head_a=0.22 * L, raise_h=r * rise, raise_len=0.28 * L, amp=1.1)
        pose['mouth'] = [0.2, 0.6, 1.0, 0.8][f]
    elif anim == 'hit':
        base.update(head_a=0.25 * L, raise_h=r * 1.5)
        pose['flash'] = [0.55, 0.25][f]
    elif anim in ('die', 'critdie'):
        p = f / (n - 1)
        base.update(raise_h=r * 2.0 * (1 - p) ** 2, amp=0.95 - 0.5 * p, head_a=0.3 * L + 0.05 * L * p)
        pose['dark'] = 0.5 * p
        pose['eyes'] = p < 0.6
        pose['mouth'] = 0.5 if 0.2 < p < 0.8 else 0.0
        if anim == 'critdie':
            pose['flash'] = max(0.0, 0.5 - p * 2)
        base['lie'] = p
    elif anim == 'spawn':
        p = f / (n - 1)
        base.update(raise_h=r * 2.0)
        pose['clip'] = 0.0
        pose['sink'] = (1 - p) * (r * 2.0 + r * 2.5)
        pose['dust'] = 1 - p
    pts = snake_spine(sp, base['head_a'], base['amp'], base['lam'], base['phase'], base['env_len'],
                      base['raise_h'], base['raise_len'], base.get('lie', 0.0))
    if pose.get('sink'):
        pts = [tuple(p[:3]) + (p[3] - pose['sink'],) + tuple(p[4:]) for p in pts]
    pose['pts'] = pts
    return pose


def burrow_pose(sp, anim, f, n):
    """Minhocão: sai de um buraco no chão (a = hole_a) e só a parte de cima aparece."""
    r = sp['r']
    t = f / n
    hole = -0.2 * r
    pose = dict(mouth=0.55, flash=0.0, dark=0.0, clip=0.0, eyes=False, dust=0.0, holes=[hole], humps=[])
    # cabeça sempre curvada para a frente: a bocarra é o que se vê
    H, F, sway, tilt = 3.9 * r, 2.3 * r, 0.0, -0.6
    if anim in ('stance', 'block'):
        sway = 0.7 * r * math.sin(2 * math.pi * t)
        H += 0.3 * r * math.sin(2 * math.pi * t)
    elif anim == 'run':
        H, F, tilt = 3.0 * r, 2.8 * r, -0.5
        H += 0.35 * r * math.sin(2 * math.pi * t * 2)
        sway = 0.4 * r * math.sin(2 * math.pi * t)
        pose['humps'] = [(hole - 2.3 * r - 3.2 * r * k, 2.6 * r, (t + 0.5 * k) % 1.0) for k in range(2)]
        pose['dust'] = 0.5
    elif anim == 'swing':
        H, F, tilt = [(5.4 * r, 0.0, 0.6), (5.8 * r, -0.6 * r, 0.9), (0.9 * r, 4.6 * r, -1.0), (3.0 * r, 2.8 * r, 0)][f]
        pose['mouth'] = [0.5, 0.9, 1.0, 0.4][f]
        pose['dust'] = 1.0 if f == 2 else 0.0
        pose['slam'] = f == 2
    elif anim in ('cast', 'shoot'):
        H, F, tilt = [(4.8 * r, 1.0 * r, 0.6), (5.6 * r, 0.6 * r, 1.2), (6.0 * r, 0.4 * r, 1.6), (5.6 * r, 0.6 * r, 1.3)][f]
        pose['mouth'] = [0.3, 0.8, 1.0, 1.0][f]
    elif anim == 'hit':
        H, F = 4.0 * r, 0.5 * r
        pose['flash'] = [0.55, 0.25][f]
    elif anim in ('die', 'critdie'):
        p = f / (n - 1)
        H = 4.4 * r * (1 - p) + 1.0 * r * p
        F = 1.4 * r * (1 - p) + 5.5 * r * p
        pose['dark'] = 0.45 * p
        pose['mouth'] = 0.6 * (1 - p)
        pose['dust'] = 1.0 if 0.6 < p < 0.95 else 0.0
        if anim == 'critdie':
            pose['flash'] = max(0.0, 0.5 - p * 2)
    elif anim == 'spawn':
        p = f / (n - 1)
        pose['sink'] = (1 - p) * (H + 1.5 * r)
        pose['dust'] = 1.0
        pose['mouth'] = 0.3 + 0.7 * p
    # coluna: do fundo do buraco até a cabeça (bezier), cabeça primeiro
    p0 = np.array([hole + F, sway, H])                            # cabeça
    if F > 3 * r:   # golpe/deitado: cabeça aponta para frente e para baixo
        p1 = np.array([hole + F * 0.7, sway * 0.6, H + 2.2 * r])
        p2 = np.array([hole + 0.6 * r, 0, H + 2.0 * r])
    else:
        p1 = np.array([hole + F * 0.55 - tilt * r, sway * 0.8, H + 0.2 * r - tilt * r * 1.2])
        p2 = np.array([hole, sway * 0.3, H * 0.45])
    p3 = np.array([hole, 0.0, -2.5 * r])
    curve = bezier(p0, p1, p2, p3)
    pts, s_end = resample(curve, sp)
    # coroa de espinhos de osso atrás da bocarra (silhueta de monstro de qualquer lado)
    if len(pts) > 6:
        hp = np.array(pts[0][1:4]); nxt = np.array(pts[4][1:4])
        T = (hp - nxt) / (np.linalg.norm(hp - nxt) + 1e-9)
        base_c = hp - T * r * 0.35
        helper = np.array([0, 0, 1.0]) if abs(T[2]) < 0.9 else np.array([1.0, 0, 0])
        u = np.cross(T, helper); u /= np.linalg.norm(u); v = np.cross(T, u)
        spikes = []
        for k in range(9):
            ang = k * 2 * math.pi / 9 + 0.2
            out = u * math.cos(ang) + v * math.sin(ang)
            for i in range(5):
                w = i / 4
                q = base_c + out * r * (0.8 + 1.1 * w) - T * r * 0.6 * w
                spikes.append((0.0, q[0], q[1], q[2], 4, r * (0.3 - 0.22 * w)))
        pts = pts + spikes
    # corcovas atrás (partes do corpo que furam o chão enquanto ele anda)
    for (ha, hw, ph) in pose['humps']:
        h = r * 2.6 * math.sin(math.pi * ph) - r * 0.4
        th = np.linspace(0, math.pi, 60)
        arc = np.stack([ha - hw * (1 - np.cos(th)) / 2, np.zeros_like(th), h * np.sin(th) - 0.9 * r], axis=1)
        more, s_end = resample(arc, sp, s_end + r * 4)
        pts += more
        pose['holes'] = pose['holes'] + [ha, ha - hw]
    if pose.get('sink'):
        pts = [tuple(p[:3]) + (p[3] - pose['sink'],) + tuple(p[4:]) for p in pts]
    pose['pts'] = pts
    return pose



def quad_pose(sp, anim, f, n):
    """Mula sem Cabeça: tronco, pescoço cortado soltando fogo, 4 patas e rabo.
    Pontos: (s, a, b, z, material, raio)."""
    r = sp['r']
    t = f / n
    B = 3.4 * r
    zt = 2.7 * r
    pose = dict(mouth=0.0, flash=0.0, dark=0.0, clip=None, eyes=False, dust=0.0)
    theta, fire_len, fire_fwd = 0.0, 1.0, 0.25
    legs = {}   # nome -> (desloc. do pé para frente, altura do pé)
    phases = {'fl': 0.0, 'fr': 0.15, 'bl': 0.5, 'br': 0.65}
    lie = 0.0
    bob = 0.0
    if anim in ('stance', 'block'):
        bob = 0.08 * r * math.sin(2 * math.pi * t)
    elif anim == 'run':
        for k, ph in phases.items():
            fi = 2 * math.pi * (t + ph)
            legs[k] = (0.8 * r * math.cos(fi), max(0.0, math.sin(fi)) * 1.0 * r)
        bob = 0.25 * r * math.sin(4 * math.pi * t)
        fire_fwd = 0.1
    elif anim == 'swing':
        theta = [34, 44, -4, 8][f]
        if f < 2:
            legs['fl'] = (0.9 * r, 1.6 * r); legs['fr'] = (0.6 * r, 1.2 * r)
        elif f == 2:
            legs['fl'] = (1.0 * r, 0.0); legs['fr'] = (1.1 * r, 0.0)
            pose['dust'] = 1.0
            pose['slam_a'] = 0.5 * B + 1.0 * r
        fire_len = [1.3, 1.5, 1.2, 1.0][f]
    elif anim in ('cast', 'shoot'):
        theta = [6, 14, 18, 14][f]
        fire_len = [1.4, 2.1, 2.8, 2.2][f]
        fire_fwd = 0.7
    elif anim == 'hit':
        theta = -6
        pose['flash'] = [0.55, 0.25][f]
    elif anim in ('die', 'critdie'):
        p = f / (n - 1)
        lie = p
        fire_len = max(0.0, 1 - 1.4 * p)
        pose['dark'] = 0.45 * p
        if anim == 'critdie':
            pose['flash'] = max(0.0, 0.5 - p * 2)
    elif anim == 'spawn':
        p = f / (n - 1)
        pose['clip'] = 0.0
        pose['sink'] = (1 - p) * (zt + 2.5 * r)
        fire_len = 1.0 + 1.5 * (1 - p)
        pose['dust'] = 1 - p

    ztt = zt * (1 - lie) + 0.95 * r * lie + bob
    pa, pz = -0.4 * B, ztt
    ct, st = math.cos(math.radians(theta)), math.sin(math.radians(theta))

    def rot(a, z):
        da, dz = a - pa, z - pz
        return pa + da * ct - dz * st, pz + da * st + dz * ct

    pts = []
    sc = [0.0]

    def add(a, b, z, mat, rad, pitched=True):
        if pitched:
            a, z = rot(a, z)
        sc[0] += 1
        pts.append((sc[0], a, b, z, mat, rad))

    # tronco de equino: mais fundo que largo (linha do dorso + linha da barriga),
    # cernelha alta, lombo levemente baixo, anca redonda, barriga recolhida no flanco
    for i in range(16):
        u = i / 15 - 0.5                      # -0.5 = anca, +0.5 = peito
        back = 0.28 * r + 0.18 * r * math.exp(-((u - 0.38) / 0.1) ** 2) \
            + 0.14 * r * math.exp(-((u + 0.36) / 0.12) ** 2) - 0.06 * r * math.exp(-(u / 0.15) ** 2)
        rt = r * (0.6 + 0.12 * math.exp(-((u + 0.38) / 0.14) ** 2) + 0.08 * math.exp(-((u - 0.4) / 0.12) ** 2))
        add(u * B, 0.0, ztt + back, 0, rt)
        belly = 0.62 * r * (1 - 0.45 * max(0.0, (-u - 0.15) / 0.35))   # barriga sobe no flanco
        add(u * B, 0.0, ztt - 0.38 * r, 0, belly * (0.7 if abs(u) > 0.42 else 1.0))
    for sgn in (-1, 1):   # músculos da anca
        add(-0.4 * B, sgn * 0.22 * r, ztt + 0.1 * r, 0, 0.6 * r)
    add(0.47 * B, 0.0, ztt - 0.12 * r, 0, 0.62 * r)   # peito
    # pescoço arqueado e grosso na base, sem cabeça
    neck = []
    for i in range(10):
        u = i / 9
        a = 0.4 * B + u * 0.34 * B
        z = ztt + 0.35 * r + u * 1.75 * r + 0.25 * r * math.sin(math.pi * u)
        add(a, 0.0, z, 0, r * (0.58 - 0.22 * u))
        add(a - 0.12 * r, 0.0, z - 0.3 * r * (1 - u), 0, r * (0.5 - 0.2 * u))
        neck.append((a, z, r * (0.58 - 0.22 * u)))
    n0 = np.array([neck[-3][0], neck[-3][1]]); n1 = np.array([neck[-1][0], neck[-1][1]])
    add(n1[0], 0.0, n1[1] + 0.05 * r, 1, r * 0.4)
    # crina de fogo ao longo do pescoço
    if fire_len > 0.05:
        for i, (a, z, rr) in enumerate(neck[1:-1]):
            h = (0.35 + 0.25 * math.sin(2 * math.pi * (t * 2 + i * 0.37))) * r * min(fire_len, 1.3)
            add(a - 0.25 * r, 0.0, z + rr * 0.8 + h * 0.5, 1, r * 0.16 + h * 0.25)
    # a labareda do toco: base larga, várias línguas, fagulhas
    d = (n1 - n0) / np.linalg.norm(n1 - n0)
    fdir = np.array([d[0] * (0.2 + fire_fwd), 1.0 - fire_fwd * 0.6]); fdir /= np.linalg.norm(fdir)
    if fire_len > 0.05:
        nf = 12
        for i in range(nf):
            u = i / (nf - 1)
            q = n1 + fdir * (0.15 + u * 2.9 * fire_len) * r
            wob = 2 * math.pi * (t * 2 + u * 1.3)
            jit = 0.5 * r * u * math.sin(wob)
            jit_a = 0.35 * r * u * math.sin(wob * 1.4 + 1.0)
            add(q[0] + jit_a, jit, q[1], 1, r * (0.8 - 0.66 * u) * (0.6 + 0.4 * min(fire_len, 1.5)))
            if 0.15 < u < 0.85:   # línguas soltas
                for k, sgn in enumerate((-1, 1)):
                    ph = math.sin(wob * (1.7 + k * 0.6) + k * 2.1)
                    add(q[0] - jit_a + sgn * 0.3 * r * ph, sgn * 0.45 * r * (0.5 + 0.5 * ph), q[1] + 0.25 * r,
                        1, r * 0.22 * (1 - u))
    # patas: finas (canela), com joelho na frente e jarrete atrás, boleto e casco
    for k, (ah, bs, front) in {'fl': (0.38 * B, 0.34, True), 'fr': (0.38 * B, -0.34, True),
                                'bl': (-0.36 * B, 0.36, False), 'br': (-0.36 * B, -0.36, False)}.items():
        da, lift = legs.get(k, (0.0, 0.0))
        hip_a, hip_z = ah, ztt - 0.3 * r
        if front:
            hip_a, hip_z = rot(hip_a, hip_z)
        foot = np.array([hip_a + da, 0.2 * r + lift])
        b = bs * r
        if lie:
            foot = foot * (1 - lie) + np.array([hip_a + 1.1 * r * (1 if front else -1), 0.2 * r]) * lie
            b = bs * r + 1.6 * r * lie
        hip = np.array([hip_a, hip_z])
        # joelho (frente) ~45% da altura; jarrete (trás) mais alto e para trás
        kh = 0.45 if front else 0.55
        knee = hip + (foot - hip) * (1 - kh) + np.array([(0.12 if front else -0.42) * r + (0.35 * lift if front else -0.2 * lift), 0])
        seg = [(hip, knee, (0.36 if front else 0.44), 0.2, 7), (knee, foot + np.array([0, 0.18 * r]), 0.15, 0.13, 7)]
        for (p, q, r0, r1, m) in seg:
            for i in range(m):
                w = i / (m - 1)
                pp = p + (q - p) * w
                add(pp[0], bs * r + (b - bs * r) * (0.5 * w if p is hip else 0.5 + 0.5 * w), pp[1], 0,
                    r * (r0 + (r1 - r0) * w), pitched=False)
        add(foot[0] + 0.03 * r, b, foot[1] + 0.2 * r, 0, r * 0.17, pitched=False)   # boleto
        add(foot[0] + 0.06 * r, b, foot[1], 2, r * 0.2, pitched=False)             # casco (ferradura)
    # rabo comprido de crina
    for i in range(13):
        u = i / 12
        sway = 0.4 * r * math.sin(2 * math.pi * t + u * 2.2)
        add(-0.53 * B - u * 0.9 * r - 0.5 * r * u * u, sway * u, ztt + 0.45 * r - u * 2.3 * r, 3, r * (0.2 - 0.08 * u))
    if pose.get('sink'):
        pts = [(s_, a, b, z - pose['sink'], m, rr) for s_, a, b, z, m, rr in pts]
    pose['pts'] = pts
    if pose['dust']:
        pose['holes'] = []
    return pose


def biped_pose(sp, anim, f, n):
    """Saci-Pererê (uma perna, gorro vermelho, cachimbo, redemoinho) e Curupira
    (cabelo de fogo, pés virados para trás, saia de folhas, porrete).
    Pontos: (s, a, b, z, material, raio); a = para frente, b = para o lado."""
    u = sp['r']
    kind = sp['kind']
    saci = kind == 'saci'
    t = f / n
    pose = dict(mouth=0.0, flash=0.0, dark=0.0, clip=None, eyes=False, dust=0.0)
    lift = 0.0            # pulo (Saci)
    crouch = 0.0          # agachar antes/depois do pulo
    lean = 0.0            # tronco para frente (+) / trás (-), graus
    fall = 0.0            # morte: 0..1 caindo de costas
    spin = 0.0            # giro no próprio eixo (redemoinho), graus
    swirl = 0.0           # redemoinho / folhas em volta, 0..1
    fire_k = 1.0          # tamanho do cabelo de fogo
    legs = {'l': (0.0, 0.0), 'r': (0.0, 0.0)}      # (pé para frente, altura do pé)
    arms = {'l': (0.0, 0.0), 'r': (0.0, 0.0)}      # (mão para frente, mão para cima), em u
    kick = 0.0
    club = 0.0            # porrete: 0 baixo, 1 erguido, -1 golpe
    if anim in ('stance', 'block'):
        if saci:
            lift = 0.25 * u * abs(math.sin(math.pi * t * 2))
            crouch = 0.3 * (1 - abs(math.sin(math.pi * t * 2)))
        arms['l'] = (0.2, 0.15 * math.sin(2 * math.pi * t))
        arms['r'] = (0.2, -0.15 * math.sin(2 * math.pi * t))
    elif anim == 'run':
        if saci:
            ph = math.sin(2 * math.pi * t)
            lift = 1.1 * u * max(0.0, ph)
            crouch = 0.6 * max(0.0, -ph)
            lean = 12
            arms['l'] = (0.5 + 0.4 * ph, 0.6 * max(0.0, ph))
            arms['r'] = (0.5 + 0.4 * ph, 0.6 * max(0.0, ph))
        else:
            ph = 2 * math.pi * t
            legs['l'] = (1.1 * u * math.sin(ph), 0.6 * u * max(0.0, math.cos(ph)))
            legs['r'] = (1.1 * u * math.sin(ph + math.pi), 0.6 * u * max(0.0, math.cos(ph + math.pi)))
            arms['l'] = (-0.8 * math.sin(ph), 0.0)
            arms['r'] = (-0.8 * math.sin(ph + math.pi), 0.0)
            lift = 0.15 * u * abs(math.cos(ph))
            lean = 10
    elif anim == 'swing':
        if saci:   # coice com a única perna
            kick = [-0.8, -0.3, 1.0, 0.3][f]
            lift = [0.3, 0.9, 0.7, 0.2][f] * u
            lean = [-10, -15, -20, 0][f]
            arms['l'] = ([-0.5, -0.6, 0.9, 0.3][f], 0.4)
            arms['r'] = ([-0.5, -0.6, 0.9, 0.3][f], 0.4)
        else:      # porrete de cima para baixo
            club = [1.0, 1.2, -1.0, -0.4][f]
            lean = [-10, -14, 20, 8][f]
            legs['l'] = (0.8 * u, 0.0)
            legs['r'] = (-0.6 * u, 0.0)
        pose['dust'] = 1.0 if f == 2 else 0.0
    elif anim in ('cast', 'shoot'):
        swirl = [0.4, 0.8, 1.0, 0.9][f]
        if saci:
            spin = f * 90.0
            lift = [0.2, 0.6, 1.0, 0.8][f] * u
            arms['l'] = (0.0, 1.2); arms['r'] = (0.0, 1.2)
        else:
            fire_k = [1.3, 1.8, 2.3, 2.0][f]
            arms['l'] = (0.4, 2.0); arms['r'] = (0.4, 2.0)
            club = 1.3
            lean = -8
    elif anim == 'hit':
        lean = -18
        pose['flash'] = [0.55, 0.25][f]
    elif anim in ('die', 'critdie'):
        p = f / (n - 1)
        fall = smooth(p * 1.2)
        pose['dark'] = 0.45 * p
        fire_k = max(0.0, 1 - 1.3 * p)
        swirl = (1 - p) * 0.6 if saci else 0.0
        arms['l'] = (0.3, 1.0 * p); arms['r'] = (0.3, 1.0 * p)
        if anim == 'critdie':
            pose['flash'] = max(0.0, 0.5 - p * 2)
    elif anim == 'spawn':
        p = f / (n - 1)
        swirl = 1.0 - 0.6 * p
        pose['clip'] = 0.0
        pose['sink'] = (1 - p) * 8.5 * u
        pose['dust'] = 1 - p

    pts = []
    sc = [0.0]
    ang_spin = math.radians(spin)
    ang_lean = math.radians(lean)

    def xf(a, b, z, pitched=True):
        # inclinação do tronco em volta do quadril, giro, queda de costas nos pés
        if pitched:
            pz = hip_z
            da, dz = a, z - pz
            a, z = da * math.cos(ang_lean) + dz * math.sin(ang_lean), pz - da * math.sin(ang_lean) + dz * math.cos(ang_lean)
        if spin:
            a, b = a * math.cos(ang_spin) - b * math.sin(ang_spin), a * math.sin(ang_spin) + b * math.cos(ang_spin)
        if fall:
            fa = math.radians(-82 * fall)
            a, z = a * math.cos(fa) - z * math.sin(fa), a * math.sin(fa) + z * math.cos(fa)
            z = max(z, 0.35 * u)
        return a, b, z + lift

    def add(a, b, z, mat, rad, pitched=True):
        a, b, z = xf(a, b, z, pitched)
        sc[0] += 1
        pts.append((sc[0], a, b, z, mat, rad))

    def seg(p0, p1, r0, r1, mat, pitched=True):
        p0, p1 = np.array(p0, float), np.array(p1, float)
        L = np.linalg.norm(p1 - p0)
        k = max(2, int(L / (min(r0, r1) * 0.55)) + 1)
        for i in range(k):
            w = i / (k - 1)
            q = p0 + (p1 - p0) * w
            add(q[0], q[1], q[2], mat, r0 + (r1 - r0) * w, pitched)

    def joint(p0, p1, length, bend_dir):
        """cotovelo/joelho: ponto do meio empurrado para bend_dir (vetor unitário)"""
        p0, p1 = np.array(p0, float), np.array(p1, float)
        d = np.linalg.norm(p1 - p0)
        h = math.sqrt(max(0.0, (length / 2) ** 2 - (d / 2) ** 2))
        return (p0 + p1) / 2 + np.array(bend_dir) * h

    leg_len = 3.0 * u
    hip_z = (3.3 - 0.9 * crouch) * u
    # ---- pernas
    if saci:
        foot = np.array([kick * 1.6 * u, 0.0, 0.35 * u + max(0.0, kick) * 1.2 * u])
        hip = np.array([0.0, 0.0, hip_z])
        knee = joint(hip, foot, leg_len, (1, 0, 0) if kick >= 0 else (0.7, 0, 0.3))
        seg(hip, knee, 0.5 * u, 0.36 * u, 0, pitched=False)
        seg(knee, foot, 0.36 * u, 0.3 * u, 0, pitched=False)
        seg(foot, foot + np.array([0.55 * u, 0, -0.05 * u]), 0.36 * u, 0.3 * u, 0, pitched=False)
    else:
        for side, sgn in (('l', 1), ('r', -1)):
            da, fh = legs[side]
            if fall:
                da, fh = 0.4 * u, 0.0
            hip = np.array([0.0, sgn * 0.55 * u, hip_z])
            ankle = np.array([da, sgn * 0.6 * u, 0.4 * u + fh])
            knee = joint(hip, ankle, leg_len, (1, 0, 0))
            seg(hip, knee, 0.46 * u, 0.36 * u, 0, pitched=False)
            seg(knee, ankle, 0.36 * u, 0.28 * u, 0, pitched=False)
            # pés virados para trás: o pé aponta para -a
            seg(ankle, ankle + np.array([-0.75 * u, 0, -0.12 * u]), 0.34 * u, 0.3 * u, 0, pitched=False)
            for toe in (-0.18, 0.0, 0.18):
                add(ankle[0] - 0.95 * u, ankle[1] + toe * u, ankle[2] - 0.15 * u, 0, 0.14 * u, pitched=False)
    # ---- quadril, roupa, tronco
    if saci:
        add(0.0, 0.0, hip_z + 0.2 * u, 2, 0.95 * u)                  # calção
        add(0.0, 0.35 * u, hip_z + 0.1 * u, 2, 0.6 * u)
        add(0.0, -0.35 * u, hip_z + 0.1 * u, 2, 0.6 * u)
    else:
        add(0.0, 0.0, hip_z + 0.2 * u, 0, 0.9 * u)
        # saia de folhas
        for k in range(12):
            ang = k * 2 * math.pi / 12
            for w in (0.0, 1.0):
                add(math.cos(ang) * (0.85 + 0.25 * w) * u, math.sin(ang) * (0.85 + 0.25 * w) * u,
                    hip_z + (0.15 - 0.75 * w) * u, 2, (0.34 - 0.08 * w) * u)
    seg((0, 0, hip_z + 0.5 * u), (0.05 * u, 0, hip_z + 1.7 * u), 0.9 * u, 1.0 * u, 0)
    chest = np.array([0.08 * u, 0.0, hip_z + 1.75 * u])
    # ---- braços
    for side, sgn in (('l', 1), ('r', -1)):
        fa, up = arms[side]
        sh = chest + np.array([0.0, sgn * 1.05 * u, 0.2 * u])
        hand = sh + np.array([fa * u + 0.2 * u, sgn * 0.35 * u, -2.2 * u + up * 1.9 * u])
        if not saci and side == 'r' and club:
            if club > 0:
                hand = sh + np.array([-0.2 * u, sgn * 0.3 * u, 1.4 * u * club])
            else:
                hand = sh + np.array([1.9 * u, sgn * 0.2 * u, -0.4 * u])
        elbow = joint(sh, hand, 2.4 * u, (-0.6, sgn * 0.5, -0.3))
        seg(sh, elbow, 0.36 * u, 0.3 * u, 0)
        seg(elbow, hand, 0.3 * u, 0.26 * u, 0)
        add(hand[0], hand[1], hand[2], 0, 0.34 * u)
        if not saci and side == 'r':
            # porrete de galho, na direção do antebraço
            dirv = hand - elbow
            dirv /= (np.linalg.norm(dirv) + 1e-9)
            seg(hand - dirv * 0.3 * u, hand + dirv * 2.6 * u, 0.2 * u, 0.42 * u, 3)
    # ---- cabeça
    head = chest + np.array([0.1 * u, 0.0, 1.55 * u])
    add(chest[0], 0.0, chest[2] + 0.55 * u, 0, 0.45 * u)          # pescoço
    add(head[0], head[1], head[2], 0, 1.12 * u)
    for sgn in (1, -1):                                            # olhos brilhando
        add(head[0] + 0.95 * u, sgn * 0.38 * u, head[2] + 0.12 * u, 4, 0.2 * u)
    if saci:
        # gorro vermelho: cone mole que cai para trás
        base = head + np.array([-0.1 * u, 0, 0.75 * u])
        for i in range(12):
            w = i / 11
            flop = math.sin(2 * math.pi * t) * 0.15 * u * w
            q = base + np.array([-1.5 * u * w * w - 0.2 * u * w, flop, 1.3 * u * w - 1.0 * u * w * w * w])
            add(q[0], q[1], q[2], 1, (0.95 - 0.8 * w) * u)
        add(base[0] - 1.9 * u, 0.0, base[2] + 0.1 * u, 1, 0.22 * u)  # pompom
        # cachimbo
        m = head + np.array([0.95 * u, -0.2 * u, -0.45 * u])
        seg(m, m + np.array([0.7 * u, -0.15 * u, -0.1 * u]), 0.1 * u, 0.1 * u, 3)
        bowl = m + np.array([0.85 * u, -0.15 * u, 0.05 * u])
        add(bowl[0], bowl[1], bowl[2], 3, 0.22 * u)
        if fall < 0.5:
            for i in range(4):   # fumaça
                w = ((t * 2 + i / 4) % 1.0)
                add(bowl[0] + 0.3 * u + 0.2 * u * w, bowl[1] - 0.4 * u + 0.3 * u * math.sin(6 * w + i),
                    bowl[2] + (0.9 + 2.4 * w) * u, 5, (0.12 + 0.24 * w) * u)
    else:
        # cabelo de fogo: labaredas saindo do alto e de trás da cabeça
        if fire_k > 0.05:
            for k in range(7):
                ang = -math.pi * 0.9 + k * (math.pi * 1.8 / 6)
                root = head + np.array([-0.35 * u + 0.3 * u * math.cos(ang) * 0.3, 0.8 * u * math.sin(ang), 0.75 * u])
                L = (1.3 + 0.5 * math.sin(2 * math.pi * (t * 2 + k * 0.29))) * u * fire_k
                for i in range(6):
                    w = i / 5
                    wob = 0.3 * u * w * math.sin(2 * math.pi * (t * 3 + k * 0.4 + w))
                    add(root[0] - 0.6 * L * w, root[1] + wob, root[2] + L * w, 1, (0.46 - 0.34 * w) * u)
    # ---- redemoinho (Saci) / folhas girando (Curupira)
    if swirl > 0.05:
        N = 26
        for k in range(N):
            w = k / (N - 1)
            ang = k * 0.85 + t * 2 * math.pi * 1.5
            rad = (1.4 + 1.6 * w) * u * (0.7 + 0.3 * swirl)
            z = w * 8.0 * u * swirl
            mat, rr = (6, (0.28 + 0.2 * w) * u) if saci else (2, 0.3 * u)
            sc[0] += 1
            pts.append((sc[0], math.cos(ang) * rad, math.sin(ang) * rad, z + 0.2 * u, mat, rr))
    if pose.get('sink'):
        pts = [tuple(p[:3]) + (p[3] - pose['sink'],) + tuple(p[4:]) for p in pts]
    pose['pts'] = pts
    return pose


def beast_pose(sp, anim, f, n):
    """Feras em pé: Lobisomem (cabeça de lobo, corcunda, garras), Mapinguari (um olho,
    boca na barriga, pés virados), Cuca (cabeça de jacaré, cabelo loiro, vestido) e
    Bicho-Papão (capa escura, capuz com olhos, dentes e braços compridos).
    Materiais: 0 pelo/pele, 1 segundo tom (focinho, cabelo, boca), 2 garras/dentes,
    3 roupa, 4 olhos (brilho), 5 fundo da boca, 6 magia (fogo colorido)."""
    u = sp['r']
    kind = sp['kind']
    t = f / n
    pose = dict(mouth=0.0, flash=0.0, dark=0.0, clip=None, eyes=False, dust=0.0)
    hunch = sp.get('hunch', 18)
    lean, fall, lift, jaw, head_up, magic = 0.0, 0.0, 0.0, 0.1, 0.0, 0.0
    legs = {'l': (0.0, 0.0), 'r': (0.0, 0.0)}
    arms = {'l': (0.3, 0.0), 'r': (0.3, 0.0)}          # (mão para frente, mão para cima)
    breath = math.sin(2 * math.pi * t)
    if anim in ('stance', 'block'):
        arms['l'] = (0.4 + 0.1 * breath, 0.1 * breath)
        arms['r'] = (0.4 - 0.1 * breath, -0.1 * breath)
        lean = 2 * breath
        jaw = 0.12 + 0.08 * max(0.0, breath)
        if anim == 'block':
            arms['l'] = arms['r'] = (1.2, 1.3)
    elif anim == 'run':
        ph = 2 * math.pi * t
        legs['l'] = (1.2 * u * math.sin(ph), 0.7 * u * max(0.0, math.cos(ph)))
        legs['r'] = (1.2 * u * math.sin(ph + math.pi), 0.7 * u * max(0.0, math.cos(ph + math.pi)))
        arms['l'] = (-0.9 * math.sin(ph) + 0.4, 0.2)
        arms['r'] = (-0.9 * math.sin(ph + math.pi) + 0.4, 0.2)
        lift = 0.2 * u * abs(math.cos(ph))
        lean = 14
        jaw = 0.3
    elif anim == 'swing':   # garrada: um braço atrás e alto, depois rasga para frente e para baixo
        k = [(-0.6, 1.9), (-0.9, 2.3), (2.2, 0.2), (1.2, -0.2)][f]
        arms['r'] = k
        arms['l'] = ([0.8, 0.9, -0.3, 0.2][f], 0.4)
        lean = [-8, -12, 24, 12][f]
        legs['l'] = (0.9 * u, 0.0); legs['r'] = (-0.7 * u, 0.0)
        jaw = [0.5, 0.8, 1.0, 0.5][f]
        pose['dust'] = 1.0 if f == 2 else 0.0
    elif anim in ('cast', 'shoot'):   # uivo / feitiço: cabeça para cima, braços abertos
        head_up = [15, 35, 45, 35][f]
        arms['l'] = arms['r'] = (0.6, [1.2, 2.0, 2.3, 2.0][f])
        lean = -[5, 12, 16, 12][f]
        jaw = [0.5, 1.0, 1.0, 0.8][f]
        magic = [0.5, 0.9, 1.2, 1.0][f]
    elif anim == 'hit':
        lean = -20
        jaw = 0.8
        pose['flash'] = [0.55, 0.25][f]
    elif anim in ('die', 'critdie'):
        p = f / (n - 1)
        fall = smooth(p * 1.2)
        pose['dark'] = 0.45 * p
        jaw = 0.9
        arms['l'] = (0.3, 1.0 * p); arms['r'] = (0.3, 1.0 * p)
        if anim == 'critdie':
            pose['flash'] = max(0.0, 0.5 - p * 2)
    elif anim == 'spawn':
        p = f / (n - 1)
        pose['clip'] = 0.0
        pose['sink'] = (1 - p) * 10.0 * u
        pose['dust'] = 1 - p
        arms['l'] = arms['r'] = (0.6, 1.5 * (1 - p))
    if kind == 'papao':
        legs = {'l': (0.0, 0.0), 'r': (0.0, 0.0)}   # flutua dentro da capa
        lift += 0.35 * u * (1 + math.sin(2 * math.pi * t))

    pts = []
    sc = [0.0]
    hip_z = sp.get('hip', 3.4) * u
    ang_lean = math.radians(lean + hunch)

    def xf(a, b, z, pitched=True):
        if pitched:
            da, dz = a, z - hip_z
            a, z = da * math.cos(ang_lean) + dz * math.sin(ang_lean), hip_z - da * math.sin(ang_lean) + dz * math.cos(ang_lean)
        if fall:
            fa = math.radians(-82 * fall)
            a, z = a * math.cos(fa) - z * math.sin(fa), a * math.sin(fa) + z * math.cos(fa)
            z = max(z, 0.35 * u)
        return a, b, z + lift

    def add(a, b, z, mat, rad, pitched=True):
        a, b, z = xf(a, b, z, pitched)
        sc[0] += 1
        pts.append((sc[0], a, b, z, mat, rad))

    def seg(p0, p1, r0, r1, mat, pitched=True):
        p0, p1 = np.array(p0, float), np.array(p1, float)
        L = np.linalg.norm(p1 - p0)
        k = max(2, int(L / (max(0.05 * u, min(r0, r1)) * 0.55)) + 1)
        for i in range(k):
            w = i / (k - 1)
            q = p0 + (p1 - p0) * w
            add(q[0], q[1], q[2], mat, r0 + (r1 - r0) * w, pitched)

    def joint(p0, p1, length, bend_dir):
        p0, p1 = np.array(p0, float), np.array(p1, float)
        d = np.linalg.norm(p1 - p0)
        h = math.sqrt(max(0.0, (length / 2) ** 2 - (d / 2) ** 2))
        return (p0 + p1) / 2 + np.array(bend_dir) * h

    bulk = sp.get('bulk', 1.0)
    leg_len = hip_z * 0.95
    # ---- pernas
    if kind != 'papao':
        for side, sgn in (('l', 1), ('r', -1)):
            da, fh = legs[side]
            if fall:
                da, fh = 0.4 * u, 0.0
            hip = np.array([0.0, sgn * 0.7 * u * bulk, hip_z])
            ankle = np.array([da - (0.3 * u if kind == 'lobisomem' else 0.0), sgn * 0.75 * u * bulk, (0.9 if kind == 'lobisomem' else 0.4) * u + fh])
            knee = joint(hip, ankle, leg_len, (1, 0, 0))
            seg(hip, knee, 0.62 * u * bulk, 0.45 * u * bulk, 0, pitched=False)
            seg(knee, ankle, 0.45 * u * bulk, 0.3 * u * bulk, 0, pitched=False)
            back = -1.0 if kind == 'mapinguari' else 1.0     # Mapinguari: pés virados para trás
            if kind == 'lobisomem':   # pata de lobo: calcanhar alto, dedos no chão
                seg(ankle, ankle + np.array([0.5 * u, 0, -0.55 * u]), 0.3 * u, 0.3 * u, 0, pitched=False)
                paw = ankle + np.array([0.7 * u, 0, -0.55 * u])
            else:
                paw = ankle + np.array([back * 0.8 * u, 0, -0.1 * u])
                seg(ankle, paw, 0.38 * u * bulk, 0.34 * u * bulk, 0, pitched=False)
            for toe in (-0.25, 0.0, 0.25):
                add(paw[0] + back * 0.35 * u, paw[1] + toe * u, paw[2] - 0.05 * u, 2, 0.12 * u, pitched=False)
    # ---- quadril e roupa
    add(0.0, 0.0, hip_z + 0.2 * u, 0 if kind in ('lobisomem', 'mapinguari') else 3, 1.1 * u * bulk)
    if kind == 'lobisomem':   # calça rasgada
        for sgn in (1, -1):
            add(0.1 * u, sgn * 0.7 * u, hip_z - 0.3 * u, 3, 0.66 * u)
            for k in range(3):
                add(0.1 * u + (k - 1) * 0.35 * u, sgn * 0.75 * u, hip_z - 1.0 * u - 0.25 * u * (k % 2), 3, 0.42 * u)
    if kind in ('cuca', 'papao'):   # vestido / capa até o chão
        top, bot = hip_z + 1.2 * u, (1.5 if kind == 'cuca' else 1.1) * u
        rows = 13
        for j in range(rows):
            w = j / (rows - 1)
            z = top + (bot - top) * w
            rad_ring = (0.75 + (0.75 if kind == 'cuca' else 0.95) * w) * u * bulk
            nring = 12 + 2 * j
            for k in range(nring):
                ang = k * 2 * math.pi / nring
                flut = 0.15 * u * w * math.sin(2 * math.pi * t + ang * 3) if kind == 'papao' else 0.0
                flut += 0.22 * u * w * max(0.0, math.sin(ang * 7 + 0.6))      # dobras do pano
                add(math.cos(ang) * (rad_ring + flut) - 0.2 * u * w, math.sin(ang) * (rad_ring + flut),
                    z - (0.25 * u * (1 + math.sin(ang * 5 + j)) * w if kind == 'papao' else 0.0), 3,
                    (0.62 + 0.12 * w) * u * bulk)
        # barra rasgada: tiras pontudas penduradas
        ntat = 16
        for k in range(ntat):
            ang = k * 2 * math.pi / ntat + 0.2
            rr = rad_ring * 1.02
            ln = (0.7 + 0.6 * ((k * 7) % 5) / 4) * u * (2.2 if kind == 'papao' else 1.1)
            sway = 0.2 * u * math.sin(2 * math.pi * t + k)
            p0 = np.array([math.cos(ang) * rr - 0.2 * u, math.sin(ang) * rr, bot + 0.5 * u])
            seg(p0, p0 + np.array([0.3 * u * math.cos(ang) + sway, 0.3 * u * math.sin(ang), -ln]), 0.34 * u, 0.05 * u, 3)
        if kind == 'cuca':   # cinto de corda com amuletos
            for k in range(18):
                ang = k * 2 * math.pi / 18
                add(math.cos(ang) * 0.95 * u * bulk, math.sin(ang) * 0.95 * u * bulk, top - 0.4 * u, 5, 0.22 * u)
            for k, off in enumerate((-0.5, 0.1, 0.6)):
                q = np.array([0.95 * u, off * u, top - 0.9 * u - 0.2 * u * k])
                add(q[0], q[1], q[2], 2, 0.2 * u)
    # ---- tronco (peito largo, barriga)
    body_m = 3 if kind == 'papao' else 0
    seg((0, 0, hip_z + 0.5 * u), (0.1 * u, 0, hip_z + 2.0 * u), 1.05 * u * bulk, 1.3 * u * bulk, body_m)
    chest = np.array([0.15 * u, 0.0, hip_z + 2.2 * u * (1 if kind != 'mapinguari' else 1.05)])
    for sgn in (1, -1):
        add(chest[0], sgn * 0.75 * u * bulk, chest[2], body_m, 1.0 * u * bulk)
    if kind == 'lobisomem':   # juba no pescoço e ombros, em tufos
        for k in range(14):
            ang = -math.pi * 0.95 + k * (math.pi * 1.9 / 13)
            rr = 1.25 * u
            base = chest + np.array([-0.4 * u + 0.4 * u * math.cos(ang) * 0.2, rr * math.sin(ang), 0.55 * u + 0.2 * u * math.cos(ang)])
            tuft = np.array([-0.55 * u, 0.25 * u * math.sin(ang), 0.55 * u])
            seg(base, base + tuft, 0.42 * u, 0.12 * u, 0)
    if kind == 'mapinguari':   # boca na barriga, com dentes
        mz = hip_z + 1.15 * u
        mo = 0.35 + 0.65 * jaw
        fa = 1.2 * u * bulk
        for k in range(-3, 4):
            w = k / 3
            add(fa, w * 0.8 * u, mz, 5, (0.28 + 0.12 * mo * (1 - abs(w))) * u)
        for k in range(-3, 4):
            w = k / 3
            for sgn in (1, -1):
                add(fa + 0.1 * u, w * 0.8 * u, mz + sgn * (0.2 + 0.25 * mo * (1 - w * w)) * u, 1, 0.2 * u)
                if abs(k) < 3:
                    add(fa + 0.2 * u, w * 0.8 * u, mz + sgn * (0.08 + 0.18 * mo * (1 - w * w)) * u, 2, 0.11 * u)
    # ---- braços com garras
    arm_len = sp.get('arm', 2.8) * u
    for side, sgn in (('l', 1), ('r', -1)):
        fa_, up = arms[side]
        sh = chest + np.array([0.0, sgn * 1.45 * u * bulk, 0.3 * u])
        hand = sh + np.array([fa_ * u + 0.3 * u, sgn * 0.4 * u, -arm_len * 0.85 + up * 1.9 * u])
        elbow = joint(sh, hand, arm_len, (-0.6, sgn * 0.5, -0.3))
        am = 3 if kind == 'papao' else 0
        seg(sh, elbow, 0.55 * u * bulk, 0.42 * u * bulk, am)
        seg(elbow, hand, 0.42 * u * bulk, 0.33 * u * bulk, am if kind != 'papao' else 0)
        add(hand[0], hand[1], hand[2], 0 if kind != 'cuca' else 0, 0.42 * u * bulk)
        dirv = hand - elbow
        dirv /= (np.linalg.norm(dirv) + 1e-9)
        for c in (-0.28, 0.0, 0.28):
            tip = hand + dirv * 0.85 * u + np.array([0.25 * u, sgn * c * u, -0.2 * u])
            seg(hand + np.array([0, sgn * c * u, 0]), tip, 0.13 * u, 0.04 * u, 2)
        if magic > 0 and kind in ('cuca', 'papao'):
            for i in range(6):
                w = i / 5
                wob = 0.25 * u * math.sin(2 * math.pi * (t * 3 + w + (0.5 if sgn > 0 else 0)))
                add(hand[0] + wob, hand[1], hand[2] + 0.3 * u + 1.4 * u * w * magic, 6, (0.5 - 0.35 * w) * u * magic)
    # ---- detalhes que quebram a silhueta redonda
    def tuft(p, d, ln, r0, mat):
        d = np.array(d, float); d /= np.linalg.norm(d)
        seg(p, np.array(p, float) + d * ln, r0, 0.05 * u, mat)
    back_a = -1.05 * u * bulk
    if kind in ('lobisomem', 'mapinguari'):
        # crista de pelo arrepiado no dorso
        for k in range(7):
            w = k / 6
            z = hip_z + (0.6 + 1.9 * w) * u
            tuft((back_a * (0.9 + 0.2 * w), 0.25 * u * math.sin(k * 2.1), z), (-0.8, 0.3 * math.sin(k * 1.7), 0.7 - 0.3 * w),
                 (0.7 + 0.3 * (k % 2)) * u, 0.4 * u, 0)
        # peito: dois peitorais e costelas marcadas
        for sgn in (1, -1):
            add(chest[0] + 0.75 * u * bulk, sgn * 0.5 * u, chest[2] - 0.25 * u, 1 if kind == 'lobisomem' else 0, 0.62 * u * bulk)
        for k in range(3):
            for sgn in (1, -1):
                add(1.02 * u * bulk, sgn * (0.55 + 0.08 * k) * u, hip_z + (1.35 - 0.3 * k) * u, 0, 0.26 * u)
        # tufos nos cotovelos e nas coxas
        for side, sgn in (('l', 1), ('r', -1)):
            sh = chest + np.array([0.0, sgn * 1.45 * u * bulk, 0.3 * u])
            tuft(sh + np.array([-0.3 * u, sgn * 0.4 * u, -1.0 * u]), (-0.6, sgn * 0.6, -0.3), 0.8 * u, 0.3 * u, 0)
            tuft(sh + np.array([-0.2 * u, sgn * 0.3 * u, 0.3 * u]), (-0.4, sgn * 0.7, 0.5), 0.9 * u, 0.36 * u, 0)
        for sgn in (1, -1):
            tuft((back_a * 0.6, sgn * 0.9 * u * bulk, hip_z - 0.3 * u), (-0.6, sgn * 0.5, -0.5), 0.8 * u, 0.3 * u, 0)
    if kind == 'lobisomem':   # rabo peludo
        for i in range(9):
            w = i / 8
            sway = 0.5 * u * w * math.sin(2 * math.pi * t + w * 2)
            add(back_a - (0.3 + 1.8 * w) * u, sway, hip_z + 0.2 * u - 1.6 * u * w * w, 0 if i < 7 else 1, (0.45 + 0.25 * math.sin(math.pi * w)) * u)
    if kind == 'mapinguari':   # pelo comprido pendurado pelo corpo todo + placas de osso nos ombros
        for k in range(20):
            ang = k * 2 * math.pi / 20
            z = hip_z + (0.4 + 1.5 * ((k * 3) % 4) / 3) * u
            rr = 1.2 * u * bulk
            tuft((math.cos(ang) * rr, math.sin(ang) * rr, z), (math.cos(ang) * 0.4, math.sin(ang) * 0.4, -1.0), 0.9 * u, 0.32 * u, 0)
        for sgn in (1, -1):
            for k in range(3):
                tuft(chest + np.array([-0.3 * u + 0.4 * u * k, sgn * 1.5 * u * bulk, 0.7 * u]), (-0.3, sgn * 0.5, 1.0), 0.7 * u, 0.22 * u, 2)
            tuft(np.array([1.25 * u * bulk, sgn * 0.75 * u, hip_z + 1.0 * u]), (0.4, sgn * 0.3, 1.0), 0.6 * u, 0.16 * u, 2)   # presas da boca
    if kind == 'cuca':   # crista de escamas nas costas, xale e colar de ossos
        for k in range(8):
            w = k / 7
            z = hip_z + (0.9 + 1.7 * w) * u
            tuft((back_a * 0.95, 0.0, z), (-0.7, 0.0, 0.7), (0.5 + 0.15 * (k % 2)) * u, 0.3 * u, 0)
        for k in range(12):
            ang = -math.pi * 0.85 + k * (math.pi * 1.7 / 11)
            q = chest + np.array([0.9 * u * math.cos(ang) * 0.4 + 0.2 * u, 1.05 * u * math.sin(ang), 0.55 * u - 0.25 * u * abs(math.cos(ang))])
            add(q[0], q[1], q[2], 3, 0.5 * u)
        for k in range(9):
            ang = -math.pi * 0.45 + k * (math.pi * 0.9 / 8)
            q = chest + np.array([0.95 * u * math.cos(ang) + 0.2 * u, 0.9 * u * math.sin(ang), 0.2 * u - 0.35 * u * math.cos(ang)])
            add(q[0], q[1], q[2], 2, (0.18 if k % 2 else 0.12) * u)
    if kind == 'papao':   # ombros esfarrapados
        for side, sgn in (('l', 1), ('r', -1)):
            sh = chest + np.array([0.0, sgn * 1.45 * u * bulk, 0.3 * u])
            for k in range(4):
                tuft(sh + np.array([(-0.4 + 0.3 * k) * u, sgn * 0.3 * u, -0.1 * u]), (-0.1, sgn * 0.4, -1.0),
                     (1.0 + 0.4 * (k % 2)) * u, 0.3 * u, 3)
    # ---- cabeça (gira para cima no uivo)
    neck = chest + np.array([0.35 * u, 0.0, 0.9 * u])
    hu = math.radians(head_up)

    def hadd(p, mat, rad):
        d = np.array(p, float) - neck
        a2 = d[0] * math.cos(hu) - d[2] * math.sin(hu)
        z2 = d[0] * math.sin(hu) + d[2] * math.cos(hu)
        add(neck[0] + a2, neck[1] + d[1], neck[2] + z2, mat, rad)

    def hseg(p0, p1, r0, r1, mat):
        p0, p1 = np.array(p0, float), np.array(p1, float)
        L = np.linalg.norm(p1 - p0)
        k = max(2, int(L / (max(0.05 * u, min(r0, r1)) * 0.55)) + 1)
        for i in range(k):
            w = i / (k - 1)
            hadd(p0 + (p1 - p0) * w, mat, r0 + (r1 - r0) * w)

    if kind == 'lobisomem':
        H = neck + np.array([0.55 * u, 0, 0.35 * u])
        hadd(neck, 0, 0.8 * u)
        hadd(H, 0, 0.95 * u)
        # focinho: maxilar de cima e mandíbula que abre
        hseg(H + [0.5 * u, 0, 0.0], H + [1.9 * u, 0, -0.15 * u], 0.55 * u, 0.3 * u, 1)
        hadd(H + [2.05 * u, 0, -0.08 * u], 5, 0.2 * u)                       # nariz
        jo = 0.2 + 0.5 * jaw
        hseg(H + [0.4 * u, 0, -0.45 * u], H + [1.7 * u, 0, -0.45 * u - jo * u], 0.38 * u, 0.2 * u, 1)
        hadd(H + [1.1 * u, 0, -0.35 * u - 0.5 * jo * u], 5, 0.3 * u)          # boca
        for sgn in (1, -1):
            for k in range(3):
                hadd(H + [(1.0 + 0.3 * k) * u, sgn * 0.2 * u, -0.3 * u - 0.1 * k * u], 2, 0.09 * u)
            hseg(H + [-0.15 * u, sgn * 0.5 * u, 0.6 * u], H + [-0.45 * u, sgn * 0.65 * u, 1.65 * u], 0.34 * u, 0.06 * u, 0)
            hadd(H + [0.75 * u, sgn * 0.42 * u, 0.32 * u], 4, 0.17 * u)            # olhos
            hadd(H + [0.62 * u, sgn * 0.42 * u, 0.5 * u], 0, 0.16 * u)             # sobrancelha
            hseg(H + [0.1 * u, sgn * 0.7 * u, -0.2 * u], H + [-0.3 * u, sgn * 1.35 * u, -0.5 * u], 0.34 * u, 0.05 * u, 0)  # bochechas
            hseg(H + [-0.4 * u, sgn * 0.5 * u, -0.3 * u], H + [-0.9 * u, sgn * 1.1 * u, -0.9 * u], 0.3 * u, 0.05 * u, 0)
    elif kind == 'mapinguari':
        H = neck + np.array([0.2 * u, 0, 0.1 * u])
        hadd(H, 0, 1.2 * u)
        hadd(H + [0.1 * u, 0, 0.55 * u], 0, 1.0 * u)
        hadd(H + [1.05 * u, 0, 0.35 * u], 1, 0.46 * u)                          # órbita
        hadd(H + [1.28 * u, 0, 0.38 * u], 4, 0.32 * u)                          # o único olho
        for sgn in (1, -1):   # chifres curtos / tufos
            hseg(H + [0.0, sgn * 0.7 * u, 0.9 * u], H + [-0.3 * u, sgn * 1.2 * u, 1.6 * u], 0.3 * u, 0.08 * u, 2)
    elif kind == 'cuca':
        H = neck + np.array([0.5 * u, 0, 0.35 * u])
        hadd(neck, 0, 0.75 * u)
        hadd(H, 0, 0.95 * u)
        jo = 0.1 + 0.6 * jaw
        for sgn in (1, -1):   # focinho de jacaré, largo e chato: duas fileiras
            hseg(H + [0.5 * u, sgn * 0.25 * u, 0.05 * u], H + [2.6 * u, sgn * 0.18 * u, -0.1 * u], 0.45 * u, 0.3 * u, 0)
            hseg(H + [0.4 * u, sgn * 0.25 * u, -0.45 * u], H + [2.3 * u, sgn * 0.18 * u, -0.45 * u - jo * u], 0.34 * u, 0.22 * u, 0)
            for k in range(5):
                x = 0.9 + 0.4 * k
                hadd(H + [x * u, sgn * 0.42 * u, -0.28 * u], 2, 0.09 * u)
                hadd(H + [x * u - 0.1 * u, sgn * 0.36 * u, -0.28 * u - jo * u * (x - 0.4) / 1.9 + 0.1 * u], 2, 0.08 * u)
            hadd(H + [0.55 * u, sgn * 0.55 * u, 0.55 * u], 4, 0.2 * u)             # olhos saltados
            hadd(H + [0.45 * u, sgn * 0.55 * u, 0.72 * u], 0, 0.22 * u)            # pálpebra
            for k in range(4):                                                    # escamas em cima do focinho
                hadd(H + [(0.9 + 0.45 * k) * u, sgn * 0.2 * u, 0.42 * u - 0.05 * k * u], 0, 0.14 * u)
            hadd(H + [2.55 * u, sgn * 0.12 * u, 0.15 * u], 5, 0.08 * u)            # narinas
        hadd(H + [1.2 * u, 0, -0.35 * u - 0.5 * jo * u], 5, 0.3 * u)
        # cabelo loiro comprido, caindo pelas costas
        for k in range(13):
            ang = -math.pi * 0.85 + k * (math.pi * 1.7 / 12)
            root = H + np.array([-0.2 * u, 0.8 * u * math.sin(ang), 0.75 * u + 0.15 * u * math.cos(ang)])
            ln = 2.2 + 1.2 * ((k * 5) % 3) / 2
            for i in range(9):
                w = i / 8
                sway = 0.3 * u * w * math.sin(2 * math.pi * t + k * 1.3)
                frizz = 0.5 * u * w * math.sin(k * 2.3)
                hadd(root + np.array([-0.4 * u - 1.1 * u * w, 0.5 * u * math.sin(ang) * w + sway + frizz, 0.4 * u * w - ln * u * w * w]),
                     1, (0.3 - 0.22 * w) * u)
    elif kind == 'papao':
        H = neck + np.array([0.35 * u, 0, 0.15 * u])
        hadd(H, 3, 1.35 * u)                                                  # capuz
        hadd(H + [-0.3 * u, 0, 0.9 * u], 3, 0.85 * u)
        hadd(H + [-0.7 * u, 0, 1.5 * u], 3, 0.45 * u)                         # ponta do capuz
        hadd(H + [0.75 * u, 0, -0.1 * u], 5, 0.95 * u)                        # escuro dentro do capuz
        for k in range(11):                                                   # aba do capuz
            ang = -math.pi * 0.8 + k * (math.pi * 1.6 / 10)
            hadd(H + [0.95 * u + 0.25 * u * math.cos(ang), 1.05 * u * math.sin(ang), 0.1 * u + 1.0 * u * math.cos(ang)], 3, 0.3 * u)
        for sgn in (1, -1):
            hadd(H + [1.55 * u, sgn * 0.38 * u, 0.2 * u], 4, 0.18 * u)
        for k in range(-3, 4):                                                # sorriso de dentes
            w = k / 3
            hadd(H + [1.6 * u - 0.15 * u * w * w, w * 0.55 * u, -0.45 * u + 0.18 * u * w * w - 0.1 * jaw * u], 2, 0.1 * u)
    if pose.get('sink'):
        pts = [tuple(p[:3]) + (p[3] - pose['sink'],) + tuple(p[4:]) for p in pts]
    pose['pts'] = pts
    return pose


def prop_pose(sp, anim, f, n):
    """Objetos do acampamento (só 'stance', em loop): fogueira, portal da horda, altar do Santuário."""
    u = sp['r']
    t = f / n
    kind = sp['kind']
    pts = []
    sc = [0.0]

    def add(a, b, z, mat, rad):
        sc[0] += 1
        pts.append((sc[0], a, b, z, mat, rad))

    def seg(p0, p1, r0, r1, mat):
        p0, p1 = np.array(p0, float), np.array(p1, float)
        L = np.linalg.norm(p1 - p0)
        k = max(2, int(L / (min(r0, r1) * 0.55)) + 1)
        for i in range(k):
            w = i / (k - 1)
            q = p0 + (p1 - p0) * w
            add(q[0], q[1], q[2], mat, r0 + (r1 - r0) * w)

    def flame(x, y, z, height, width, mat, seed):
        for i in range(8):
            w = i / 7
            wob = 0.35 * width * w * math.sin(2 * math.pi * (t * 2 + w * 1.2 + seed))
            wob2 = 0.25 * width * w * math.cos(2 * math.pi * (t * 3 + w + seed * 1.7))
            h = height * (0.85 + 0.15 * math.sin(2 * math.pi * (t + seed)))
            add(x + wob2, y + wob, z + h * w, mat, width * (1.0 - 0.8 * w))

    if kind == 'campfire':
        for k in range(9):                                  # pedras
            ang = k * 2 * math.pi / 9
            add(math.cos(ang) * 1.5 * u, math.sin(ang) * 1.5 * u, 0.3 * u, 1, (0.42 + 0.06 * (k % 3)) * u)
        for k in range(4):                                  # lenha
            ang = k * math.pi / 2 + 0.4
            seg((math.cos(ang) * 1.2 * u, math.sin(ang) * 1.2 * u, 0.3 * u), (0, 0, 0.9 * u), 0.26 * u, 0.2 * u, 2)
        flame(0, 0, 0.6 * u, 2.8 * u, 0.9 * u, 3, 0.0)
        flame(0.4 * u, 0.3 * u, 0.6 * u, 1.8 * u, 0.55 * u, 3, 0.37)
        flame(-0.4 * u, -0.2 * u, 0.6 * u, 2.0 * u, 0.55 * u, 3, 0.71)
    elif kind == 'portal':
        # arco de pedra de frente para a câmera (plano b/z), redemoinho de fogo dentro
        for sgn in (-1, 1):
            for i in range(7):
                add(0, sgn * 2.3 * u, (0.4 + i * 0.75) * u, 1, (0.62 - 0.03 * i) * u)
        for i in range(11):
            ang = math.pi * i / 10
            add(0, -math.cos(ang) * 2.3 * u, 4.9 * u + math.sin(ang) * 1.3 * u, 1, 0.55 * u)
        for i in range(3):                                  # degrau
            add(0.2 * u, (i - 1) * 1.3 * u, 0.2 * u, 1, 0.6 * u)
        N = 34
        for k in range(N):                                  # espiral girando
            w = k / (N - 1)
            ang = w * 5.0 * math.pi + t * 2 * math.pi
            rad = (1.75 - 1.5 * w) * u
            add(0.05 * u, math.cos(ang) * rad, 3.2 * u + math.sin(ang) * rad * 1.15, 3, (0.34 + 0.18 * (1 - w)) * u)
        add(0.1 * u, 0, 3.2 * u, 3, 0.45 * u)
    elif kind == 'altar':
        for i in range(3):                                  # base em degraus
            add(0, 0, (0.3 + 0.5 * i) * u, 1, (1.5 - 0.3 * i) * u)
        for sgn in (-1, 1):
            add(0, sgn * 0.9 * u, 1.9 * u, 1, 0.55 * u)
        add(0, 0, 2.1 * u, 1, 0.8 * u)                      # tampo
        for k, (a, b) in enumerate(((0.5 * u, -0.9 * u), (0.6 * u, 0.0), (0.5 * u, 0.9 * u))):   # velas
            seg((a, b, 2.4 * u), (a, b, 3.0 * u), 0.16 * u, 0.16 * u, 2)
            flame(a, b, 3.1 * u, 0.5 * u, 0.13 * u, 3, k * 0.3)
        bob = 0.3 * u * math.sin(2 * math.pi * t)          # alma azul flutuando
        flame(0, 0, 3.4 * u + bob, 2.6 * u, 0.95 * u, 4, 0.5)
        flame(0.3 * u, 0.4 * u, 3.6 * u + bob, 1.6 * u, 0.45 * u, 4, 0.2)
        flame(-0.3 * u, -0.4 * u, 3.6 * u + bob, 1.8 * u, 0.45 * u, 4, 0.8)
    pose = dict(mouth=0.0, flash=0.0, dark=0.0, clip=None, eyes=False, dust=0.0, pts=pts)
    return pose


# ------------------------------------------------------------------ rendering
def pattern_mask(sp, S, NX, NY):
    """True where the darker color goes."""
    per = sp['period']
    fr = (S / per) % 1.0
    p = sp['pattern']
    if p == 'bands':
        return fr < 0.22
    if p == 'rings':
        return fr < 0.16
    if p == 'diamond':
        return np.abs(fr - 0.5) < 0.42 * (1 - np.abs(NX)) - 0.08
    if p == 'fur':   # tufos de pelo: listras curtas quebradas
        return np.sin(NX * 23.0 + NY * 5.0 + S * 1.3) > 0.82
    if p == 'spots':
        return ((fr - 0.5) * 2) ** 2 + ((np.abs(NX) - 0.45) * 2.4) ** 2 < 0.42
    return np.zeros_like(S, dtype=bool)


def colorize(sp, S, NX, NY, NZ, diff, rng):
    H, W = S.shape
    base = np.array(sp['base'], float); dark = np.array(sp['dark'], float); belly = np.array(sp['belly'], float)
    if sp['pattern'] == 'fire':
        flick = 0.85 + 0.3 * np.sin(S * 2.3 + NX * 3 + rng.random() * 6.28)
        heat = np.clip(NZ * flick, 0, 1)
        col = dark[None, None, :] * (1 - heat[..., None]) + base[None, None, :] * heat[..., None]
        col[(diff > 0.55) & (NZ > 0.55)] = belly
        return col
    if sp['pattern'] == 'flat':   # brilho próprio (olhos), sem sombra
        return np.broadcast_to(base, (H, W, 3)).copy()
    col = np.broadcast_to(base, (H, W, 3)).copy()
    col[pattern_mask(sp, S, NX, NY)] = dark
    bm = NY > 0.5
    col[bm] = col[bm] * 0.4 + belly * 0.6
    shade = 0.42 + 0.72 * np.clip(diff, 0, 1)
    col = col * (np.round(shade / 0.16) * 0.16)[..., None]
    if sp.get('sheen'):
        sh = diff > 0.88
        col[sh] = col[sh] * 0.4 + np.array([200, 225, 205]) * 0.6
    return col


def render(sp, pose, d, rng):
    W, H = sp['canvas']
    ox, oy = W // 2, int(H * 0.62)
    fwd = dir_vec(d)
    side = np.array([-fwd[1], fwd[0]])
    zbuf = np.full((H, W), -1e9)
    S = np.zeros((H, W)); NX = np.zeros((H, W)); NY = np.zeros((H, W)); NZ = np.zeros((H, W))
    shadow = np.zeros((H, W))
    yy, xx = np.mgrid[0:H, 0:W]
    clip = pose['clip']

    def to_screen(a, b, z):
        g = a * fwd + b * side
        return ox + g[0], oy + 0.5 * g[1] - C30 * z, g[1] * C30 + z * S30

    head_info = None
    MAT = np.zeros((H, W), np.int8)
    for idx, pt in enumerate(pose['pts']):
        s, a, b, z = pt[:4]
        mat = pt[4] if len(pt) > 4 else 0
        r = pt[5] if len(pt) > 5 else radius_at(sp, s)
        cx, cy, cd = to_screen(a, b, z)
        # sombra no chão
        if clip is None or z > -r:
            gx, gy, _ = to_screen(a, b, 0)
            strength = max(0.25, min(1.0, 1 - (z - r) / (4 * r)))
            x0, x1 = int(gx - r * 1.3) - 1, int(gx + r * 1.3) + 2
            y0, y1 = int(gy - r * 0.7) - 1, int(gy + r * 0.7) + 2
            x0, y0, x1, y1 = max(x0, 0), max(y0, 0), min(x1, W), min(y1, H)
            if x1 > x0 and y1 > y0:
                ex = (xx[y0:y1, x0:x1] - gx) / (r * 1.15)
                ey = (yy[y0:y1, x0:x1] - gy) / (r * 0.6)
                m = (ex * ex + ey * ey) <= 1
                shadow[y0:y1, x0:x1] = np.where(m, np.maximum(shadow[y0:y1, x0:x1], strength), shadow[y0:y1, x0:x1])
        x0, x1 = max(int(cx - r) - 1, 0), min(int(cx + r) + 2, W)
        y0, y1 = max(int(cy - r) - 1, 0), min(int(cy + r) + 2, H)
        if x1 <= x0 or y1 <= y0:
            continue
        dx = xx[y0:y1, x0:x1] + 0.5 - cx
        dy = yy[y0:y1, x0:x1] + 0.5 - cy
        q = r * r - dx * dx - dy * dy
        m = q > 0
        nz = np.sqrt(np.where(m, q, 0)) / r
        nx, ny = dx / r, dy / r
        depth = cd + nz * r
        if clip is not None:
            pz = z + r * (-C30 * ny + S30 * nz)
            m &= pz >= clip
        win = m & (depth > zbuf[y0:y1, x0:x1])
        zbuf[y0:y1, x0:x1] = np.where(win, depth, zbuf[y0:y1, x0:x1])
        S[y0:y1, x0:x1] = np.where(win, s, S[y0:y1, x0:x1])
        NX[y0:y1, x0:x1] = np.where(win, nx, NX[y0:y1, x0:x1])
        NY[y0:y1, x0:x1] = np.where(win, ny, NY[y0:y1, x0:x1])
        NZ[y0:y1, x0:x1] = np.where(win, nz, NZ[y0:y1, x0:x1])
        MAT[y0:y1, x0:x1] = np.where(win, mat, MAT[y0:y1, x0:x1])
        if idx == 0:
            head_info = (a, b, z, r)
    body = zbuf > -1e8

    # --- color (material 0 = a espécie; outros em sp['materials'])
    diff = NX * LIGHT[0] + NY * LIGHT[1] + NZ * LIGHT[2]
    col = colorize(sp, S, NX, NY, NZ, diff, rng)
    fire_px = np.zeros((H, W), bool) if sp['pattern'] != 'fire' else body.copy()
    for k, m in sp.get('materials', {}).items():
        sel = body & (MAT == k)
        if sel.any():
            col[sel] = colorize(dict(sp, **m), S, NX, NY, NZ, diff, rng)[sel]
            if m.get('pattern') == 'fire':
                fire_px |= sel
    # contorno: silhueta e bordas de profundidade (dobras do corpo)
    edge = np.zeros((H, W), bool)
    thr = sp['r'] * sp.get('edge', 0.6)
    for sx, sy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        nb = np.roll(np.roll(zbuf, sy, 0), sx, 1)
        nbody = np.roll(np.roll(body, sy, 0), sx, 1)
        edge |= body & (~nbody | (nb - zbuf > thr))
    col[edge] = col[edge] * 0.38
    if pose['dark']:
        col = col * (1 - pose['dark'])
    if pose['flash']:
        col = col * (1 - pose['flash']) + 255 * pose['flash']
    col = np.clip(col, 0, 255)

    img = np.zeros((H, W, 4), np.uint8)
    # sombra primeiro
    sa = (shadow * 90).astype(np.uint8)
    img[..., 3] = sa
    img[body, :3] = col[body].astype(np.uint8)
    img[body, 3] = 255
    im = Image.fromarray(img, 'RGBA')

    # buracos / terra (Minhocão) e poeira
    if pose.get('holes') or pose.get('dust'):
        im = draw_ground_fx(sp, pose, im, to_screen, rng)
    # boca e olhos em cima do corpo
    if head_info and sp['mode'] in ('snake', 'burrow'):
        im = draw_face(sp, pose, im, to_screen, fwd, side)
    if sp.get('glow') and fire_px.any():
        a = Image.fromarray((fire_px * 255).astype(np.uint8), 'L').filter(ImageFilter.GaussianBlur(sp['r'] * 0.7))
        glow = Image.new('RGBA', im.size, sp['glow'] + (0,))
        glow.putalpha(a.point(lambda v: int(v * max(0.0, 0.55 - pose['dark']))))
        glow.alpha_composite(im)
        im = glow
        im = draw_embers(sp, pose, im, rng, fire_px)
    return im, (ox, oy)


def draw_ground_fx(sp, pose, im, to_screen, rng):
    from PIL import ImageDraw
    r = sp['r']
    under = Image.new('RGBA', im.size, (0, 0, 0, 0))
    dr = ImageDraw.Draw(under)
    dirt, dirt_d, hole = (96, 66, 40, 255), (64, 42, 26, 255), (22, 14, 10, 255)
    for ha in pose.get('holes', []):
        cx, cy, _ = to_screen(ha, 0, 0)
        rx, ry = r * 1.55, r * 0.8
        dr.ellipse([cx - rx * 1.25, cy - ry * 1.25, cx + rx * 1.25, cy + ry * 1.25], fill=dirt_d)
        dr.ellipse([cx - rx * 1.1, cy - ry * 1.1, cx + rx * 1.1, cy + ry * 1.1], fill=dirt)
        dr.ellipse([cx - rx * 0.85, cy - ry * 0.85, cx + rx * 0.85, cy + ry * 0.85], fill=hole)
        for _ in range(int(r)):
            ang = rng.random() * 6.283
            dd = rx * (1.1 + rng.random() * 0.6)
            px, py = cx + math.cos(ang) * dd, cy + math.sin(ang) * dd * 0.5
            sz = 1 + rng.random() * r * 0.18
            dr.ellipse([px - sz, py - sz * 0.7, px + sz, py + sz * 0.7], fill=dirt if rng.random() < 0.5 else dirt_d)
    under.alpha_composite(im)
    im = under
    if pose.get('dust'):
        over = Image.new('RGBA', im.size, (0, 0, 0, 0))
        do = ImageDraw.Draw(over)
        pts = pose['pts']
        s0, a0, b0, z0 = pts[0][:4]
        spots = [(a0, b0)] if pose.get('slam') else []
        if pose.get('slam_a'):
            spots.append((pose['slam_a'], 0))
        spots += [(ha, 0) for ha in pose.get('holes', [])[:1]]
        if not spots:
            spots = [(0, 0)]
        for (a, b) in spots:
            cx, cy, _ = to_screen(a, b, 0)
            for _ in range(int(14 * pose['dust'])):
                ang = rng.random() * 6.283
                dd = r * (0.6 + rng.random() * 1.8)
                px, py = cx + math.cos(ang) * dd, cy + math.sin(ang) * dd * 0.5 - rng.random() * r * 1.4
                sz = 1 + rng.random() * r * 0.14
                c = (120 + int(rng.random() * 40), 90 + int(rng.random() * 30), 60, 220)
                do.ellipse([px - sz, py - sz, px + sz, py + sz], fill=c)
        im.alpha_composite(over)
    return im


def disk_points(center, normal, radius, n=24):
    normal = normal / (np.linalg.norm(normal) + 1e-9)
    helper = np.array([0, 0, 1.0]) if abs(normal[2]) < 0.9 else np.array([1.0, 0, 0])
    u = np.cross(normal, helper); u /= np.linalg.norm(u)
    v = np.cross(normal, u)
    return [center + radius * (u * math.cos(k * 2 * math.pi / n) + v * math.sin(k * 2 * math.pi / n)) for k in range(n)]


def draw_face(sp, pose, im, to_screen, fwd, side):
    from PIL import ImageDraw
    pts = pose['pts']
    if len(pts) < 3:
        return im
    (s0, a0, b0, z0), (s1, a1, b1, z1) = pts[0], pts[2]
    r = radius_at(sp, 0)
    if pose.get('clip') is not None and z0 < 0:
        return im

    def world(a, b, z):  # local -> ground xyz
        g = a * fwd + b * side
        return np.array([g[0], g[1], z])

    def scr(p):
        return (to_screen_ground(p))

    ox, oy = to_screen(0, 0, 0)[:2]

    def to_screen_ground(p):
        return (ox + p[0], oy + 0.5 * p[1] - C30 * p[2])

    c = world(a0, b0, z0)
    T = c - world(a1, b1, z1)
    T /= (np.linalg.norm(T) + 1e-9)
    dr = ImageDraw.Draw(im)
    facing = float(np.dot(T, VIEW))
    mouth = pose['mouth']
    if sp['mode'] == 'burrow':
        # bocarra circular com anel de dentes
        if facing > -0.15:
            mr = r * (0.45 + 0.4 * mouth)
            center = c + T * r * 0.62
            ring = [to_screen_ground(p) for p in disk_points(center, T, mr)]
            dr.polygon(ring, fill=(70, 12, 18, 255), outline=(40, 8, 10, 255))
            inner = [to_screen_ground(p) for p in disk_points(center - T * 0.2 * r, T, mr * 0.55)]
            dr.polygon(inner, fill=(25, 4, 6, 255))
            teeth = disk_points(center, T, mr * 0.95, n=12)
            tips = disk_points(center, T, mr * 0.55, n=12)
            for k in range(12):
                a = to_screen_ground(teeth[k]); b = to_screen_ground(teeth[(k + 1) % 12]); tp = to_screen_ground(tips[k])
                mid = ((a[0] + b[0]) / 2, (a[1] + b[1]) / 2)
                dr.polygon([a, mid, tp], fill=(235, 225, 190, 255))
        return im
    # cobra: olhos nos lados da cabeça, boca aberta na frente
    up = np.array([0, 0, 1.0])
    sd = np.cross(up, T)
    if np.linalg.norm(sd) < 1e-3:
        sd = np.array([side[0], side[1], 0])
    sd /= np.linalg.norm(sd)
    if mouth > 0.25 and facing > -0.3:
        center = c + T * r * 0.75 - up * r * 0.1
        mr = r * 0.62 * mouth
        ring = [to_screen_ground(p) for p in disk_points(center, T, mr, n=16)]
        inner = (255, 200, 60, 255) if sp['pattern'] == 'fire' else (120, 20, 30, 255)
        dr.polygon(ring, fill=inner, outline=(30, 6, 8, 255))
        for sgn in (-1, 1):
            base_p = center + up * mr * 0.8 + sd * sgn * mr * 0.45
            tip_p = base_p - up * mr * 0.7 + T * r * 0.1
            a = to_screen_ground(base_p); b = to_screen_ground(tip_p)
            dr.line([a, b], fill=(245, 240, 225, 255), width=max(1, int(r * 0.12)))
    if pose['eyes'] and sp['eyes']:
        es = sp.get('eye_size', 0.2) * r
        for sgn in (-1, 1):
            n = T * 0.45 + sd * sgn * 0.62 + up * 0.5
            n /= np.linalg.norm(n)
            if float(np.dot(n, VIEW)) < 0.05:
                continue
            p = to_screen_ground(c + n * r * 0.98)
            e = max(1.0, es)
            dr.ellipse([p[0] - e, p[1] - e * 0.8, p[0] + e, p[1] + e * 0.8], fill=sp['eyes'] + (255,))
            if e >= 2.5 and sp['pattern'] != 'fire':
                dr.ellipse([p[0] - e * 0.3, p[1] - e * 0.6, p[0] + e * 0.3, p[1] + e * 0.6], fill=(20, 10, 5, 255))
    return im


def draw_embers(sp, pose, im, rng, mask):
    from PIL import ImageDraw
    dr = ImageDraw.Draw(im)
    ys, xs = np.nonzero(mask)
    if len(xs) == 0:
        return im
    for _ in range(int(sp['r'] * 1.6 * (1 - pose['dark']))):
        i = rng.integers(0, len(xs))
        px, py = xs[i] + rng.normal(0, sp['r'] * 0.5), ys[i] - rng.random() * sp['r'] * 2.2
        c = (255, 230, 120, 255) if rng.random() < 0.5 else (255, 140, 40, 230)
        dr.rectangle([px, py, px + 1, py + 1], fill=c)
    return im


# ------------------------------------------------------------------ packing / output
def crop(im, origin):
    bbox = im.getbbox()
    if not bbox:
        return Image.new('RGBA', (1, 1)), (0, 0)
    return im.crop(bbox), (origin[0] - bbox[0], origin[1] - bbox[1])


def generate(name, sp):
    rng = np.random.default_rng(abs(hash(name)) % (2 ** 32))
    pose_fn = {'burrow': burrow_pose, 'quad': quad_pose, 'biped': biped_pose, 'beast': beast_pose, 'prop': prop_pose}.get(sp['mode'], snake_pose)
    frames = []  # (anim, index, dir, image, offset)
    anims = ANIMS_PROP if sp['mode'] == 'prop' else ANIMS
    for anim, n, _, _, _ in anims:
        for f in range(n):
            for d in range(8):
                pose = pose_fn(sp, anim, f, n)
                im, origin = render(sp, pose, 6 if sp['mode'] == 'prop' else d, rng)
                im, off = crop(im, origin)
                frames.append((anim, f, d, im, off))
    # shelf packing into 2048x2048 sheets
    order = sorted(range(len(frames)), key=lambda i: -frames[i][3].size[1])
    sheets, place = [], {}
    cur, x, y, shelf = None, 0, 0, 0
    for i in order:
        w, h = frames[i][3].size
        if cur is None or x + w > SHEET:
            x, y, shelf = 0, y + shelf, 0
        if cur is None or y + h > SHEET:
            cur = Image.new('RGBA', (SHEET, SHEET)); sheets.append(cur)
            x, y, shelf = 0, 0, 0
        cur.paste(frames[i][3], (x, y))
        place[i] = (len(sheets) - 1, x, y)
        x += w + 1
        shelf = max(shelf, h + 1)
    img_rel = []
    for k, sh in enumerate(sheets):
        bbox = sh.getbbox()
        sh = sh.crop((0, 0, SHEET, bbox[3]))
        rel = 'images/enemies/rd_%s_%d.png' % (name, k)
        os.makedirs(os.path.join(MOD, 'images/enemies'), exist_ok=True)
        sh.save(os.path.join(MOD, rel), optimize=True)
        img_rel.append(rel)
    out = [HEADER]
    for k, rel in enumerate(img_rel):
        out.append('image=%s,s%d\n' % (rel, k))
    durations = sp.get('durations', {})
    for anim, n, dur, typ, active in anims:
        out.append('\n[%s]\nframes=%d\nduration=%dms\ntype=%s\n' % (anim, n, durations.get(anim, dur), typ))
        if active is not None:
            out.append('active_frame=%d\n' % active)
        for i, (a, f, d, im, off) in enumerate(frames):
            if a != anim:
                continue
            k, x, y = place[i]
            out.append('frame=%d,%d,%d,%d,%d,%d,%d,%d,s%d\n' % (f, d, x, y, im.size[0], im.size[1], off[0], off[1], k))
    path = os.path.join(MOD, 'animations/enemies/rd_%s.txt' % name)
    with open(path, 'w', encoding='utf8') as fh:
        fh.write(''.join(out))
    print('%s: %d frames, %d sheet(s)' % (name, len(frames), len(sheets)))
    return frames


def preview(names):
    """One strip per species: stance/run/swing/cast/die, direction 6 (down) + 2."""
    out_dir = os.environ.get('PREVIEW_DIR', os.path.join(MOD, 'previews'))
    os.makedirs(out_dir, exist_ok=True)
    for name in names:
        sp = SPECIES[name]
        rng = np.random.default_rng(1)
        pose_fn = {'burrow': burrow_pose, 'quad': quad_pose, 'biped': biped_pose, 'beast': beast_pose, 'prop': prop_pose}.get(sp['mode'], snake_pose)
        tiles = []
        for anim, f, n, d in [('stance', 0, 4, 6), ('stance', 0, 4, 3), ('run', 2, 8, 7), ('run', 5, 8, 4),
                              ('swing', 0, 4, 5), ('swing', 2, 4, 5), ('cast', 2, 4, 6), ('die', 5, 6, 6),
                              ('spawn', 2, 6, 6)]:
            im, _ = render(sp, pose_fn(sp, anim, f, n), d, rng)
            tiles.append(im)
        W, H = sp['canvas']
        strip = Image.new('RGBA', (W * len(tiles), H), (150, 60, 45, 255))
        for i, t in enumerate(tiles):
            strip.alpha_composite(t, (i * W, 0))
        p = os.path.join(out_dir, 'serpents_%s.png' % name)
        strip.save(p)
        print(p)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    names = args or list(SPECIES)
    if '--preview' in sys.argv:
        preview(names)
        return
    for name in names:
        generate(name, SPECIES[name])


if __name__ == '__main__':
    main()
