#!/usr/bin/env python3
"""
Open-world generator ("modo mundo aberto"): Exiled-Kingdoms-style overworld,
a grid of outdoor areas connected at their edges. Each people/faction has its
own region and biome (goblin forest, undead swamp, orc badlands, mage woods...).

Source of truth (edit, then re-run):
  tools/world/regions.csv   region name, people, biome, music, enemy list, boss
  tools/world/zones.csv     one row per area: grid position, level range, town/dungeon/boss
  BIOMES / TOWNS below      terrain recipes and town NPCs

Writes (all GENERATED, don't hand-edit):
  maps/world/<zone>.txt                     the outdoor areas
  maps/world/dungeons/<zone>_*.txt          one procedural dungeon per zone with `dungeon`
  maps/procgen_rules/rd_world_<zone>.txt
  tilesetdefs/rd_<biome>.txt                biome = base tileset + color filter
  images/tilesets/rd_<biome>_*.png          (gitignored: ~5-9MB each, re-run to rebuild)
  npcs/rd_*.txt, animations/npcs/rd/*.txt, loot/rd_vendor_*.txt

Terrain is random but seeded by the zone id, so re-running gives the same maps
unless you change the zone/biome data (or SEED_SALT).

Usage: python3 tools/gen_world.py            (rebuilds tinted tilesets only if missing)
       python3 tools/gen_world.py --tilesets  (force rebuild of the tinted tileset images)
"""
import csv, math, os, random, re, sys
from PIL import Image

TOOLS = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(TOOLS)
MODS = os.path.dirname(MOD)
WDATA = os.path.join(TOOLS, 'world')
HEADER = '# GENERATED by tools/gen_world.py from tools/world/*.csv -- edit those, not this file.\n'
SEED_SALT = 'rd-world-1'
W = H = 50          # zone size in tiles
BORDER = 3          # thickness of the tree/rock wall around each zone
GAP = 4             # width of the passage to a neighbouring zone

# ------------------------------------------------------------------ biomes
# base: fantasycore tileset. tint: multiply filter for the whole tileset image.
# obstacles: (weight, [tile ids], collision)  1 = blocks all, 2 = blocks movement only
# density: fraction of the interior covered by obstacle clusters
G_TREES = [240, 241, 242, 243, 248, 249, 250, 251, 252, 253, 254, 255]
PINES = [248, 249, 250, 251]
LEAFY = [252, 253, 254, 255]
PALE = [240, 241, 242, 243]
DEAD = [244, 245, 246, 247]
ROCKS = [128, 129, 130, 131]
OBELISKS = [132, 133, 134, 135]
STUMPS = [136, 137]
PLANTS = list(range(112, 128))
DRY = [124, 125, 126, 127]
REEDS = [114, 115, 124, 125]
FLOWERS = [116, 117, 118, 119, 120, 121]

BIOMES = {
    'meadow':   dict(base='grassland', tint=None, density=0.18, border=G_TREES,
                     obstacles=[(6, LEAFY + PALE, 1), (1, ROCKS, 2)], decor=PLANTS, decor_rate=0.07, water=0),
    'darkwood': dict(base='grassland', tint=(150, 170, 140), density=0.34, border=PINES + LEAFY,
                     obstacles=[(7, PINES, 1), (3, LEAFY, 1), (1, DEAD, 1), (1, ROCKS, 2)], decor=PLANTS, decor_rate=0.10, water=0),
    'swamp':    dict(base='grassland', tint=(140, 150, 105), density=0.24, border=DEAD + PINES,
                     obstacles=[(6, DEAD, 1), (2, PINES, 1), (1, ROCKS, 2)], decor=REEDS, decor_rate=0.12, water=0),
    'arcane':   dict(base='grassland', tint=(205, 170, 255), density=0.2, border=PALE + LEAFY,
                     obstacles=[(5, PALE, 1), (2, LEAFY, 1), (1, ROCKS, 2)], decor=FLOWERS, decor_rate=0.10, water=0),
    'ashen':    dict(base='grassland', tint=(150, 145, 140), density=0.16, border=DEAD + ROCKS,
                     obstacles=[(4, ROCKS, 2), (3, DEAD, 1)], decor=DRY, decor_rate=0.05, water=0),
    'glacier':  dict(base='snowplains', tint=None, density=0.2, border=OBELISKS + DEAD,
                     obstacles=[(3, OBELISKS, 1), (3, DEAD, 1), (2, ROCKS, 2), (1, STUMPS, 2)], decor=PLANTS, decor_rate=0.04, water=0),
    'desert':   dict(base='snowplains', tint=(250, 215, 150), density=0.16, border=OBELISKS + ROCKS,
                     obstacles=[(3, ROCKS, 2), (2, OBELISKS, 1), (1, DEAD, 1)], decor=DRY, decor_rate=0.04, water=0),
    'badlands': dict(base='snowplains', tint=(225, 130, 100), density=0.2, border=ROCKS + DEAD + OBELISKS,
                     obstacles=[(4, ROCKS, 2), (2, DEAD, 1), (2, STUMPS, 2)], decor=DRY, decor_rate=0.05, water=0),
    'volcanic': dict(base='snowplains', tint=(150, 75, 60), density=0.2, border=OBELISKS + ROCKS,
                     obstacles=[(4, ROCKS, 2), (3, OBELISKS, 1), (2, DEAD, 1)], decor=DRY, decor_rate=0.03, water=0),
}
GROUND = 16          # 16..31: seamless 4x4 ground texture (same ids in both tilesets)
WATER = 176          # 176..191: water, same layout
CAVE = 224           # cave mouth object
CAMP = dict(fire=102, tent=72, crates=[96, 97, 98, 99], logs=[100, 101])

# ------------------------------------------------------------------ towns
# npc: (file id, name, animation, tint, portrait, vendor stock table or '', lines of dialog)
TOWNS = {
    'aurora': [
        ('aurora_ferreiro', 'Brom, o Ferreiro', 'guild_man1', None, 'male04', 'rd_vendor_general',
         ['Aço bom não se acha em árvore. Se quiser algo melhor que ferro, traga ouro.',
          'Dizem que no Planalto Cinzento os minotauros forjam adamantita. Loucura.']),
        ('aurora_alquimista', 'Mirela, a Alquimista', 'peasant_woman1', None, 'female03', 'rd_vendor_potions',
         ['Poções de vida e mana, frescas. Os mortos do pântano não perdoam quem vai sem elas.']),
        ('aurora_anciao', 'Ancião Tavros', 'knight', None, 'male12', '',
         ['Bem-vindo a Aurora, exilado. Este vale é o último lugar seguro da ilha.',
          'A oeste fica o Bosque Sombrio, tomado pelos goblins. Ao norte, o Pântano dos Lamentos, onde os mortos não descansam.',
          'A leste, as Dunas de Âmbar e a colmeia dos mirmeks. Além delas, as Terras Rubras dos orcs.',
          'Os magos se trancaram na Torre de Vidro, no Bosque Arcano. E no extremo norte... gelo, cinzas e fogo.']),
    ],
    'torre': [
        ('torre_arcanista', 'Arcanista Velya', 'guild_man2', (200, 160, 255), 'female09', 'rd_vendor_arcane',
         ['Varinhas, cajados, anéis. Tudo encantado, nada barato.']),
        ('torre_ferreiro', 'Ferreiro Rúnico Odo', 'guild_man1', (200, 170, 255), 'male07', 'rd_vendor_general',
         ['Os magos não ligam pra aço. Eu ligo.']),
        ('torre_arquimago', 'Arquimago Selen', 'wandering_trader2', (190, 150, 255), 'male16', '',
         ['Nossos experimentos escaparam para os jardins. Evocadores, bibliotecários espectrais, diabretes...',
          'Se limpar os Jardins Proibidos, a biblioteca afundada é sua para saquear.']),
    ],
    'forte': [
        ('forte_mercador', 'Mercador Kael', 'wandering_trader1', None, 'male09', 'rd_vendor_general',
         ['Último posto antes das Terras Rubras. O que os orcs não levaram, eu vendo.']),
        ('forte_alquimista', 'Irmã Dalla', 'peasant_woman2', None, 'female06', 'rd_vendor_potions',
         ['Cuide das feridas antes de subir para o acampamento de guerra.']),
        ('forte_capitao', 'Capitã Rhea', 'knight', (255, 200, 170), 'female12', '',
         ['O Rei Orc junta suas tropas no acampamento a leste. Cada orc que cai aqui é um a menos lá.']),
    ],
}

REGIONS_ALL = {}        # filled in main
ELITE_ODDS = 6          # a normal enemy is this many times likelier than an elite
ENEMY_GRADE = {}        # enemy id -> grade, from tools/ek_data/enemies.csv (filled in main)
ENEMY_EK = {}           # enemy id -> EK level (filled in main)
# An enemy's hp_mult/dmg_mult are relative to ITS OWN level (see enemies.csv),
# so it must spawn near that level: a zone only uses region enemies whose EK
# level is in [level_min + EK_BAND[0], level_max + EK_BAND[1]], each at its own
# EK level clamped to the zone's range. gen_content.py uses the same band for
# the per-zone dungeon categories (rd_dg_<zone>).
EK_BAND = (-3, 2)


def zone_enemies(z, cats):
    lo, hi = int(z['level_min']) + EK_BAND[0], int(z['level_max']) + EK_BAND[1]
    fit = [c for c in cats if lo <= ENEMY_EK.get(c, 0) <= hi]
    if fit:
        return fit
    # nothing in range: the closest ones
    near = min(abs(ENEMY_EK.get(c, 0) - int(z['level_min'])) for c in cats)
    return [c for c in cats if abs(ENEMY_EK.get(c, 0) - int(z['level_min'])) == near]
REGION_TOP_ZONE = {}    # region -> id of its highest-level zone (filled in main)

SIDES = {  # neighbour offset -> side of this map
    (0, -1): 'n', (0, 1): 's', (-1, 0): 'w', (1, 0): 'e',
}
OPPOSITE = {'n': 's', 's': 'n', 'w': 'e', 'e': 'w'}


def rel(*p):
    return os.path.join(MOD, *p)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf8') as f:
        f.write(text)


def load_csv(name):
    return list(csv.DictReader(open(os.path.join(WDATA, name), encoding='utf8')))


# ------------------------------------------------------------------ tilesets
def gen_tilesets(force):
    for biome, b in BIOMES.items():
        src = os.path.join(MODS, 'fantasycore/tilesetdefs/tileset_%s.txt' % b['base'])
        text = open(src, encoding='utf8').read()
        if b['tint']:
            def repl(m):
                img = m.group(1)
                out = 'images/tilesets/rd_%s_%s' % (biome, os.path.basename(img))
                if force or not os.path.exists(rel(out)):
                    im = Image.open(os.path.join(MODS, 'fantasycore', img)).convert('RGBA')
                    r, g, bl, a = im.split()
                    t = b['tint']
                    im = Image.merge('RGBA', (r.point(lambda v: v * t[0] // 255), g.point(lambda v: v * t[1] // 255),
                                              bl.point(lambda v: v * t[2] // 255), a))
                    os.makedirs(os.path.dirname(rel(out)), exist_ok=True)
                    im.save(rel(out), optimize=True)
                    print('  tileset image %s' % out)
                return 'img=' + out
            text = re.sub(r'^img=(.*)$', repl, text, flags=re.M)
        write(rel('tilesetdefs/rd_%s.txt' % biome), HEADER + text)


# ------------------------------------------------------------------ zone terrain
def side_gap(side):
    """cells of the passage on a side (at the very edge)."""
    c0 = W // 2 - GAP // 2
    if side == 'n': return [(c0 + i, 0) for i in range(GAP)]
    if side == 's': return [(c0 + i, H - 1) for i in range(GAP)]
    if side == 'w': return [(0, c0 + i) for i in range(GAP)]
    return [(W - 1, c0 + i) for i in range(GAP)]


def arrival(side):
    """where you appear when entering through `side`."""
    c = W // 2
    return {'n': (c, BORDER + 1), 's': (c, H - BORDER - 2), 'w': (BORDER + 1, c), 'e': (W - BORDER - 2, c)}[side]


def blob_mask(rng, density, n_clusters, W=W, H=H):
    """clustered noise: mark cells near random cluster centres."""
    m = [[0.0] * W for _ in range(H)]
    for _ in range(n_clusters):
        cx, cy = rng.uniform(0, W), rng.uniform(0, H)
        r = rng.uniform(2.0, 6.5)
        for y in range(max(0, int(cy - r)), min(H, int(cy + r) + 1)):
            for x in range(max(0, int(cx - r)), min(W, int(cx + r) + 1)):
                d = math.hypot(x - cx, y - cy)
                if d < r:
                    m[y][x] += 1 - d / r
    vals = sorted(v for row in m for v in row)
    cut = vals[int(len(vals) * (1 - density))] if density > 0 else 99
    return [[m[y][x] > cut and m[y][x] > 0 for x in range(W)] for y in range(H)]


def carve(clear, x, y, r):
    for yy in range(y - r, y + r + 1):
        for xx in range(x - r, x + r + 1):
            if 0 <= xx < W and 0 <= yy < H:
                clear[yy][xx] = True


def carve_path(rng, clear, a, b, width=1):
    x, y = a
    while (x, y) != b:
        carve(clear, x, y, width)
        dx, dy = b[0] - x, b[1] - y
        if rng.random() < 0.3:  # wander a bit
            if rng.random() < 0.5 and dy: y += (1 if rng.random() < 0.5 else -1)
            elif dx: x += (1 if rng.random() < 0.5 else -1)
        elif abs(dx) > abs(dy) or (abs(dx) == abs(dy) and rng.random() < 0.5):
            x += (dx > 0) - (dx < 0)
        else:
            y += (dy > 0) - (dy < 0)
        x = min(max(x, 1), W - 2); y = min(max(y, 1), H - 2)
    carve(clear, x, y, width)


def pick(rng, weighted):
    total = sum(w for w, _, _ in weighted)
    r = rng.uniform(0, total)
    for w, ids, col in weighted:
        if r < w:
            return rng.choice(ids), col
        r -= w
    return rng.choice(weighted[-1][1]), weighted[-1][2]


def gen_zone(z, zones_by_pos, regions, dungeon):
    rng = random.Random(SEED_SALT + z['id'])
    region = regions[z['region']]
    b = BIOMES[region['biome']]
    col, row = int(z['col']), int(z['row'])
    lvl_min, lvl_max = int(z['level_min']), int(z['level_max'])
    town = z['town']

    bg = [[GROUND + (y % 4) * 4 + (x % 4) for x in range(W)] for y in range(H)]
    obj = [[0] * W for _ in range(H)]
    colm = [[0] * W for _ in range(H)]
    clear = [[False] * W for _ in range(H)]   # must stay walkable
    events, npcs, enemies = [], [], []
    center = (W // 2, H // 2)

    # passages to neighbours
    exits = {}
    for (dx, dy), side in SIDES.items():
        n = zones_by_pos.get((col + dx, row + dy))
        if n:
            exits[side] = n
    for side in exits:
        for (x, y) in side_gap(side):
            carve(clear, x, y, 0)
        gx, gy = side_gap(side)[GAP // 2]
        inner = {'n': (gx, BORDER + 1), 's': (gx, H - BORDER - 2), 'w': (BORDER + 1, gy), 'e': (W - BORDER - 2, gy)}[side]
        for (x, y) in side_gap(side):
            ix = x if side in 'ns' else inner[0]
            iy = y if side in 'we' else inner[1]
            carve_path(rng, clear, (x, y), (ix, iy), 0)
        carve_path(rng, clear, inner, center, 1)

    # town square / points of interest
    if town:
        carve(clear, center[0], center[1], 8)
    else:
        carve(clear, center[0], center[1], 2)
    spots = []   # clearings for enemies / camps
    for _ in range(40):
        if len(spots) >= 9:
            break
        x, y = rng.randint(BORDER + 4, W - BORDER - 5), rng.randint(BORDER + 4, H - BORDER - 5)
        if math.hypot(x - center[0], y - center[1]) < (14 if town else 7):
            continue
        if any(math.hypot(x - sx, y - sy) < 8 for sx, sy in spots):
            continue
        if any(math.hypot(x - ax, y - ay) < 7 for ax, ay in (arrival(s) for s in exits)):
            continue
        spots.append((x, y))
        carve(clear, x, y, 2)
        carve_path(rng, clear, (x, y), center, 0)

    # dungeon entrance: a cave mouth near a corner, reachable from the centre
    cave = None
    if dungeon:
        corner = rng.choice([(BORDER + 4, BORDER + 4), (W - BORDER - 5, BORDER + 4), (BORDER + 4, H - BORDER - 5), (W - BORDER - 5, H - BORDER - 5)])
        cave = corner
        carve(clear, cave[0], cave[1] + 1, 2)
        carve_path(rng, clear, (cave[0], cave[1] + 2), center, 1)

    # water pools (swamp, oasis...)
    for _ in range(b['water']):
        cx, cy = rng.randint(BORDER + 5, W - BORDER - 6), rng.randint(BORDER + 5, H - BORDER - 6)
        rw, rh = rng.randint(2, 4), rng.randint(2, 4)
        for y in range(cy - rh, cy + rh + 1):
            for x in range(cx - rw, cx + rw + 1):
                if not clear[y][x] and ((x - cx) / (rw + .5)) ** 2 + ((y - cy) / (rh + .5)) ** 2 <= 1:
                    bg[y][x] = WATER + (y % 4) * 4 + (x % 4)
                    colm[y][x] = 2

    # obstacle clusters
    mask = blob_mask(rng, b['density'], 30)
    for y in range(H):
        for x in range(W):
            edge = x < BORDER or y < BORDER or x >= W - BORDER or y >= H - BORDER
            if clear[y][x] or colm[y][x]:
                continue
            if edge:
                obj[y][x] = rng.choice(b['border']); colm[y][x] = 1
            elif (mask[y][x] and rng.random() < 0.7) or rng.random() < 0.015:
                t, c = pick(rng, b['obstacles']); obj[y][x] = t; colm[y][x] = c
            elif rng.random() < b['decor_rate']:
                obj[y][x] = rng.choice(b['decor'])
    # decor on paths too (walkable plants), but never on exits
    for y in range(BORDER, H - BORDER):
        for x in range(BORDER, W - BORDER):
            if clear[y][x] and not obj[y][x] and rng.random() < b['decor_rate'] / 3:
                obj[y][x] = rng.choice(b['decor'])

    def put(x, y, tile, c=2):
        obj[y][x] = tile; colm[y][x] = c

    # cave mouth + trigger in front of it
    if cave:
        x, y = cave
        put(x, y, CAVE, 1)
        for yy in (y + 1,):
            for xx in (x - 1, x, x + 1):
                obj[yy][xx] = 0; colm[yy][xx] = 0
        events.append('[event]\ntype=event\nlocation=%d,%d,3,1\nactivate=on_trigger\nhotspot=%d,%d,1,1\n'
                      'intermap=maps/world/dungeons/%s.txt\ntooltip=%s\n' % (x - 1, y + 1, x, y, z['id'], dungeon))
        # a new DUNGEON_VERSION regenerates this save's cached layout on the next visit
        events.append('[event]\ntype=event\n# dungeon version %d\nlocation=0,0,1,1\nactivate=on_load\n'
                      'requires_not_status=rd_dg_%s_v%d\nset_status=rd_dg_%s_f1_reset,rd_dg_%s_v%d\n'
                      % (DUNGEON_VERSION, z['id'], DUNGEON_VERSION, z['id'], z['id'], DUNGEON_VERSION))
        # where the dungeon's stairs drop you back (see gen_dungeon)
        events.append('[event]\ntype=event\n# back from the dungeon\nlocation=%d,%d,1,1\nintermap_id=rd_cave\n' % (x, y + 3))

    # town: campfire in the middle, tents and crates around, NPCs in a ring
    if town:
        cx, cy = center
        put(cx, cy, CAMP['fire'])
        for i, (dx, dy) in enumerate([(-5, -4), (5, -4), (-5, 4), (5, 4)]):
            put(cx + dx, cy + dy, CAMP['tent'])
            put(cx + dx + 1, cy + dy + 1, rng.choice(CAMP['crates']))
        ring = [(0, -3), (3, 0), (0, 3), (-3, 0), (2, 2), (-2, -2)]
        for (npc_id, *_), (dx, dy) in zip(TOWNS[town], ring):
            npcs.append('[npc]\ntype=npc\nlocation=%d,%d,1,1\nfilename=npcs/rd_%s.txt\n' % (cx + dx, cy + dy, npc_id))

    # enemy groups in the clearings. Towns are safe (no groups at all).
    # Elites (enemies.csv grade=elite) only show up in the highest-level zone of
    # their region, and even there at 1/ELITE_ODDS the weight of a normal enemy.
    cats = zone_enemies(z, [c for c in region['enemies'].split(';') if c])
    top_zone = z['id'] == REGION_TOP_ZONE.get(z['region'])
    weighted = []
    for c in cats:
        if ENEMY_GRADE.get(c) == 'elite':
            if top_zone:
                weighted.append(c)
        else:
            weighted += [c] * ELITE_ODDS
    boss_spot = None
    if z['boss'] and region['boss'] and spots:
        boss_spot = max(spots, key=lambda s: math.hypot(s[0] - center[0], s[1] - center[1]))
    for (x, y) in spots:
        if town:
            continue
        if (x, y) == boss_spot:
            enemies.append('[enemy]\ntype=enemy\n# boss (stays dead until the hero visits a town)\nlocation=%d,%d,1,1\ncategory=%s\nnumber=1\n'
                           'spawn_level=fixed,%d\nrequires_not_status=rd_boss_down_%s\n'
                           % (x, y, region['boss'], lvl_max + 1, region['boss']))
            continue
        foe = rng.choice(weighted)
        # at its own level (+-1), kept inside the zone's range
        lvl = max(lvl_min, min(lvl_max, ENEMY_EK.get(foe, lvl_min) + rng.randint(-1, 1)))
        enemies.append('[enemy]\ntype=enemy\nlocation=%d,%d,3,3\ncategory=%s\nnumber=%s\nspawn_level=fixed,%d\n'
                       % (x - 1, y - 1, foe, rng.choice(['1,2', '2,3', '2,4']), lvl))
        if region['biome'] == 'badlands' and rng.random() < 0.5:   # orc war camps
            put(x + 2, y - 2, CAMP['tent']); put(x - 2, y + 2, CAMP['fire'])

    # passages
    for side, n in exits.items():
        cells = side_gap(side)
        xs = [c[0] for c in cells]; ys = [c[1] for c in cells]
        ax, ay = arrival(OPPOSITE[side])
        events.append('[event]\ntype=event\n# to %s\nlocation=%d,%d,%d,%d\nactivate=on_trigger\nhotspot=location\n'
                      'intermap=maps/world/%s.txt,%d,%d\ntooltip=%s\n'
                      % (n['id'], min(xs), min(ys), max(xs) - min(xs) + 1, max(ys) - min(ys) + 1, n['id'], ax, ay, n['name']))

    if town:
        # resting in a town brings every world boss back (EK respawns them on a timer)
        bosses = sorted(set(r['boss'] for r in REGIONS_ALL.values() if r['boss']))
        events.append('[event]\ntype=event\n# bosses respawn\nlocation=1,0,1,1\nactivate=on_load\nunset_status=%s\n'
                      % ','.join('rd_boss_down_%s' % b for b in bosses))
    hero = (center[0] + 1, center[1] + 2) if town else arrival(next(iter(exits))) if exits else center
    title = '%s — %s' % (z['name'], region['name']) if z['name'] != region['name'] else z['name']

    def layer(name, grid):
        return '[layer]\ntype=%s\ndata=\n%s\n\n' % (name, ',\n'.join(','.join(str(v) for v in r) for r in grid))

    out = [HEADER, '# %s | região: %s (%s) | bioma: %s | nível %d-%d\n\n'
           % (z['name'], region['name'], region['people'], region['biome'], lvl_min, lvl_max)]
    out.append('[header]\nwidth=%d\nheight=%d\ntilewidth=192\ntileheight=96\norientation=isometric\n'
               'background_color=0,0,0,255\nhero_pos=%d,%d\nmusic=music/%s.ogg\ntileset=tilesetdefs/rd_%s.txt\ntitle=%s\n\n'
               % (W, H, hero[0], hero[1], region['music'], region['biome'], title))
    out.append(layer('background', bg))
    out.append(layer('object', obj))
    out.append(layer('collision', colm))
    out.append('\n'.join(events) + '\n' + '\n'.join(npcs) + '\n' + '\n'.join(enemies))
    write(rel('maps/world/%s.txt' % z['id']), ''.join(out))
    return len(enemies)


# ------------------------------------------------------------------ mode maps
# Infinite run: one open arena per biome; maps/run/start.txt sends each new run
# to a random one (HordeManager is active on everything under maps/run/, see
# engine/horde.txt). Test room: maps/dev_room.txt, where the dev kit button shows.
RUN_BIOMES = ['meadow', 'desert', 'badlands', 'glacier', 'swamp', 'volcanic', 'arcane', 'ashen']
ARENA = 80
DEV = 30


def open_map(map_id, biome, size, density, title, music, events, seed, hero=None, npcs=()):
    rng = random.Random(SEED_SALT + seed)
    b = BIOMES[biome]
    bg = [[GROUND + (y % 4) * 4 + (x % 4) for x in range(size)] for y in range(size)]
    obj = [[0] * size for _ in range(size)]
    colm = [[0] * size for _ in range(size)]
    c = size // 2
    mask = blob_mask(rng, density, size // 3, size, size)
    for y in range(size):
        for x in range(size):
            if x < BORDER or y < BORDER or x >= size - BORDER or y >= size - BORDER:
                obj[y][x] = rng.choice(b['border']); colm[y][x] = 1
            elif math.hypot(x - c, y - c) < 6:
                continue
            elif mask[y][x] and rng.random() < 0.6:
                t, cc = pick(rng, b['obstacles']); obj[y][x] = t; colm[y][x] = cc
            elif rng.random() < b['decor_rate']:
                obj[y][x] = rng.choice(b['decor'])
    for ev in events:  # keep event cells walkable
        x, y = ev[0], ev[1]
        for yy in range(y - 1, y + 2):
            for xx in range(x - 1, x + 2):
                obj[yy][xx] = 0; colm[yy][xx] = 0
    hero = hero or (c, c)

    def layer(name, grid):
        return '[layer]\ntype=%s\ndata=\n%s\n\n' % (name, ',\n'.join(','.join(str(v) for v in r) for r in grid))
    out = [HEADER, '[header]\nwidth=%d\nheight=%d\ntilewidth=192\ntileheight=96\norientation=isometric\n'
           'background_color=0,0,0,255\nhero_pos=%d,%d\nmusic=music/%s.ogg\ntileset=tilesetdefs/rd_%s.txt\ntitle=%s\n\n'
           % (size, size, hero[0], hero[1], music, biome, title)]
    out += [layer('background', bg), layer('object', obj), layer('collision', colm)]
    for ev in events:
        x, y, target, tooltip = ev[:4]
        size = ev[4] if len(ev) > 4 else 1   # square area centred on x,y (around a prop that blocks its own tile)
        # "book:rd:sanctuary" opens a menu (GameStatePlay turns that book into the Sanctuary)
        action = ('book=%s' % target[5:]) if target.startswith('book:') else ('intermap=%s' % target)
        out.append('[event]\ntype=event\nlocation=%d,%d,%d,%d\nactivate=on_trigger\nhotspot=location\n'
                   '%s\ntooltip=%s\n\n' % (x - size // 2, y - size // 2, size, size, action, tooltip))
    for x, y, npc in npcs:
        out.append('[npc]\ntype=npc\nlocation=%d,%d,1,1\nfilename=npcs/rd_%s.txt\n\n' % (x, y, npc))
    write(rel(map_id), ''.join(out))


def run_edition():
    """engine/edition.txt says 'run' in the commercial (infinite run only) build."""
    try:
        return 'edition=run' in open(rel('engine/edition.txt'), encoding='utf8').read()
    except OSError:
        return False


def gen_mode_maps():
    exit_world = 'maps/world/aurora_a.txt,26,27'
    camp = 'maps/lobby.txt'
    # leaving a horde early goes back to camp (in every edition)
    arena_exit = [(ARENA // 2 + 4, ARENA // 2 + 4, camp, 'Abandonar a horda (voltar ao acampamento)')]
    for biome in RUN_BIOMES:
        open_map('maps/run/arena_%s.txt' % biome, biome, ARENA, BIOMES[biome]['density'] / 3,
                 'Horda Infinita', 'battle_theme', arena_exit, 'arena' + biome)
    # start.txt: several on_load teleports; the engine stops at the FIRST one
    # that passes its chance, so chances 1/n, 1/(n-1), ..., 1/1 give every
    # arena the same odds.
    ev = []
    for i, biome in enumerate(RUN_BIOMES):
        ev.append('[event]\ntype=event\nlocation=0,0,1,1\nactivate=on_load\nchance_exec=%.2f\n'
                  'intermap=maps/run/arena_%s.txt\n' % (100.0 / (len(RUN_BIOMES) - i), biome))
    write(rel('maps/run/start.txt'), HEADER + '# Sorteia a arena da horda (uma por bioma).\n[header]\nwidth=1\nheight=1\nhero_pos=0,0\n\n'
          + '\n'.join(ev))
    # Acampamento (lobby): todo mundo começa aqui, solo ou em grupo, e volta
    # aqui quando a horda acaba. Monta a build (ferreiro, alquimista,
    # arcanista, Santuário) e entra na horda pelo portal. Fica FORA de
    # maps/run/ -- o HordeManager liga em qualquer mapa daquela pasta.
    # Em grupo, só o anfitrião leva todos pelo portal (GameStatePlay::checkTeleport).
    c = DEV // 2
    portal, altar, fire = (c - 3, c + 4), (c + 4, c + 3), (c + 1, c - 2)
    camp_events = [(portal[0], portal[1], 'maps/run/start.txt', 'Iniciar Horda', 3),
                   (altar[0], altar[1], 'book:rd:sanctuary', 'Santuário (bênçãos permanentes)', 3)]
    # (no world/training portals: the commercial build ships this same map)
    # props: sprites from tools/gen_serpents.py (camp_*), placed as silent NPCs
    for npc_id, name in (('camp_fogueira', 'Fogueira'), ('camp_portal', 'Portal da Horda'),
                         ('camp_altar', 'Altar do Santuário')):
        write(rel('npcs/rd_%s.txt' % npc_id), HEADER + 'name=%s\ntalker=false\n'
              'direction=6\nanimations=animations/enemies/rd_%s.txt\n' % (name, npc_id))
    open_map(camp, 'meadow', DEV, 0, 'Acampamento', 'safe_room_theme', camp_events, 'lobby',
             npcs=[(c - 4, c - 4, 'aurora_ferreiro'), (c + 4, c - 4, 'aurora_alquimista'), (c - 6, c + 1, 'torre_arcanista'),
                   (fire[0], fire[1], 'camp_fogueira'), (portal[0], portal[1], 'camp_portal'), (altar[0], altar[1], 'camp_altar')])
    open_map('maps/dev_room.txt', 'meadow', DEV, 0, 'Treinamento', 'safe_room_theme',
             [(DEV - 6, 6, exit_world, 'Mundo Aberto: Aurora'), (6, DEV - 6, camp, 'Acampamento')], 'dev',
             npcs=[(DEV // 2 - 4, DEV // 2 - 4, 'aurora_ferreiro'), (DEV // 2 + 4, DEV // 2 - 4, 'aurora_alquimista'),
                   (DEV // 2 - 4, DEV // 2 + 4, 'torre_arcanista')])


# ------------------------------------------------------------------ dungeons
IL = 'empyrean_campaign/maps/iron_labyrinth/'
# Bump when the dungeon rooms change: every save regenerates its cached
# dungeon layouts on the next visit (the engine caches procgen maps per save).
DUNGEON_VERSION = 3
IL_SCRIPTS = 'empyrean_campaign/scripts/maps/iron_labyrinth/'


def dungeon_chunk(text, z, region):
    """Adapt one Iron Labyrinth room chunk to this zone's dungeon."""
    prefix = 'rd_dg_%s_' % z['id']
    level = int(z['level_max']) + 1
    t = text.replace('emp_il_', prefix)                      # own door/chest/room statuses
    t = re.sub(r'category=il_\w+', 'category=rd_dg_%s' % z['id'], t)   # region monsters of this zone's level band
    t = re.sub(r'spawn_level=hero_level,[\d.]+', 'spawn_level=fixed,%d' % level, t)
    t = t.replace('loot=loot/il_chest_common.txt', 'loot=loot/rd_drop_elite.txt')
    t = t.replace('filename=npcs/il_loren.txt', 'filename=npcs/rd_dungeon_trader.txt')
    t = re.sub(r'script=scripts/maps/iron_labyrinth/(f1_key_chest_\d)\.txt',
               lambda m: 'script=scripts/world/%s_%s.txt' % (z['id'], m.group(1)), t)
    # campaign story notes and the warp room teleporter don't exist here
    t = re.sub(r'\nscript=scripts/maps/iron_labyrinth/(notes_drop\w*|warp_tele)\.txt', '', t)
    return t


def gen_dungeon(z, region):
    """
    One procedural dungeon per zone with a `dungeon` column: the Iron Labyrinth
    room chunks, copied and adapted (region monsters at a fixed level, own
    door/chest statuses, our loot). Entering sets the floor status the rooms
    need for their doors and key chests. The layout is generated once per save
    and then cached by the engine, like a fixed EK dungeon.
    """
    zid = z['id']
    prefix = 'rd_dg_%s_' % zid
    folder = 'maps/world/dungeons/%s' % zid
    rules = open(os.path.join(MODS, 'empyrean_campaign/maps/procgen_rules/iron_labyrinth.txt'), encoding='utf8').read()
    chunks = re.findall(r'^filename=maps/iron_labyrinth/(\S+)$', rules, re.M)
    out_chunks = []
    for c in chunks:
        text = open(os.path.join(MODS, IL, c), encoding='utf8').read()
        write(rel('%s/%s' % (folder, c.replace('/', '_'))), HEADER + dungeon_chunk(text, z, region))
        out_chunks.append('%s/%s' % (folder, c.replace('/', '_')))

    # start room: stairs back up to the cave, floor status on load
    start = dungeon_chunk(open(os.path.join(MODS, IL, 'f1/start.txt'), encoding='utf8').read(), z, region)
    events = start.split('\n[event]')
    keep = [events[0]]
    for e in events[1:]:
        if 'Stairs Up' in e:
            e = re.sub(r'intermap=.*', 'intermap=maps/world/%s.txt,-1,-1,rd_cave' % zid, e)
            e = re.sub(r'tooltip=.*', 'tooltip=%s' % z['name'], e)
            keep.append(e)
        elif 'Spawn point' in e or 'Reset Floor' in e:
            keep.append(e)
    keep.append('\n# floor status the rooms need (doors, key chests)\ntype=event\nlocation=2,0,1,1\nactivate=on_load\nset_status=%sf1\n' % prefix)
    write(rel('%s/start.txt' % folder), HEADER + '\n[event]'.join(keep))

    # end room: the stairs down become the way out, guarded by the region's elite
    end = dungeon_chunk(open(os.path.join(MODS, IL, 'f1/end.txt'), encoding='utf8').read(), z, region)
    end = re.sub(r'intermap=maps/iron_labyrinth_f2\.txt', 'intermap=maps/world/%s.txt,-1,-1,rd_cave' % zid, end)
    end = re.sub(r'tooltip=Iron Labyrinth: Level 2', 'tooltip=%s' % z['name'], end)
    end = re.sub(r'\nset_status=%sf2' % prefix, '', end)
    elite = [c for c in region['enemies'].split(';') if ENEMY_GRADE.get(c) == 'elite']
    guard = 'rd_regelite_%s' % region['id'] if elite else 'rd_reg_%s' % region['id']
    end += ('\n[enemy]\ntype=enemy\n# guardian of the way out\nlocation=10,8,8,3\ncategory=%s\nnumber=1\nspawn_level=fixed,%d\n'
            % (guard, int(z['level_max']) + 2))
    write(rel('%s/end.txt' % folder), HEADER + end)

    # key-chest scripts with this dungeon's statuses and our loot
    for n in (1, 2):
        sc = open(os.path.join(MODS, IL_SCRIPTS, 'f1_key_chest_%d.txt' % n), encoding='utf8').read()
        sc = sc.replace('emp_il_', prefix).replace('loot=loot/il_chest_common.txt', 'loot=loot/rd_drop_elite.txt')
        write(rel('scripts/world/%s_f1_key_chest_%d.txt' % (zid, n)), HEADER + sc)

    settings = open(rel('maps/procgen_rules/random_dungeon.txt'), encoding='utf8').read()
    settings = settings[settings.index('[settings]'):settings.index('[chunks]')]
    write(rel('maps/procgen_rules/rd_world_%s.txt' % zid), HEADER + settings + '[chunks]\nfilename=%s/start.txt\nfilename=%s/end.txt\n'
          % (folder, folder) + ''.join('filename=%s\n' % c for c in out_chunks if not c.endswith(('f1_start.txt', 'f1_end.txt'))))
    d = open(rel('maps/dungeon.txt'), encoding='utf8').read()
    d = d.replace('maps/procgen_rules/random_dungeon.txt', 'maps/procgen_rules/rd_world_%s.txt' % zid)
    d = re.sub(r'title=.*', 'title=%s' % z['dungeon'], d)
    d = re.sub(r'music=.*', 'music=music/dungeon_theme.ogg', d)
    d = d.replace('[header]\n', '[header]\nprocgen_reset_status=%sf1_reset\n' % prefix, 1)
    write(rel('maps/world/dungeons/%s.txt' % zid), HEADER + d)
    # the old single-file start room from the first version
    old = rel('maps/world/dungeons/%s_start.txt' % zid)
    if os.path.exists(old):
        os.remove(old)


# ------------------------------------------------------------------ npcs & vendors
def gen_npcs():
    write(rel('npcs/rd_dungeon_trader.txt'), HEADER + 'name=Mercador Perdido\nportrait=images/portraits/male11.png\ntalker=true\n'
          'animations=animations/npcs/wandering_trader2.txt\n\nvendor=true\nconstant_stock=2:5,3:5\n'
          'random_stock=loot/rd_vendor_general.txt\nrandom_stock_count=8,12\n\n[dialog]\ntopic=Conversar\n'
          'him=Me perdi aqui embaixo faz tempo. Pelo menos os monstros não compram nada.\n')
    for town, npcs in TOWNS.items():
        for npc_id, name, anim, tint, portrait, stock, lines in npcs:
            anim_path = 'animations/npcs/%s.txt' % anim
            if tint:
                tp = 'animations/npcs/rd/%s.txt' % npc_id
                write(rel(tp), HEADER + 'color_mod=%d,%d,%d\n\nINCLUDE %s\n' % (tint + (anim_path,)))
                anim_path = tp
            out = [HEADER, 'name=%s\nportrait=images/portraits/%s.png\ntalker=true\nanimations=%s\n' % (name, portrait, anim_path)]
            if stock:
                out.append('\nvendor=true\n')
                if stock == 'rd_vendor_potions':
                    out.append('constant_stock=2:20,3:20\n')
                else:
                    out.append('constant_stock=2:5,3:5\nrandom_stock=loot/%s.txt\nrandom_stock_count=12,18\n' % stock)
            for i, line in enumerate(lines):
                out.append('\n[dialog]\ntopic=%s\nhim=%s\n' % ('Conversar' if i == 0 else 'Mais...', line))
            write(rel('npcs/rd_%s.txt' % npc_id), ''.join(out))


def gen_vendor_loot():
    items = list(csv.DictReader(open(os.path.join(TOOLS, 'ek_data/items.csv'), encoding='utf8')))
    arcane = lambda it: it['dmg_type'] == 'ment' or '/armor/mage' in it['base'] or '/rings/' in it['base'] or '/necklaces/' in it['base']
    for name, keep in (('rd_vendor_general', lambda it: it['band'] in ('common', 'uncommon')),
                       ('rd_vendor_arcane', lambda it: it['band'] in ('common', 'uncommon', 'rare') and arcane(it))):
        out = [HEADER, '# vendor stock: items within ~3 levels of the player\n']
        for it in items:
            if keep(it):
                l = int(it['level'])
                out.append('\n[loot]\nid=%s\nchance=100\nquantity=1\nrequires_level=%d,%d\n' % (it['id'], max(1, l - 3), l + 4))
        write(rel('loot/%s.txt' % name), ''.join(out))


def main():
    regions = {r['id']: r for r in load_csv('regions.csv')}
    REGIONS_ALL.update(regions)
    zones = load_csv('zones.csv')
    for e in csv.DictReader(open(os.path.join(TOOLS, 'ek_data/enemies.csv'), encoding='utf8')):
        ENEMY_GRADE[e['id']] = e['grade']
        ENEMY_EK[e['id']] = int(e['ek_level'])
    for z in zones:
        cur = REGION_TOP_ZONE.get(z['region'])
        if cur is None or int(z['level_max']) > int(next(x for x in zones if x['id'] == cur)['level_max']):
            REGION_TOP_ZONE[z['region']] = z['id']
    by_pos = {(int(z['col']), int(z['row'])): z for z in zones}
    gen_tilesets('--tilesets' in sys.argv)
    gen_npcs()
    gen_vendor_loot()
    gen_mode_maps()
    total = 0
    for z in zones:
        total += gen_zone(z, by_pos, regions, z['dungeon'])
        if z['dungeon']:
            gen_dungeon(z, regions[z['region']])
    print('world: %d zones, %d dungeons, %d enemy groups, %d towns'
          % (len(zones), sum(1 for z in zones if z['dungeon']), total, sum(1 for z in zones if z['town'])))


if __name__ == '__main__':
    main()
